### ISSUE TITLE
docs: writes (towncrier) files when evaluating Sphinx config

### ISSUE THREAD

**Issue by blueyed** [tox-dev/tox#1177] opened 2019-02-27 08:49 UTC
The following code gets executed when Sphinx loads the config:
https://github.com/blueyed/tox/blob/76c089ec6c06aff47d5685ca07da806170ce8d5a/docs/conf.py#L23-L48

This happens e.g. when linting via `sphinx-build -n -E -q -N -b dummy …/Vcs/tox/docs /tmp/nvimJRKBlE/4`, where it then fails with an error even:

```
Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/usr/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "…/Vcs/tox/docs/conf.py", line 49, in <module>
    generate_draft_news()
  File "…/Vcs/tox/docs/conf.py", line 25, in generate_draft_news
    home = "https://github.com"
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'towncrier': 'towncrier'
```

Traceback for the call to `generate_draft_news`:

```
[0]   /home/user/.local/bin/sphinx-build(11)<module>()
-> load_entry_point('Sphinx', 'console_scripts', 'sphinx-build')()
[1]   /usr/lib/python3.7/site-packages/sphinx/cmd/build.py(319)main()
-> return build_main(argv)
[2]   /usr/lib/python3.7/site-packages/sphinx/cmd/build.py(303)build_main()
-> args.tags, args.verbosity, args.jobs, args.keep_going)
[3]   /usr/lib/python3.7/site-packages/sphinx/application.py(201)__init__()
-> self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
[4]   /usr/lib/python3.7/site-packages/sphinx/config.py(203)read()
-> namespace = eval_config_file(filename, tags)
[5]   /usr/lib/python3.7/site-packages/sphinx/config.py(368)eval_config_file()
-> execfile_(filename, namespace)
[6]   /usr/lib/python3.7/site-packages/sphinx/util/pycompat.py(150)execfile_()
-> exec_(code, _globals)
[7]   …/Vcs/tox/docs/conf.py(49)<module>()
-> generate_draft_news()
[8] > …/Vcs/tox/docs/conf.py(25)generate_draft_news()
-> home = "https://github.com"
```

**Comment by blueyed** [comment] 2019-02-27 08:52
To be clear: I think it should not run code / subprocesses when the config gets evaluated.

As for the linting command: this is used by Neomake (a Vim plugin) for `.rst` files.

**Comment by gaborbernat** [comment] 2019-02-27 09:03
This is by design, we could hook it up to run upon doc generation but no one complained that running during evaluation to be troublesome until now. Feel free to add a pr to move the subprocess call only during doc generation and not config load.

**Comment by blueyed** [comment] 2019-02-27 09:14
> Feel free to add a pr to move the subprocess call only during doc generation and not config load.

`towncrier` (the subprocess) fails to run.
It gets written via/in https://github.com/blueyed/tox/blob/70424581866443ad1bef9903d594a63a1ff8d415/docs/conf.py#L27-L32.

I don't know my way around Sphinx unfortunately.
Should some hook (similar to `setup`) be used?

**Comment by gaborbernat** [comment] 2019-02-27 09:20
I don't deeply either, none of my linters run the code automatically, or run it from root of the project, so did not run into this issue. Maybe, you should just fix that towncrier does not fail.

**Comment by blueyed** [comment] 2019-02-27 10:37
Well, the first issue here already is, that the file gets rewritten (for `home` and `issue` replacements), and that could be skipped if the text was not changed.
But I think it should not auto-fix files under version control in the first place.

**Comment by gaborbernat** [comment] 2019-02-27 10:39
the changes should happen only on drafts one which is not version controlled

**Comment by blueyed** [comment] 2019-02-27 10:42
It runs on `docs/changelog/1176.feature.rst` for me?!
With `fragments_path = ROOT_SRC_TREE_DIR / "docs" / "changelog"` and `.glob("*.rst")` that is also what is expected, no?
I am not complaining about the subprocess here in the first place.

**Comment by blueyed** [comment] 2019-02-27 10:43
Re improving the Sphinx integration, it should probably also respect the OUTPUTDIR (/tmp/nvimJRKBlE/4).

**Comment by gaborbernat** [comment] 2019-03-11 12:21
I don't think it's about temp dir, it's more the case we should not rewrite those files 👍

**Comment by gaborbernat** [comment] 2022-01-13 10:15
I think this should now be fixed with version 4 (rewrite branch). If still reproducible please post it and we'll reopen it.

**Closed by gaborbernat** 2022-01-13 10:15 UTC
Labels: bug:minor, type:internal, help:wanted
