### ISSUE TITLE
test_pythonpath_usage is failed

### ISSUE THREAD

**Issue by stanislavlevin** [tox-dev/tox#655] opened 2017-10-24 11:53 UTC
Using command:

 `TOX_TESTENV_PASSENV='PYTHONPATH' python setup.py pytest --addopt "--verbose --cov-config=tox.ini --cov=tox --timeout=180 --pdb -k test_pythonpath_usage"`

Error log:

```
running pytest
running egg_info
writing requirements to tox.egg-info/requires.txt
writing tox.egg-info/PKG-INFO
writing top-level names to tox.egg-info/top_level.txt
writing dependency_links to tox.egg-info/dependency_links.txt
writing entry points to tox.egg-info/entry_points.txt
reading manifest file 'tox.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'tox.egg-info/SOURCES.txt'
running build_ext
========================================== test session starts ==========================================
platform linux2 -- Python 2.7.11, pytest-3.2.1, py-1.4.34, pluggy-0.4.0 -- /usr/bin/python
cachedir: .cache
tox comes from: '/usr/src/RPM/BUILD/python-module-tox-2.9.1/tox/__init__.pyc'
rootdir: /usr/src/RPM/BUILD/python-module-tox-2.9.1, inifile: tox.ini
plugins: xdist-1.11, timeout-1.2.0, cov-2.4.0
timeout: 180.0s method: signal
collected 303 items                                                                                      

tests/test_venv.py::TestVenvTest::test_pythonpath_usage FAILED
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> traceback >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

self = <test_venv.TestVenvTest instance at 0x7f90005f4b90>
newmocksession = <function newmocksession at 0x7f90006ae140>
monkeypatch = <_pytest.monkeypatch.MonkeyPatch instance at 0x7f90005e6e18>

    def test_pythonpath_usage(self, newmocksession, monkeypatch):
        monkeypatch.setenv("PYTHONPATH", "/my/awesome/library")
        mocksession = newmocksession([], """
                [testenv:python]
                commands=abc
            """)
        venv = mocksession.getenv("python")
        action = mocksession.newaction(venv, "getenv")
        venv.run_install_command(['qwe'], action=action)
>       assert 'PYTHONPATH' not in os.environ
E       AssertionError: assert 'PYTHONPATH' not in {'LESS': '-MM', 'LESSOPEN': '|/usr/share/less/lesspipe.sh %s', 'LOGNAME': 'builder', 'USER': 'builder', 'HOME': '/usr/...a=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'}
E        +  where {'LESS': '-MM', 'LESSOPEN': '|/usr/share/less/lesspipe.sh %s', 'LOGNAME': 'builder', 'USER': 'builder', 'HOME': '/usr/...a=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'} = os.environ

tests/test_venv.py:576: AssertionError
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PDB >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> /usr/src/RPM/BUILD/python-module-tox-2.9.1/tests/test_venv.py(576)test_pythonpath_usage()
-> assert 'PYTHONPATH' not in os.environ
(Pdb) os.environ['PYTHONPATH']
'/my/awesome/library'
```

**Comment by obestwalter** [comment] 2017-11-05 16:40
Hi @stanislavlevin, can you explain what you are trying to accomplish? You are calling the test in a way that I don't understand - ``python setup.py pytest`` does not work at all in my setup and I don't understand why you want to run the tests like that. I also do not understand why passing PYTHONPATH is necessary in your setup. If you would explain what problem you are trying to solve, we might be able to help.

**Comment by stanislavlevin** [comment] 2017-11-08 06:49
Hello, @obestwalter.

I'm packing tox python module to rpm package.
My task is build, install and test tox under chroot environment(without internet connection).

According to your link [http://tox.readthedocs.io/en/latest/example/basic.html#integration-with-setup-py-test-command](http://tox.readthedocs.io/en/latest/example/basic.html#integration-with-setup-py-test-command) i used pytest and pytest-runner

PYTHONPATH is used to pass python2/3 site packages and tox paths.
Without this env. variable almost all tests were failed.
Thank you.

**Comment by obestwalter** [comment] 2017-11-17 13:53
I still don't quite understand why you are trying to run the tests in that way and if I try it , it simply does not work at all:

```
TOX_TESTENV_PASSENV='PYTHONPATH' python setup.py pytest --addopt "--verbose --cov-config=tox.ini --cov=tox --timeout=180 --pdb -k test_pythonpath_usage"
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'pytest'
```

As the tests run fine, if you run them the normal way, I do not understand what the problem is and what we should do about it.

**Comment by obestwalter** [comment] 2018-06-04 16:53
Closing this as we didn'tget any more details to be able to help.

**Closed by obestwalter** 2018-06-04 16:53 UTC
Labels: type:invalid
