### ISSUE TITLE
Support for negative factor conditionals

### ISSUE THREAD

**Issue by jurko-gospodnetic** [tox-dev/tox#688] opened 2017-11-28 22:13 UTC
When playing around with nicely configuring tox for a project I ran into a scenario where I'd like to have a setting for an environment unless its name has some specific factor like `dev`. That would make it simpler to effectively remove a setting for specifically marked environments instead of having to duplicate all the other values for it or have to extract those values into a separate section and then reference them from there explicitly in multiple places.

Here's a simplified scenario:

A project that has a `[dev]` setuptools extra defined that adds a pytest dependency, which you want to use in `dev` environments, but in which case you do not want to add the regular `pytest` dependency to the tox `deps` setting, e.g. to test that the extra definition actually works and is getting used.
```
[tox]
envlist = {py27,py36}

[base]
deps = some-generic-packages

[testenv]
commands = pytest
deps =
    {[base]deps}
    pytest
extras = dev: dev
usedevelop = dev: True

[testenv:py27-dev]
deps = {[base]deps}

[testenv:py36-dev]
deps = {[base]deps}
```
while with negative factor selector support using a `!` prefix it can be rewritten to just:
```
[tox]
envlist = {py27,py36}

[testenv]
commands = pytest
deps =
    some-generic-package
    !dev: pytest
extras = dev: dev
usedevelop = dev: True
```

**Comment by jurko-gospodnetic** [comment] 2017-11-28 22:22
Added pull request https://github.com/jurko-gospodnetic/tox/pull/1 for discussion. Not added to this repo as it's based on still unmerged test cleanup pull request #687, but I'll recreate it here as soon as that one is merged.

**Comment by The-Compiler** [comment] 2017-11-29 06:01
Closing this as duplicate of #292 - really looking forward to that pull request though! 👍

**Closed by The-Compiler** 2017-11-29 06:01 UTC

**Comment by jurko-gospodnetic** [comment] 2017-11-29 08:10
Well the pull request is up, but for now on my tox project fork until #687 gets merged.

**Comment by jurko-gospodnetic** [comment] 2017-12-01 22:23
Pull request #694 on this repo now up and the original one closed.

**Comment by jurko-gospodnetic** [comment] 2017-12-01 22:26
Pull request #694 on this repo now up and the original one closed.
