### ISSUE TITLE
Tox 4 no longer passes environment variables to setup

### ISSUE THREAD

**Issue by ozzy92** [tox-dev/tox#2688] opened 2022-12-12 16:54 UTC
## Issue

I have a package that depends on environment variables in setup.py for a custom build step.  Tox 4 no longer passes any environment variables to the setup.py in the test environment.  setenv/passenv do not work to resolve.

I've attached a quick example similar to the library.

## Environment

Provide at least:

- OS: Ubuntu 20.04.5 LTS
- `pip list` of the host Python where `tox` is installed:

In tar: pip_list.out

## Output of running tox

Provide the output of `tox -rvv`:

in tar: tox.out

## Minimal example

If possible, provide a minimal reproducer for the issue:

attached tar
[tox_test.tar.gz](https://github.com/tox-dev/tox/files/10210234/tox_test.tar.gz)

**Comment by gaborbernat** [comment] 2022-12-12 17:03
Duplicate of https://github.com/tox-dev/tox/issues/2543

**Closed by gaborbernat** 2022-12-12 17:03 UTC
