### ISSUE TITLE
tox 3.23.0 produces logging on stdout breakind use of --showconfig, -l, -a

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/tox#2030] opened 2021-04-15 08:04 UTC
I realised that `tox --showconfig` "API" is broken by the fact that tox does output logging messages to stdout instead of stderr when it recreates the .tox envs.

Here you can see capture of stdout from `tox --showconfig >stdout.out` when run on a fresh clone, clearly invalid ini file. If you run it again it will produce valid content because it will no longer produce stdout output.
```
[1m.tox create: /Users/ssbarnea/c/opendev/tripleo-ci-health-queries/.tox/.tox
[0m[1m.tox installdeps: setuptools >= 41.4.0, pip >= 19.3.0, tox-bindep, tox >= 3.16.1
[0m[tox]
args = ['--showconfig']
distdir = /Users/ssbarnea/c/opendev/tripleo-ci-health-queries/.tox/dist
distshare = /Users/ssbarnea/.tox/distshare
envlist_default = ['py', 'lint', 'error-testing']
hashseed = 2551992764
homedir = /Users/ssbarnea
ignore_basepython_conflict = False
```

Ideally logging should happen only on stderr, at least for commands that are expected to be machine parseable like `-l`, `-a` and `--showconfig`. I am not sure if the other two are affected but this one is for sure.

This is a serious bug for integration with other tools as --showconfig is currently the only reliable way to query tox about its config (looking inside config fix not being one).

When we fix this we should also add a simple test to avoid regressions, still with v4 around the corner I am not sure how easy it would be to port the test for v4.

The irony is that running `tox -q --showconfig` does produce zero stdout output. That , means that printing config uses the logging level when it should not and instead use effective output to stdout, aka print as this is the effective "output of the program" not some logging information.

**Comment by gaborbernat** [comment] 2021-04-15 08:38
I don't think using the reporter is the troublesome part here. the troublesome part is that the provisioning pollutes the output. I don't see an easy solution to this though; so I can only suggest a workaround: call first `tox --help` to perform the provisioning, and then call `tox --showconfig`  this is what I've also been doing in my systems. changing to print doesn't help you because `tox -v --showconfig` might still pollute the output or similarly anything might trigger a warning message to polluting the output. The way things are I'm inclined to mark this won't fix because there's no easy solution here.

**Comment by ssbarnea** [comment] 2021-04-15 09:56
The fact that `tox -q --showconfig` is a non-sense, a side effect of some historical implementation decisions being made. What is the damage of fixing at least some part of these mistakes? What if tools like flake8/... would display nothing when run with less verbose mode? They will be useless.

https://clig.dev/#output is also giving some insights on how output should be treated, especially when it is supposed to be machine parseable.

@gaborbernat How I read you reply on this is that you refuse to allow use of `-q` option as an workaround that would make tox v3 output machine parseable, leaving users without any options to interact with the tool. I personally find `tox --help && tox --showconfig` more of a joke, at it would double runtime, introduce cross platform problems due to the chaining and more importantly, buggy. What if a tox plugin may decide to log something? While I am not aware of one that does that, I am fully aware that they could decide to log something and it would not be their fault if they do (unless they do it via print instead of tox reporter).

In fact this bug also breaks use of `-l` and `-a` too, not only `--showconfig` for the same reasons. The good part is that adding `-qq` does work for those two as they knew not to display the output using the reporter. Sadly, --showconfig missed to do that, and that is what #2031 is supposed to address.

I wonder what is the worry reason for making the behavior consistent between all commands that produce parseable output?

**Comment by obestwalter** [comment] 2021-04-15 15:41
I would also like if this could be solved in a clean(er) way. I volunteer to have a look and see if I can help resolving this in a satisfactory way.

**Comment by obestwalter** [comment] 2021-04-15 16:17
i can't look into any details yet, but just to give some quick feedback:

> In fact this bug also breaks use of -l and -a too, not only --showconfig for the same reasons. The good part is that adding -qq does work for those two as they knew not to display the output using the reporter. Sadly, --showconfig missed to do that, and that is what #2031 is supposed to address.

If there is nothing in the way, then making `-qq` work the same and documenting it as a necessary switch when doing any kind of parsing seems like a good solution to fix the problem at hand and to make it consistent.

> What if a tox plugin may decide to log something?

Currently the "correct" way to log from a plugin is to use `tox.session.reporter`, I guess? Like here: https://github.com/obestwalter/tox-direct/blob/8054e6498570f7c99d13ca2935d673a5138d3732/src/tox_direct/hookimpls.py#L100-L102

But in general, I agree: log output should always go to stderr, but there seem to be some complicating factors involved here, but I am not quite grasping them yet either.

**Comment by obestwalter** [comment] 2021-04-16 16:11
I can't even reproduce this. When does this exactly happen? Whatever I do: I just get the config and no provisioning output before. I deleted `.tox` and still no provisioning happens, when I only call `tox --showconfig`. Can you please link to a repo where that happens?

**Comment by ssbarnea** [comment] 2021-04-16 16:22
@obestwalter It does not happen in all cases, maily it happens when tox decides that the current version does not fit the `requires` or `minversion` and creates the bootstrapping venv with tox in it. If you install an older version of tox than the one needed it should happen.

That is not so much related to the repository itself but more about which version of tox you are calling.

**Comment by obestwalter** [comment] 2021-04-16 19:37
Ah ok, I get it ... those are all features that I am not using, that's why I never have seen that. I am a very boring tox user :D

**Comment by gaborbernat** [comment] 2022-01-13 08:51
Seems we could not determine a path ahead, so closing this for now.

**Closed by gaborbernat** 2022-01-13 08:51 UTC
Labels: bug:normal
