### ISSUE TITLE
py35, usedevelop setup hangs

### ISSUE THREAD

**Issue by scop** [tox-dev/tox#2836] opened 2023-01-08 07:50 UTC
## Issue

py35 setup with usedevelop fails with "incorrect request to backend", hangs.

## Environment

Provide at least:

- OS: Linux
- `pip list` of the host Python where `tox` is installed:

```console
$ pip list
Package       Version
------------- -------
cachetools    5.2.0
chardet       5.1.0
colorama      0.4.6
distlib       0.3.6
filelock      3.9.0
packaging     22.0
pip           22.3.1
platformdirs  2.6.2
pluggy        1.0.0
pyproject_api 1.4.0
setuptools    65.5.0
tox           4.2.6
virtualenv    20.17.1
```

## Output of running tox

Provide the output of `tox -rvv`:

```console
# see below
```

## Minimal example

If possible, provide a minimal reproducer for the issue:

```console
$ mkdir /tmp/new-empty-dir
$ cd /tmp/new-empty-dir
$ tox run -rvv --develop -e py35
[...]
.pkg-cpython35: 455 W install_requires> python -I -m pip install 'setuptools>=40.8.0' wheel [tox/tox_env/api.py:427]
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
Requirement already satisfied: setuptools>=40.8.0 in ./.tox/.pkg-cpython35/lib/python3.5/site-packages (50.3.2)
Requirement already satisfied: wheel in ./.tox/.pkg-cpython35/lib/python3.5/site-packages (0.37.1)
.pkg-cpython35: 1358 I exit 0 (0.90 seconds) /tmp/new-empty-dir> python -I -m pip install 'setuptools>=40.8.0' wheel pid=1750750 [tox/execute/api.py:275]
.pkg-cpython35: 1359 W _optional_hooks> python [...]/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__ [tox/tox_env/api.py:427]
Backend: incorrect request to backend: bytearray(b'{"cmd": "_optional_hooks", "kwargs": {}, "result": "/tmp/pep517__optional_hooks-rag91x47.json"}')
# hangs here
```

**Comment by gaborbernat** [comment] 2023-01-09 15:43
Can you please provide a reproducible for this, I can't reproduce myself. Note also Python 3.5 is long time EOLd. Ideally, a docker image, python 3.5 is very much unsupported, but if you put in a PR to fix it, I'll accept. As such, I am closing this issue.

**Closed by gaborbernat** 2023-01-09 15:43 UTC

**Comment by scop** [comment] 2023-01-09 19:42
The minimal example reproduces for me reliably. `python3.5` needs to be in `$PATH`.

If Python 3.5 is completely unsupported, I suggest rephrasing https://tox.wiki/en/latest/user_guide.html#main-features which currently says
> cross-Python compatible: tox requires CPython 3.7 and higher, but it can create environments 2.7 or later

Note that in the minimal reproducer above, tox itself is running with Python 3.11.1, creating an env for 3.5.

**Comment by scop** [comment] 2023-01-09 19:49
Re/aside/FWIW 3.5 EOLd, sure, by python.org. However for example Ubuntu 14.04 is in "Extended Security Maintenance (ESM)" until 2024-04, and ships with 3.5 (and even 3.4). https://ubuntu.com/about/release-cycle

**Comment by gaborbernat** [comment] 2023-01-09 19:58
> Re/aside/FWIW 3.5 EOLd, sure, by python.org. However for example Ubuntu 14.04 is in "Extended Security Maintenance (ESM)" until 2024-04, and ships with 3.5 (and even 3.4). [ubuntu.com/about/release-cycle](https://ubuntu.com/about/release-cycle)

As such support is provided by Ubuntu, not us 😊 If Ubuntu promises support, they should actually do it 😆

**Comment by scop** [comment] 2023-01-09 20:21
Ok, opened #2845 for updating the user guide info on supported Python (env) versions.
