### ISSUE TITLE
Ability to share tox environments within a project

### ISSUE THREAD

**Issue by Apteryks** [tox-dev/tox#425] opened 2016-12-14 02:20 UTC
Reproducing Steps
------------------------

1. Save the following configuration in a "tox.ini" somewhere. Note that the "envdir" is commented out for now.
```
[tox]
skipsdist = True
envlist = py27,pylint

[testenv]
deps =
    pytest
    pylint
commands =
    pytest --version

[testenv:pylint]
#envdir = {toxworkdir}/py27
commands = pylint --version
```
2. In the same directory of this newly created tox.ini file, execute tox twice (`tox`). The output should look like that:

**py27 installed**: astroid==1.4.8,backports.functools-lru-cache==1.3,configparser==3.5.0,isort==4.2.5,lazy-object-proxy==1.2.2,mccabe==0.5.2,py==1.4.31,pylint==1.6.4,pytest==3.0.5,six==1.10.0,wrapt==1.10.8
py27 runtests: PYTHONHASHSEED='2007619177'
py27 runtests: commands[0] | pytest --version
This is pytest version 3.0.5, imported from /home/mcournoyer/workspace/test_proj/.tox/py27/lib/python2.7/site-packages/pytest.pyc
**pylint installed**: astroid==1.4.8,backports.functools-lru-cache==1.3,configparser==3.5.0,isort==4.2.5,lazy-object-proxy==1.2.2,mccabe==0.5.2,py==1.4.31,pylint==1.6.4,pytest==3.0.5,six==1.10.0,wrapt==1.10.8
pylint runtests: PYTHONHASHSEED='2007619177'
pylint runtests: commands[0] | pylint --version
No config file found, using default configuration
pylint 1.6.4, 
astroid 1.4.8
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4]
_____________________________________________________ summary ______________________________________________________
  py27: commands succeeded
  pylint: commands succeeded
  congratulations :)

real	**0m2.066s**
user	0m1.804s
sys	0m0.224s

3. Now uncomment the line "#envdir = {toxworkdir}/py27" in the tox.ini file and save it, and rerun `tox` twice. The output should now look like:

**py27 recreate**: /home/mcournoyer/workspace/test_proj/.tox/py27
py27 installdeps: pytest, pylint
py27 installed: astroid==1.4.8,backports.functools-lru-cache==1.3,configparser==3.5.0,isort==4.2.5,lazy-object-proxy==1.2.2,mccabe==0.5.2,py==1.4.31,pylint==1.6.4,pytest==3.0.5,six==1.10.0,wrapt==1.10.8
py27 runtests: PYTHONHASHSEED='809406144'
py27 runtests: commands[0] | pytest --version
This is pytest version 3.0.5, imported from /home/mcournoyer/workspace/test_proj/.tox/py27/lib/python2.7/site-packages/pytest.pyc
**pylint recreate**: /home/mcournoyer/workspace/test_proj/.tox/py27
pylint installdeps: pytest, pylint
pylint installed: astroid==1.4.8,backports.functools-lru-cache==1.3,configparser==3.5.0,isort==4.2.5,lazy-object-proxy==1.2.2,mccabe==0.5.2,py==1.4.31,pylint==1.6.4,pytest==3.0.5,six==1.10.0,wrapt==1.10.8
pylint runtests: PYTHONHASHSEED='809406144'
pylint runtests: commands[0] | pylint --version
No config file found, using default configuration
pylint 1.6.4, 
astroid 1.4.8
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4]
_____________________________________________________ summary ______________________________________________________
  py27: commands succeeded
  pylint: commands succeeded
  congratulations :)

real	**0m11.402s**
user	0m9.856s
sys	0m1.440s

4. Observe that, when reusing the same envdir, the environment always gets recreated (and takes more time to do so) even though the two targets (pytest & pylint) share the exact same requirements. 

System Information
-------------------------
OS: Ubuntu 14.04
tox version: 2.5.0
Python version: 2.7.12
pip list: Too many to list here (can provide upon request).

**Comment by obestwalter** [comment] 2016-12-15 23:24
Thanks for the detailed report @Apteryks.

**Comment by Apteryks** [comment] 2016-12-16 06:11
No problem! And thanks for the great software!

**Comment by speedyleion** [comment] 2017-01-18 05:51
I was able to reproduce this on windows with version 2.5.0

I've traced it to this function in config.py
```
 def basepython_default(testenv_config, value):
        if value is None:
            for f in testenv_config.factors:
                if f in default_factors:
                    return default_factors[f]
            return sys.executable
        return str(value)
```

It looks like `py27` is a default factor so it grabs the `basepython` from the `default_factors` dictionary, this happens to be `python2.7`.
`pylint` is not a default factor and thus uses `sys.executable`.  This makes the two environments differ so that each one is being recreated.

You can work around this by setting `basepython` in the pylint environment to `python2.7`
```
[testenv:pylint]
basepython=python2.7
envdir = {toxworkdir}/py27
commands = pylint --version
```

**Comment by speedyleion** [comment] 2017-01-19 04:09
@Apteryks if you do discover that the issue can be resolved by specifying `basepython`, I think that may be by design:
- http://tox.readthedocs.io/en/latest/config.html#confval-basepython=NAME-OR-PATH says that the default is the interpreter used for tox invocation, `sys.executable` in my example above.
- http://tox.readthedocs.io/en/latest/example/basic.html#a-simple-tox-ini-default-environments though it takes some interpretation it mentions that the `default` environments will use the appropriate python interpreters.

It would seem `pylint` is doing what is expected it's not a default so it uses `sys.executable`.  `py27` is a default so it finds the systems `python2.7` executable.  
Again this is only if the `basepython` fixes the problem you were seeing.

**Comment by obestwalter** [comment] 2017-03-10 17:51
@speedyleion thanks for digging into this. I agree that this is a side effect of sharing between a default environment and a non-default environemnt. It is obviuous if you share environments that use different interpreters. What is surprising to me is, that the recreation also happens when sharing the same interpreter unless you set `basepython` as you decribed. 

To summarize (If your tox with Python 3.6 the following happens

With `tox.ini`:

    [tox]
    envlist = py36,nonstandard
    [testenv]
    envdir = {toxworkdir}/sharedenvdir
    commands = python --version

=> against expectation: constant recreation although interpreter is the same for both environments.

With `tox.ini`:

    [tox]
    envlist = nonstandard1,nonstandard2
    [testenv]
    envdir = {toxworkdir}/sharedenvdir
    commands = python --version

=> as expected: environment is reused

With `tox.ini`:

    [tox]
    envlist = py36,nonstandard
    [testenv]
    basepython=python3.6
    envdir = {toxworkdir}/sharedenvdir
    commands = python --version

=> as expected: environment is reused

I guess this is an unintended side effect of the default environments. @hpk42 - what do you think?

BTW: To weird things up one can do:

    [tox]
    envlist = py36,py27
    [testenv]
    basepython=python3.6
    envdir = {toxworkdir}/sharedenvdir
    commands = python --version

... which leads to the py27 environment also be run with python3.6 which is very likely not intended by the user and a mistake in the configuration. This might lead to unnecessary confusion and I wonder if we should catch that and throw an appropriate error, when we encounter configurations like that?

**Comment by Apteryks** [comment] 2017-03-12 03:32
@speedyleion, obestwalter: Thanks for looking into this. I can confirm that the environments stop being recreated when I set basepython to python2.7 either in the non-standard environment section [testenv:pylint] or in the shared base environment [testenv].

So I'm grateful I could make it work, but I'm wondering what could be made to make this situation less confusing. Maybe the information that is used to "identify" an interpreter could be taken from its '--version' output rather than its path? It would still be a weak verification, but it would at least allow sharing the envdirs between standard and non-standard environment without this setting this not-so-intuitive basepython, provided the sys.executable and the python2.7/python3.6, etc '--version' output match.

**Comment by obestwalter** [comment] 2017-03-12 12:32
If you want to look into that a bit more in detail - a PR fixing that will likely be merged, as this is definitely not desirable behaviour. The default environments seem to be a bit special though and I have not looked into their implications in detail though, so there might be some surprises waiting ... it might as well just be though that this is just a case that hasn't been considered in the original implication and is fairly easy to fix in the way that you propose.

BTW My last example should definitely throw an error as I can't imagine any sane use case for that, or am I missing something? I think that is another issue though, so I will open one for that.

**Comment by wolfch-elsevier** [comment] 2021-03-17 17:56
I have:
```
[tox]
envlist = py37,unit_tests
skipsdist = True

[testenv]
basepython = python3.7
passenv = USER

[testenv:unit_tests]
basepython = python3.7
envdir = {toxworkdir}/py37
deps = -r dev-requirements.txt
commands = py.test -s -v tests/unit_test
```
Even though I added `basepython = python3.7` to the `[testenv:unit_tests]` section, it keeps recreating `py37`, so the workaround doesn't work for me.

**Comment by gaborbernat** [comment] 2021-03-17 18:03
Officially we don't allow sharing tox environments at the moment, which is what you're doing by making that config change.

**Comment by wolfch-elsevier** [comment] 2021-03-17 18:10
> Officially we don't allow sharing tox environments at the moment, which is what you're doing by making that config change.

Hi, thanks for the rapid response!

- I was just noting that the workaround described at [issuecomment](https://github.com/tox-dev/tox/issues/425#issuecomment-273390111) didn't work for me.
- So are you suggesting that each tox environment has to have it's own `virtualenv` even if the Python version and dependencies are identical?

**Comment by gaborbernat** [comment] 2021-03-17 18:48
Yes 👍🏻 as of today.

**Comment by gaborbernat** [comment] 2022-01-13 09:17
I've decided that for now we'll not plan to support this. However, tox 4 allows one to do this via a plugin, so we'd encourage people interested in this to try to test a solution to this via that. Once the project is stable and widely used we can revisit accepting it in core.

**Closed by gaborbernat** 2022-01-13 09:17 UTC
Labels: area:configuration, area:testenv-creation, level:hard, help:wanted

**Comment by masenf** [comment] 2023-01-14 23:30
I've published a plugin to support this workflow in tox4 as [tox-ignore-env-name-mismatch](https://github.com/masenf/tox-ignore-env-name-mismatch)

**Comment by gaborbernat** [comment] 2023-01-14 23:36
I personally don't agree with such ignore solution 🤷‍♂️ but you're free to do whatever works best for you in your plugin 😅
