### ISSUE TITLE
tox4: Checking for external commands is not implemented

### ISSUE THREAD

**Issue by hexagonrecursion** [tox-dev/tox#1946] opened 2021-03-02 16:16 UTC
This should complain about an external command not listed in `allowlist_externals`
```ini
[tox]
isolated_build = true
envlist = py3

[testenv]
commands = echo foo
```
but it does not:
```
hello $ tox4
.pkg: install_requires> python -I -m pip install 'setuptools>=40.0.4'
.pkg: get_requires_for_build_wheel> python /path/to/venv/lib/python3.9/site-packages/tox/util/pep517/backend.py True setuptools.build_meta
.pkg: install_requires_for_build_wheel> python -I -m pip install wheel
.pkg: prepare_metadata_for_build_wheel> python /path/to/venv/lib/python3.9/site-packages/tox/util/pep517/backend.py True setuptools.build_meta
.pkg: get_requires_for_build_sdist> python /path/to/venv/lib/python3.9/site-packages/tox/util/pep517/backend.py True setuptools.build_meta
.pkg: build_sdist> python /path/to/venv/lib/python3.9/site-packages/tox/util/pep517/backend.py True setuptools.build_meta
py3: install_package> python -I -m pip install --no-deps --force-reinstall /path/to/hello/.tox/4/.pkg/dist/UNKNOWN-0.0.0.tar.gz
py3: commands[0]> echo foo
foo
.pkg: _exit> python /path/to/venv/lib/python3.9/site-packages/tox/util/pep517/backend.py True setuptools.build_meta
  py3: OK (8.80=setup[8.79]+cmd[0.01] seconds)
  congratulations :) (8.85 seconds)
```
tox3 for comparison:
```
hello tox
.package create: /path/to/hello/.tox/.package
.package installdeps: setuptools >= 40.0.4
py3 create: /path/to/hello/.tox/py3
py3 inst: /path/to/hello/.tox/.tmp/package/1/UNKNOWN-0.0.0.tar.gz
py3 installed: UNKNOWN @ file:///path/to/hello/.tox/.tmp/package/1/UNKNOWN-0.0.0.tar.gz
py3 run-test-pre: PYTHONHASHSEED='3671335986'
py3 run-test: commands[0] | echo foo
WARNING: test command found but not installed in testenv
  cmd: /usr/bin/echo
  env: /path/to/hello/.tox/py3
Maybe you forgot to specify a dependency? See also the allowlist_externals envconfig setting.

DEPRECATION WARNING: this will be an error in tox 4 and above!
foo
_____________________________________________________________ summary ______________________________________________________________
  py3: commands succeeded
  congratulations :)
```

**Comment by gaborbernat** [comment] 2021-03-02 17:03
Duplicate of https://github.com/tox-dev/tox/issues/1127

**Closed by gaborbernat** 2021-03-02 17:03 UTC
Labels: feature:new
