### ISSUE TITLE
Color support on Windows: TerminalWriter (PY_COLORS), colorama (PYCHARM_HOSTED)

### ISSUE THREAD

**Issue by eine** [tox-dev/tox#1468] opened 2019-11-30 06:26 UTC
While running several tests with `tox` on GitHub Actions environments, tox's output is not coloured by default (see actions/starter-workflows#114). Setting `PY_COLORS: 1` (#1009) works for jobs running on GNU/Linux (`ubuntu-latest`). Unfortunately, it seems not to be effective on `windows-latest`.

- `ubuntu-latest`: https://github.com/1138-4EB/vunit/runs/326860648#step:5:29
- `windows-latest`: https://github.com/1138-4EB/vunit/runs/326860617#step:7:31

Note that, in those examples, the output of the commands executed by tox is coloured because `--color=yes` is explicitly passed to `pytest` through `{posargs}`.

**Comment by gaborbernat** [comment] 2019-11-30 15:28
We'd happy to fix this if someone can investigate and come up with a PR for it.

**Comment by 1138-4EB** [comment] 2019-11-30 16:01
I'd be happy to investigate if I have any reference. Currently, `PY_COLORS` seems not to be found in this repository, except in the help: https://github.com/tox-dev/tox/search?q=PY_COLORS&type=Code

**Comment by 1138-4EB** [comment] 2019-11-30 16:40
Here is a minimal reproducer GitHub Actions workflow:

```yml
name: "tox"
on: [push]
jobs:
  tox:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [ ubuntu, windows ]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - uses: actions/checkout@v1
    - run: pip3 install tox --progress-bar off
    - run: tox -e py37-test
    - run: tox -e py37-test
      env:
        PY_COLORS: 1
```

Output: https://github.com/1138-4EB/actions/runs/327196070

**Comment by 1138-4EB** [comment] 2019-12-01 03:20
Upon further investigation, it seems that `tox` does not explicitly handle colouring at all:

https://github.com/tox-dev/tox/blob/9ee972e7be07589c2ac09d5189c44e5943f0b51c/src/tox/reporter.py#L101-L102

https://github.com/tox-dev/tox/blob/9ee972e7be07589c2ac09d5189c44e5943f0b51c/src/tox/reporter.py#L72-L75

https://github.com/tox-dev/tox/blob/9ee972e7be07589c2ac09d5189c44e5943f0b51c/src/tox/reporter.py#L77-L83

https://github.com/tox-dev/tox/blob/9ee972e7be07589c2ac09d5189c44e5943f0b51c/src/tox/reporter.py#L38

Hence, `PY_COLORS` is handled by `py.io.TerminalWriter()`. This is mentioned in #163, but not in the help/docs. I'd suggest to please explain this explicitly (#1009). For example: 

> `tox` depends on [py.io.TerminalWriter](https://github.com/pytest-dev/py/blob/master/py/_io/terminalwriter.py) to handle colouring, which supports forcing the behaviour with environment variable `PY_COLORS`: 0 disable, 1 enable (default).

---

Looking at the source of `TerminalWriter`, the usage of `PY_COLORS` seems straightforward:

https://github.com/pytest-dev/py/blob/1e99d20f31ef511fc2f1a9e49ba970acad441d4e/py/_io/terminalwriter.py#L131-L138

This issue might be related to the fact that `TerminalWriter` seems to depend on [colorama](https://github.com/tartley/colorama) when on windows:

https://github.com/pytest-dev/py/blob/1e99d20f31ef511fc2f1a9e49ba970acad441d4e/py/_io/terminalwriter.py#L15-L24

Unfortunately, colorama is only used when a tty is available:

https://github.com/pytest-dev/py/blob/1e99d20f31ef511fc2f1a9e49ba970acad441d4e/py/_io/terminalwriter.py#L157-L158

As a result, it might be a bug in `TerminalWriter`, as using colorama might need to be forced when `PY_COLORS` is set (similar to pytest-dev/py#224). Still:

- `TerminalWriter` has not been updated in 7 months and the CI tests are broken. It "*is in maintenance mode and should not be used in new code*". Instead of trying to push a fix, it might be more sensible to copy/fork `terminalwriter.py` only.
- `colorama` itself will not colour the output when a tty is not available. It needs to be forced with `PYCHARM_HOSTED` (tartley/colorama#214). It would make sense if colorama supported `PY_COLORS` too (ping @tartley @wiggin15).

---

An alternative solution to properly honour `PY_COLORS` in both TerminalWriter and colorama, is to have tartley/colorama#226 tested and merged, and then use it in TerminalWriter too.

**Comment by gaborbernat** [comment] 2019-12-02 12:27
Closed via https://github.com/tox-dev/tox/pull/1471

**Comment by 1138-4EB** [comment] 2019-12-02 13:05
@gaborbernat, note that this was not closed automatically on purpose. #1471 is just a quick fix and it might seem to work, but I believe that this issue needs to remain open. Let me elaborate:

With the current version of TerminalWriter, ensuring that colorama is installed will avoid `win32_and_ctypes` being used. However, colorama is not actually used unless a tty is available (which is not the case in some CI services, such as GHA):

https://github.com/pytest-dev/py/blob/1e99d20f31ef511fc2f1a9e49ba970acad441d4e/py/_io/terminalwriter.py#L157-L158

Hence, the current `master` of `tox` generates Linux type coloring on Windows when no TTY is used. I guess that this might work on web frontend, on bash (MSYS2/MINGW) and probably on powershell; but it is likely to be broken on cmd.

[This](https://github.com/1138-4EB/tox/commits/fix-win-color) is an effort to bring TerminalWriter to tox's codebase and clean it up so that `colorama` is always used on Windows. Unfortunately, in this context `PY_COLORS=1` alone is uneffective, because not being a tty colorama requires `PYCHARM_HOSTED=1` to be set too. I tried to make tox set it automatically, but it seems not to work.

Hence, as commented above, I think that it would make sense if colorama supported `PY_COLORS`; or if TerminalWriter supported `FORCE_COLOR` and `NOCOLOR` (tartley/colorama#230). Any of those would allow a single envvar to be used while ensuring that colorama is allowed to handle any terminal on windows.

Anyway, I later found #1400. It seems that `py` is removed completely and colorama is directly used instead. I think that's a great decission and I'm looking to having it released. Nonetheless, I believe that this issue should remain open until it is merged or until any other of the solutions is applied.

**Comment by gaborbernat** [comment] 2020-04-19 08:56
My available efforts at the moment are aimed at fixing this as part of https://github.com/tox-dev/tox/issues/1394, but that probably will take a while (ETA September).

**Comment by gaborbernat** [comment] 2022-01-13 10:37
I think this has been fixed on version 4 by using the colorama package.

**Closed by gaborbernat** 2022-01-13 10:37 UTC
Labels: feature:new, help:wanted
