### ISSUE TITLE
Extract dependencies from setup.py

### ISSUE THREAD

**Issue by gaborbernat** [tox-dev/tox#496] opened 2017-03-27 12:55 UTC
So now one has the option to add ``requirements.txt`` via the -r option. However, for the package there already exists a ``setup.py`` that  contains the dependencies. It would be nice to not need to have maintain dependencies in two files and instead load them directly from the requirements.txt via '-ssetup.py'. What do you guys think?

**Comment by RonnyPfannschmidt** [comment] 2017-03-27 13:05
i beleive this is a duplicate of #13

**Comment by The-Compiler** [comment] 2017-03-27 13:07
I don't understand - tox already install requirements listed in your `setup.py` when installing your package, no? Also [setup.py vs requirements.txt](https://caremad.io/posts/2013/07/setup-vs-requirement/) might be worth a read :wink:

**Comment by RonnyPfannschmidt** [comment] 2017-03-27 13:09
@The-Compiler the requirement extraction happens at package install time, not package test time
and its done by pip, not by tox

it could help a lot to extract test_requires/extra_requires and reuse them

**Comment by obestwalter** [comment] 2017-03-27 13:11
This is really a dupe, so let's take the discussion there. Closing.

**Closed by obestwalter** 2017-03-27 13:11 UTC

**Comment by gaborbernat** [comment] 2017-03-28 18:02
@obestwalter  @RonnyPfannschmidt  you're correct, my pain is that after initial env creation stuff updated in setup.py does not trigger a reinstall (only if you change stuff in deps), but that's another issue.
