### ISSUE TITLE
3.24.1: `pytest` is failing because `tox` has hardcoded python executable name

### ISSUE THREAD

**Issue by kloczek** [tox-dev/tox#2160] opened 2021-08-17 08:26 UTC
Just found that a lot of test units is failing because I have no `python` executable name in $PATH.
After add symlink `ln -s python3 /usr/bin/python` only one unit failed (still need to find out why but that is another part)
Looks like in at least one places executable name is hardcoded:
```console
[tkloczko@barrel tox-3.24.1]$ grep -r 'self.getcommandpath("python")'
src/tox/venv.py:            command_path = self.getcommandpath("python")
```
I think that instead `self.getcommandpath("python")` should be used `sys.executable` (or something simillar)

Summary pytest output with `/usr/bin/python`
```console
============================================================================= warnings summary =============================================================================
tests/unit/test_z_cmdline.py::test_notest
  /home/tkloczko/rpmbuild/BUILDROOT/python-tox-3.24.1-2.fc35.x86_64/usr/lib/python3.8/site-packages/tox/config/__init__.py:670: UserWarning: conflicting basepython version (set 3.8, should be 2.6) for env 'py26';resolve conflict or set ignore_basepython_conflict
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================================= short test summary info ==========================================================================
SKIPPED [1] tests/unit/interpreters/windows/test_pep514.py:10: non posix test
SKIPPED [1] tests/unit/interpreters/windows/test_windows.py:4: non posix test
SKIPPED [1] tests/unit/interpreters/windows/test_pep514.py:17: non posix test
SKIPPED [1] tests/integration/test_jython_env_create.py:5: needs jython and dev cut of virtualenv
SKIPPED [1] tests/unit/test_z_cmdline.py:776: Platform doesnt support alwayscopy
ERROR tests/unit/test_quickstart.py - IndexError: tuple index out of range
ERROR tests/unit/test_quickstart.py - IndexError: tuple index out of range
ERROR tests/unit/test_quickstart.py - IndexError: tuple index out of range
ERROR tests/unit/test_quickstart.py - IndexError: tuple index out of range
ERROR tests/unit/test_quickstart.py - IndexError: tuple index out of range
ERROR tests/unit/test_quickstart.py - IndexError: tuple index out of range
ERROR tests/unit/test_quickstart.py - IndexError: tuple index out of range
ERROR tests/unit/test_quickstart.py - IndexError: tuple index out of range
ERROR tests/unit/test_quickstart.py - IndexError: tuple index out of range
ERROR tests/unit/test_quickstart.py - IndexError: tuple index out of range
ERROR tests/unit/test_quickstart.py - IndexError: tuple index out of range
ERROR tests/unit/test_quickstart.py - IndexError: tuple index out of range
FAILED tests/integration/test_provision_int.py::test_provision_interrupt_child[Signals.SIGTERM] - AssertionError: 0:00:00.191296 using tox.ini: /tmp/pytest-of-tkloczko/p...
================================================ 1 failed, 611 passed, 5 skipped, 1 warning, 12 errors in 60.28s (0:01:00) =================================================
pytest-xprocess reminder::Be sure to terminate the started process by running 'pytest --xkill' if you have not explicitly done so in your fixture with 'xprocess.getinfo(<process_name>).terminate()'.
/usr/lib/python3.8/site-packages/_pytest/pathlib.py:80: PytestWarning: (rm_rf) error removing /tmp/pytest-of-tkloczko/garbage-40fdd6cd-5f51-4fec-9d11-3e195a79f959/test_safe_get_no_perms0
<class 'OSError'>: [Errno 39] Directory not empty: 'test_safe_get_no_perms0'
  warnings.warn(
/usr/lib/python3.8/site-packages/_pytest/pathlib.py:80: PytestWarning: (rm_rf) error removing /tmp/pytest-of-tkloczko/garbage-40fdd6cd-5f51-4fec-9d11-3e195a79f959/test_safe_delete_no_perms0
<class 'OSError'>: [Errno 39] Directory not empty: 'test_safe_delete_no_perms0'
  warnings.warn(
/usr/lib/python3.8/site-packages/_pytest/pathlib.py:80: PytestWarning: (rm_rf) error removing /tmp/pytest-of-tkloczko/garbage-40fdd6cd-5f51-4fec-9d11-3e195a79f959/test_safe_set_no_perms0
<class 'OSError'>: [Errno 39] Directory not empty: 'test_safe_set_no_perms0'
  warnings.warn(
/usr/lib/python3.8/site-packages/_pytest/pathlib.py:80: PytestWarning: (rm_rf) error removing /tmp/pytest-of-tkloczko/garbage-40fdd6cd-5f51-4fec-9d11-3e195a79f959/test_rmtree_errorhandler_rerai0
<class 'OSError'>: [Errno 39] Directory not empty: 'test_rmtree_errorhandler_rerai0'
  warnings.warn(
/usr/lib/python3.8/site-packages/_pytest/pathlib.py:80: PytestWarning: (rm_rf) error removing /tmp/pytest-of-tkloczko/garbage-40fdd6cd-5f51-4fec-9d11-3e195a79f959/test_rmtree_errorhandler_reado0
<class 'OSError'>: [Errno 39] Directory not empty: 'test_rmtree_errorhandler_reado0'
  warnings.warn(
/usr/lib/python3.8/site-packages/_pytest/pathlib.py:80: PytestWarning: (rm_rf) error removing /tmp/pytest-of-tkloczko/garbage-40fdd6cd-5f51-4fec-9d11-3e195a79f959
<class 'OSError'>: [Errno 39] Directory not empty: '/tmp/pytest-of-tkloczko/garbage-40fdd6cd-5f51-4fec-9d11-3e195a79f959'
  warnings.warn(
```
and the same without `/usr/bin/python`
```console
========================================================================= short test summary info ==========================================================================
SKIPPED [1] tests/unit/test_z_cmdline.py:776: Platform doesnt support alwayscopy
SKIPPED [1] tests/unit/interpreters/windows/test_windows.py:4: non posix test
SKIPPED [1] tests/integration/test_jython_env_create.py:5: needs jython and dev cut of virtualenv
SKIPPED [1] tests/unit/interpreters/windows/test_pep514.py:10: non posix test
SKIPPED [1] tests/unit/interpreters/windows/test_pep514.py:17: non posix test
ERROR tests/unit/test_quickstart.py - IndexError: tuple index out of range
ERROR tests/unit/test_quickstart.py - IndexError: tuple index out of range
ERROR tests/unit/test_quickstart.py - IndexError: tuple index out of range
ERROR tests/unit/test_quickstart.py - IndexError: tuple index out of range
ERROR tests/unit/test_quickstart.py - IndexError: tuple index out of range
ERROR tests/unit/test_quickstart.py - IndexError: tuple index out of range
ERROR tests/unit/test_quickstart.py - IndexError: tuple index out of range
ERROR tests/unit/test_quickstart.py - IndexError: tuple index out of range
ERROR tests/unit/test_quickstart.py - IndexError: tuple index out of range
ERROR tests/unit/test_quickstart.py - IndexError: tuple index out of range
ERROR tests/unit/test_quickstart.py - IndexError: tuple index out of range
ERROR tests/unit/test_quickstart.py - IndexError: tuple index out of range
ERROR tests/unit/package/test_package_parallel.py::test_tox_parallel_build_safe - Failed: test changed environ extra {'TOX_WORK_DIR': '/tmp/pytest-of-tkloczko/pytest-32/...
FAILED tests/unit/session/test_session.py::test_command_prev_fail_command_skip_post_run - assert '============...ith code 2)\n' == '\npy run-tes...ands failed\n'
FAILED tests/unit/test_venv.py::TestVenvTest::test_pythonpath_keep - tox.exception.InvocationError: InvocationError for command could not find executable python
FAILED tests/unit/test_venv.py::test_install_python3 - tox.exception.InvocationError: InvocationError for command could not find executable python
FAILED tests/unit/test_venv.py::test_installpkg_upgrade - assert 0 == 1
FAILED tests/unit/test_venv.py::test_install_deps_indexserver - tox.exception.InvocationError: InvocationError for command could not find executable python
FAILED tests/unit/test_venv.py::test_install_command_verbosity[5-3] - assert 0 == 1
FAILED tests/unit/test_venv.py::test_installpkg_no_upgrade - assert 0 == 1
FAILED tests/unit/test_venv.py::test_install_command_verbosity[0-0] - assert 0 == 1
FAILED tests/unit/test_venv.py::test_develop_extras - tox.exception.InvocationError: InvocationError for command could not find executable python
FAILED tests/unit/test_venv.py::test_env_variables_added_to_pcall - assert 0 == 2
FAILED tests/unit/test_venv.py::TestVenvTest::test_pythonpath_empty - tox.exception.InvocationError: InvocationError for command could not find executable python
FAILED tests/unit/package/test_package_parallel.py::test_tox_parallel_build_safe - AssertionError:
FAILED tests/unit/package/test_package.py::test_install_via_installpkg - AssertionError: 1
FAILED tests/unit/test_venv.py::test_run_install_command - tox.exception.InvocationError: InvocationError for command could not find executable python
FAILED tests/unit/session/test_provision.py::test_provision_cli_args_ignore - AssertionError: 2
FAILED tests/unit/test_venv.py::test_installpkg_indexserver - assert 0 == 1
FAILED tests/unit/test_venv.py::test_install_command_verbosity[6-3] - assert 0 == 1
FAILED tests/integration/test_provision_int.py::test_provision_interrupt_child[Signals.SIGTERM] - AssertionError: None
FAILED tests/unit/session/test_session.py::test_command_prev_post_ok - AssertionError: 1
FAILED tests/integration/test_parallel_interrupt.py::test_parallel_interrupt - AssertionError: None
FAILED tests/unit/test_venv.py::TestVenvTest::test_pythonpath_remove - tox.exception.InvocationError: InvocationError for command could not find executable python
FAILED tests/unit/test_venv.py::test_install_deps_wildcard - tox.exception.InvocationError: InvocationError for command could not find executable python
FAILED tests/unit/test_venv.py::test_install_deps_pre - tox.exception.InvocationError: InvocationError for command could not find executable python
FAILED tests/unit/test_venv.py::test_install_sdist_extras - tox.exception.InvocationError: InvocationError for command could not find executable python
FAILED tests/unit/test_venv.py::test_install_command_verbosity[3-1] - assert 0 == 1
FAILED tests/unit/test_venv.py::test_install_command_verbosity[2-0] - assert 0 == 1
FAILED tests/unit/test_venv.py::test_install_command_verbosity[4-2] - assert 0 == 1
FAILED tests/unit/test_venv.py::test_install_command_verbosity[1-0] - assert 0 == 1
FAILED tests/integration/test_provision_int.py::test_provision_interrupt_child[Signals.SIGINT] - AssertionError: None
⠼ [1] aERROR: invocation failed (exit code 1), logfile: /tmp/pytest-of-tkloczko/pytest-32/popen-gw9/test_parallel_error_report_Fal0/pkg123/.tox/a/log/a-0.log
FAILED tests/unit/session/test_parallel.py::test_parallel_error_report[True] - AssertionError: a create: /tmp/pytest-of-tkloczko/pytest-32/popen-gw9/test_parallel_error_...
FAILED tests/unit/package/builder/test_package_builder_isolated.py::test_isolated_build_script_args - FileNotFoundError: [Errno 2] No such file or directory: 'python'
FAILED tests/unit/package/builder/test_package_builder_isolated.py::test_verbose_isolated_build - AssertionError: using tox.ini: /tmp/pytest-of-tkloczko/pytest-32/popen-...
FAILED tests/unit/package/builder/test_package_builder_isolated.py::test_dist_exists_version_change - AssertionError: 2
FAILED tests/unit/session/test_parallel.py::test_parallel_show_output - AssertionError: 1
FAILED tests/unit/package/builder/test_package_builder_isolated.py::test_verbose_isolated_build_in_tree - AssertionError: using tox.ini: /tmp/pytest-of-tkloczko/pytest-3...
===================================================== 36 failed, 576 passed, 5 skipped, 1 warning, 13 errors in 56.38s =====================================================
pytest-xprocess reminder::Be sure to terminate the started process by running 'pytest --xkill' if you have not explicitly done so in your fixture with 'xprocess.getinfo(<process_name>).terminate()'.
/usr/lib/python3.8/site-packages/_pytest/pathlib.py:80: PytestWarning: (rm_rf) error removing /tmp/pytest-of-tkloczko/garbage-9b00bd52-8851-4351-9fd9-deafd4f2fb3c/test_safe_get_no_perms0
<class 'OSError'>: [Errno 39] Directory not empty: 'test_safe_get_no_perms0'
  warnings.warn(
/usr/lib/python3.8/site-packages/_pytest/pathlib.py:80: PytestWarning: (rm_rf) error removing /tmp/pytest-of-tkloczko/garbage-9b00bd52-8851-4351-9fd9-deafd4f2fb3c/test_safe_delete_no_perms0
<class 'OSError'>: [Errno 39] Directory not empty: 'test_safe_delete_no_perms0'
  warnings.warn(
/usr/lib/python3.8/site-packages/_pytest/pathlib.py:80: PytestWarning: (rm_rf) error removing /tmp/pytest-of-tkloczko/garbage-9b00bd52-8851-4351-9fd9-deafd4f2fb3c/test_safe_set_no_perms0
<class 'OSError'>: [Errno 39] Directory not empty: 'test_safe_set_no_perms0'
  warnings.warn(
/usr/lib/python3.8/site-packages/_pytest/pathlib.py:80: PytestWarning: (rm_rf) error removing /tmp/pytest-of-tkloczko/garbage-9b00bd52-8851-4351-9fd9-deafd4f2fb3c/test_rmtree_errorhandler_rerai0
<class 'OSError'>: [Errno 39] Directory not empty: 'test_rmtree_errorhandler_rerai0'
  warnings.warn(
/usr/lib/python3.8/site-packages/_pytest/pathlib.py:80: PytestWarning: (rm_rf) error removing /tmp/pytest-of-tkloczko/garbage-9b00bd52-8851-4351-9fd9-deafd4f2fb3c/test_rmtree_errorhandler_reado0
<class 'OSError'>: [Errno 39] Directory not empty: 'test_rmtree_errorhandler_reado0'
  warnings.warn(
/usr/lib/python3.8/site-packages/_pytest/pathlib.py:80: PytestWarning: (rm_rf) error removing /tmp/pytest-of-tkloczko/garbage-9b00bd52-8851-4351-9fd9-deafd4f2fb3c
<class 'OSError'>: [Errno 39] Directory not empty: '/tmp/pytest-of-tkloczko/garbage-9b00bd52-8851-4351-9fd9-deafd4f2fb3c'
  warnings.warn(
```

**Comment by gaborbernat** [comment] 2021-08-17 08:30
This is by design, the test suite is expected to run in a virtual environment. 

> I think that instead `self.getcommandpath("python")` should be used `sys.executable`

That would mean something totally different. Perhaps one could approximate what we want by using the basename of `sys.executable`. PRs are welcome. I'll leave this issue open for a week in case you follow it up with a PR. Otherwise will close as the use case is toofringe.

**Comment by kloczek** [comment] 2021-08-17 08:50
> This is by design, the test suite is expected to run in a virtual environment.

So venv setup is probably wrong and `pythin` symlink 
> > I think that instead `self.getcommandpath("python")` should be used `sys.executable`
> 
> That would mean something totally different. Perhaps one could approximate what we want by using the basename of `sys.executable`. PRs are welcome. I'll leave this issue open for a week in case you follow it up with a PR. Otherwise will close as the use case is too fringe.

It is to early to make PR :)
For now I found that patch
```patch
--- a/src/tox/venv.py~  2021-07-31 13:10:14.000000000 +0100
+++ b/src/tox/venv.py   2021-08-17 09:29:17.513040972 +0100
@@ -650,7 +650,7 @@
                 else:
                     reporter.error(str_status)
                 return False
-            command_path = self.getcommandpath("python")
+            command_path = sys.executable
             envlog.set_python_info(command_path)
             return True
```
does not affect results of the test suite :/
However other grep shows where potentially someting may be wrong.
```
[tkloczko@barrel tox-3.24.1]$ grep -r \"python\"
docs/example/result.rst:          "python": {
src/tox/_pytestplugin.py:        assert name == "python"
src/tox/_pytestplugin.py:            cmd = ["python", "-c", "print({!r})".format(cmd)]
src/tox/config/__init__.py:                base_exe = {"py": "python"}.get(match.group(1), match.group(1))
src/tox/config/__init__.py:            name = "python"
src/tox/config/__init__.py:        known_factors.update({"py", "python"})
src/tox/config/__init__.py:            all_envs["python"] = None
src/tox/interpreters/py_spec.py:    "pypy" if tox.constants.INFO.IS_PYPY else "python",
src/tox/interpreters/via_path.py:                    "pypy" if info["implementation"] == "PyPy" else "python",
src/tox/interpreters/windows/__init__.py:        if spec.name == "python":
src/tox/interpreters/windows/pep514.py:        name = "python" if company == "PythonCore" else company
src/tox/logs/env.py:        self.dict["python"] = answer
src/tox/venv.py:            command_path = self.getcommandpath("python")
tests/unit/config/test_config.py:        assert expected_deps == [str(x) for x in config.envconfigs["python"].deps]
tests/unit/config/test_config.py:        assert [str(x) for x in config.envconfigs["python"].deps] == expected_deps
tests/unit/config/test_config.py:        assert [str(x) for x in config.envconfigs["python"].deps] == expected_deps
tests/unit/config/test_config.py:            "python",
tests/unit/config/test_config.py:            "python",
tests/unit/config/test_config.py:            "python",
tests/unit/config/test_config.py:            "python",
tests/unit/config/test_config.py:        envconfig = config.envconfigs["python"]
tests/unit/config/test_config.py:        envconfig = config.envconfigs["python"]
tests/unit/config/test_config.py:        envconfig = config.envconfigs["python"]
tests/unit/config/test_config.py:        envconfig = config.envconfigs["python"]
tests/unit/config/test_config.py:        assert envconfig.commands[0] == ["python", "-c", "x ; y"]
tests/unit/config/test_config.py:        envconfig = config.envconfigs["python"]
tests/unit/config/test_config.py:        envconfig = config.envconfigs["python"]
tests/unit/config/test_config.py:        assert not config.envconfigs["python"].usedevelop
tests/unit/config/test_config.py:        envconfig = config.envconfigs["python"]
tests/unit/config/test_config.py:        envconfig = config.envconfigs["python"]
tests/unit/config/test_config.py:        envconfig = config.envconfigs["python"]
tests/unit/config/test_config.py:        assert envconfig.envpython == envconfig.envbindir.join("python")
tests/unit/config/test_config.py:        envconfig = config.envconfigs["python"]
tests/unit/config/test_config.py:        envconfig = config.envconfigs["python"]
tests/unit/config/test_config.py:        assert envconfig.envpython == envconfig.envbindir.join("python")
tests/unit/config/test_config.py:        envconfig = config.envconfigs["python"]
tests/unit/config/test_config.py:        envconfig = config.envconfigs["python"]
tests/unit/config/test_config.py:        env = config.envconfigs["python"]
tests/unit/config/test_config.py:        env = config.envconfigs["python"]
tests/unit/config/test_config.py:        env = config.envconfigs["python"]
tests/unit/config/test_config.py:        envconfig = config.envconfigs["python"]
tests/unit/config/test_config.py:        envconfig = config.envconfigs["python"]
tests/unit/config/test_config.py:        envconfig = config.envconfigs["python"]
tests/unit/config/test_config.py:            "python",
tests/unit/config/test_config.py:        envconfig = config.envconfigs["python"]
tests/unit/config/test_config.py:            "python",
tests/unit/config/test_config.py:        envconfig = config.envconfigs["python"]
tests/unit/config/test_config.py:        envconfig = config.envconfigs["python"]
tests/unit/config/test_config.py:        assert conf.commands == [["python", "-c", 'print("Hello, world!")']]
tests/unit/config/test_config.py:        conf = newconfig([""], inisource).envconfigs["python"]
tests/unit/config/test_config.py:        env = conf.envconfigs["python"]
tests/unit/config/test_config.py:        env = conf.envconfigs["python"]
tests/unit/config/test_config.py:        conf = newconfig([], inisource).envconfigs["python"]
tests/unit/config/test_config.py:        assert configs["python"].setenv["VAR"] == r"\{val\}"
tests/unit/config/test_config.py:        assert configs["python"].commands[0] == ["{val}"]
tests/unit/config/test_config.py:        assert config["python"].ignore_outcome is True
tests/unit/config/test_config.py:        return envconfigs["python"]
tests/unit/config/test_config.py:        envconfig = config.envconfigs["python"]
tests/unit/config/test_config.py:        envconfig = config.envconfigs["python"]
tests/unit/config/test_config.py:        envconfig = config.envconfigs["python"]
tests/unit/config/test_config.py:        envconfig = config.envconfigs["python"]
tests/unit/config/test_config.py:        envconfig = config.envconfigs["python"]
tests/unit/config/test_config.py:        envconfig = config.envconfigs["python"]
tests/unit/config/test_config.py:        ).envconfigs["python"]
tests/unit/config/test_config.py:        ).envconfigs["python"]
tests/unit/config/test_config.py:        envconfig = config.envconfigs["python"]
tests/unit/config/test_config.py:        envconfig = config.envconfigs["python"]
tests/unit/config/test_config.py:        assert not config.envconfigs["python"].recreate
tests/unit/config/test_config.py:        assert config.envconfigs["python"].recreate
tests/unit/config/test_config.py:        assert config.envconfigs["python"].recreate
tests/unit/config/test_config.py:        testenv = config.envconfigs["python"]
tests/unit/package/builder/test_package_builder_isolated.py:    subprocess.check_call(("python", script_path, str(tmp_path), "setuptools.build_meta"))
tests/unit/test_result.py:    assert envlog.dict["python"]["version_info"] == list(sys.version_info)
tests/unit/test_result.py:    assert envlog.dict["python"]["version"] == sys.version
tests/unit/test_result.py:    assert envlog.dict["python"]["executable"] == sys.executable
tests/unit/test_venv.py:    venv = mocksession.getvenv("python")
tests/unit/test_venv.py:    assert py.path.local.sysfind("python") == args[0]
tests/unit/test_venv.py:    venv = mocksession.getvenv("python")
tests/unit/test_venv.py:    venv = mocksession.getvenv("python")
tests/unit/test_venv.py:    venv = mocksession.getvenv("python")
tests/unit/test_venv.py:    venv = mocksession.getvenv("python")
tests/unit/test_venv.py:    venv = mocksession.getvenv("python")
tests/unit/test_venv.py:    venv = mocksession.getvenv("python")
tests/unit/test_venv.py:    venv = mocksession.getvenv("python")
tests/unit/test_venv.py:    venv = mocksession.getvenv("python")
tests/unit/test_venv.py:    venv = mocksession.getvenv("python")
tests/unit/test_venv.py:    venv = mocksession.getvenv("python")
tests/unit/test_venv.py:    venv = mocksession.getvenv("python")
tests/unit/test_venv.py:    venv = mocksession.getvenv("python")
tests/unit/test_venv.py:    venv = mocksession.getvenv("python")
tests/unit/test_venv.py:    venv = mocksession.getvenv("python")
tests/unit/test_venv.py:    venv = mocksession.getvenv("python")
tests/unit/test_venv.py:    assert py.path.local.sysfind("python") == args[0]
tests/unit/test_venv.py:        venv = mocksession.getvenv("python")
tests/unit/test_venv.py:        venv = mocksession.getvenv("python")
tests/unit/test_venv.py:        venv = mocksession.getvenv("python")
tests/unit/test_venv.py:        venv = mocksession.getvenv("python")
tests/unit/test_venv.py:        venv = mocksession.getvenv("python")
tests/unit/test_venv.py:        venv = mocksession.getvenv("python")
tests/unit/test_venv.py:        venv = mocksession.getvenv("python")
tests/unit/test_venv.py:        venv = mocksession.getvenv("python")
tests/unit/test_venv.py:        venv = mocksession.getvenv("python")
tests/unit/test_venv.py:        venv = mocksession.getvenv("python")
tests/unit/test_venv.py:        venv = mocksession.getvenv("python")
tests/unit/test_venv.py:        venv = mocksession.getvenv("python")
tests/unit/test_venv.py:    venv = mocksession.getvenv("python")
tests/unit/test_venv.py:    venv = mocksession.getvenv("python")
tests/unit/test_venv.py:    env = mock_session.getvenv("python")
tests/unit/test_venv.py:    venv = mocksession.getvenv("python")
tests/unit/test_venv.py:    venv = mocksession.getvenv("python")
tests/unit/test_venv.py:    assert py.path.local.sysfind("python") == args[0]
tests/unit/test_venv.py:    venv = mocksession.getvenv("python")
tests/unit/test_venv.py:    venv = mocksession.getvenv("python")
tests/unit/test_venv.py:    venv = mocksession.getvenv("python")
tests/unit/test_venv.py:    venv = mocksession.getvenv("python")
tests/unit/test_venv.py:    venv = mocksession.getvenv("python")
tests/unit/test_venv.py:    venv = mocksession.getvenv("python")
tests/unit/test_venv.py:    assert args == ["/usr/bin/env", "python"] + base_args
tests/unit/test_venv.py:    venv = mocksession.getvenv("python")
tests/unit/test_z_cmdline.py:    setup_result_from_json = json.load(report_path)["testenvs"]["python"]["setup"]
tests/unit/test_z_cmdline.py:        pyinfo = env_data["python"]
tests/unit/test_z_cmdline.py:        # do not include "python" as it is changed to python.EXE by appveyor
build/lib/tox/_pytestplugin.py:        assert name == "python"
build/lib/tox/_pytestplugin.py:            cmd = ["python", "-c", "print({!r})".format(cmd)]
build/lib/tox/venv.py:            command_path = self.getcommandpath("python")
build/lib/tox/config/__init__.py:                base_exe = {"py": "python"}.get(match.group(1), match.group(1))
build/lib/tox/config/__init__.py:            name = "python"
build/lib/tox/config/__init__.py:        known_factors.update({"py", "python"})
build/lib/tox/config/__init__.py:            all_envs["python"] = None
build/lib/tox/interpreters/py_spec.py:    "pypy" if tox.constants.INFO.IS_PYPY else "python",
build/lib/tox/interpreters/via_path.py:                    "pypy" if info["implementation"] == "PyPy" else "python",
build/lib/tox/interpreters/windows/__init__.py:        if spec.name == "python":
build/lib/tox/interpreters/windows/pep514.py:        name = "python" if company == "PythonCore" else company
build/lib/tox/logs/env.py:        self.dict["python"] = answer
```
Nevertheless looks like test suite is going on /dev/tree if there is no `python` executable (I have only `python3` in my build env) and `tox` is first ever python module which I'm trying to package as rpm and Solaris IPS packages (I have already almost 600 cleaned packages)

**Comment by gaborbernat** [comment] 2021-09-30 10:53
> I'll leave this issue open for a week in case you follow it up with a PR. Otherwise will close as the use case is too fringe.

Closing as agreed above.

**Closed by gaborbernat** 2021-09-30 10:53 UTC
Labels: help:wanted
