### ISSUE TITLE
Regression (?) deps no longer accepts flags

### ISSUE THREAD

**Issue by julien-lecomte** [tox-dev/tox#2717] opened 2022-12-14 21:20 UTC
## Issue

The following tox.ini works perfectly in 3.x, but now, even with the flags quotted, it no longer works.

```
[tox]
envlist = py37, py38, py39

skipsdist = true

[testenv]
allowlist_externals = make
deps =
  --upgrade
  -rrequirements-dev.txt
commands = make check
```

## Environment

tox 4.0.9

## Output of running tox

Provide the output of `tox -rvv`:

```console
py37: failed with unrecognized arguments: --upgrade for tox env py within deps
py37: FAIL ✖ in 0.14 seconds
py38: failed with unrecognized arguments: --upgrade for tox env py within deps
py38: FAIL ✖ in 0.06 seconds
py39: failed with unrecognized arguments: --upgrade for tox env py within deps
  py37: FAIL code 1 (0.14 seconds)
  py38: FAIL code 1 (0.06 seconds)
  py39: FAIL code 1 (0.00 seconds)
  evaluation failed :( (0.40 seconds)

```

**Comment by gaborbernat** [comment] 2022-12-14 21:24
Duplicate of https://github.com/tox-dev/tox/issues/2631

**Comment by gaborbernat** [comment] 2022-12-14 21:25
It makes no sense to add `--upgrade` in this context. Worked by chance on v3

**Closed by gaborbernat** 2022-12-14 21:24 UTC
