### ISSUE TITLE
[meta] Replace pylib with other constructs

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox#610] opened 2017-09-06 21:30 UTC
**NOTE** to make the transition easier, I suggest waiting until we can drop 2.6 support (when pip 10 is released) - see [milestone status](https://github.com/pypa/pip/milestone/23).

[pylib](https://pypi.python.org/pypi/py/1.4.26) is not actively maintained anymore (last release was end of 2014) and we should slowly move to actively maintained constructs and remove constructs that trip up static code analysis in modern IDEs.

- [x] **py.std.[stdlib module]**

instead of accessing stdlib modules through this shortcut they should be used as intended (normal import)

see: https://github.com/tox-dev/tox/issues/592

- [x] **py.builtin**

This is used as a py2/py3 comaptibility layer, so these should be replaced wiht use of e.g. six

- [ ] **py.path**

Should be replaced with e.g. stdlib pathlib (there is a Python2 backport) 

- [ ] **py.io**

TODO

- [x] **py.process**

TODO

Each part should be addressed in a separate PR.

**Comment by nicoddemus** [comment] 2017-09-06 21:46
> Should be replaced with e.g. stdlib pathlib (there is a Python2 backport)

I'm interested in ideas on how to do this in particular; it is hard because `py.path` is part of public APIs in many places in pytest, and quite a few in tox as well.

**Comment by obestwalter** [comment] 2017-09-06 21:55
Hi @nicoddemus tox has no public API except for its hooks. 

https://github.com/tox-dev/tox/blob/master/CHANGELOG.rst#200-2015-05-12

> rename internal files -- tox offers no external API except for the experimental plugin hooks, use tox internals at your own risk.

**Comment by obestwalter** [comment] 2017-09-06 22:00
No concrete ideas yet how to tackle that. But my gut feeling is that this will be part of a world breaking tox 3.0 :)

**Comment by nicoddemus** [comment] 2017-09-06 22:26
Good point, for `tox` I think the problem is much smaller given only a few hooks and plugins might depend on it. For pytest is quite the contrary thought... 😓

**Comment by obestwalter** [comment] 2017-09-06 22:35
Yeah, I feel you. I mean there is even the tmpdir fixture that provides a py.path object, so that gets officially exposed. I usually have a fixture in my conftest to override that with the current path object of my choice. Maybe in pytest the ship has sailed and we're at least stuck with the py.path API for a very long time?

**Comment by The-Compiler** [comment] 2017-09-07 06:02
I remember having talked with some people about this (at the sprint last year maybe?) and the plan was to have a layer over pathlib which exposes an API similar (or ideally the same to) py.path, with a config option to turn that compatibility layer off.

**Comment by RonnyPfannschmidt** [comment] 2017-09-07 06:07
@The-Compiler i believe that was for pytest

**Comment by nicoddemus** [comment] 2017-09-07 06:07
@The-Compiler yep we talked about this, but the lingering aspect of this was: how solid can we make that compatibility layer, and how long it would last. Unlike other parts of deprecated code, `py.path` is very central to a lot of things in pytest, starting from `tmpdir` which is an extremely used fixture, to all a lot hooks of important objects having `py.path` objects as public API (`config.rootdir` for example).

**Comment by nicoddemus** [comment] 2017-09-07 06:09
@RonnyPfannschmidt made me realize we might be hijacking this thread, so we probably should move this discussion over to pytest-dev/pytest#2230. 😬

**Comment by obestwalter** [comment] 2017-09-07 06:12
I think it's not going to be that horrible for tox, but we'll cross that bridge once we get there (not this year anymore, I am pretty sure).

**Comment by gaborbernat** [comment] 2019-05-02 21:38
Let's do this with tox 4 and python 3 only.

**Comment by jayvdb** [comment] 2020-10-20 06:11
I am guessing that the work is effectively already completed as part of https://github.com/tox-dev/tox/issues/1394 , and there is no desire to fix this in tox v3.. ?

I'd be willing to attempt at least a minimal pathlib fix for tox v3 if there is maintainer interest in this, as I am running into py.path complications on other PRs I am working on.

Might be worth adding a note about that at the top of the issue, or even close this issue.

**Comment by gaborbernat** [comment] 2020-10-20 06:19
That's the hope. However, we'll keep the issue open until v4 is out.

**Comment by gaborbernat** [comment] 2021-01-20 16:44
With the release of version 4 alpha this now has been resolved.

**Closed by gaborbernat** 2021-01-20 16:44 UTC
Labels: help:wanted, level:hard, needs:discussion, type:internal
