### ISSUE TITLE
tox4: fails when invoked inside Git bash (MINGW64)

### ISSUE THREAD

**Issue by johannesloibl** [tox-dev/tox#2437] opened 2022-06-02 20:58 UTC
When execution any tox command inside a Git bash shell following error occurs:

![image](https://user-images.githubusercontent.com/48917891/171736856-e839bbd5-b7df-4413-90b5-51c7ecdbeb5a.png)

Tox version 4.0.0b4 (tox 3.25 works fine)

**Comment by jugmac00** [comment] 2022-10-01 12:49
I have no access to a Windows box - yet... I pinged a friend at Microsoft.

**Comment by ssbarnea** [comment] 2022-11-20 21:57
One first question here is if we should support MINGW under Windows as we already have: navite and WSL paths. I did not imagine that MinGW is still a thing in 2022.

**Comment by ssbarnea** [comment] 2022-11-20 22:15
Closing as unable to reproduce. I installed mingw and tried running tox 4 with tox repository itself, so far it worked fine.

**Closed by ssbarnea** 2022-11-20 22:15 UTC
Labels: bug:normal, os:windows
