### ISSUE TITLE
Exit code should be displayed or relayed

### ISSUE THREAD

**Issue by jaraco** [tox-dev/tox#452] opened 2017-02-07 19:49 UTC
Consider a test run that exits unexpectedly:

```
$ cat tox.ini
[tox]
skipsdist=true

[testenv]
commands=python -c "import sys; sys.exit(70)"
$ tox        
python installed: appdirs==1.4.0,packaging==16.8,pyparsing==2.1.10,six==1.10.0
python runtests: PYTHONHASHSEED='3650451697'
python runtests: commands[0] | python -c import sys; sys.exit(70)
ERROR: InvocationError: '/Users/jaraco/Dropbox/code/public/tox/new/.tox/python/bin/python -c import sys; sys.exit(70)'
____________________________________________ summary _____________________________________________
ERROR:   python: commands failed
$ echo $?
1
```

Although the test runner is exiting with the exit code of 70, that exit code is masked and swallowed by tox. The only reason it appears here is because it's literally in the command. To recover it, one needs to bypass tox and invoke the test runner separately. Better would be for tox to either report the exit code (as part of the InvocationError) or pass it through as its own exit code.

**Comment by RonnyPfannschmidt** [comment] 2017-02-07 19:51
since tox does run more than one command, i think its bet to display the code

**Comment by The-Compiler** [comment] 2017-02-07 20:10
Duplicate of #290.

**Closed by The-Compiler** 2017-02-07 20:10 UTC
