### ISSUE TITLE
tox4: posargs --pdb on pytest testenvs executed but no pdb show up / test finish

### ISSUE THREAD

**Issue by loechel** [tox-dev/tox#2050] opened 2021-04-28 20:11 UTC
When I run tox4 on a pytest testenv like that:

```

[testenv]
usedevelop = True
extras =
    test

commands =
    python -VV
    pip list
    pytest --cov=src --cov=tests --cov-report=xml  {posargs}
```

it shows a different behaviour than on tox3 where the python console showed up and you could debug the failing test.

This is especially problematic on paralell processing of the tests, as there the execution just halt and did not continue.

**Comment by gaborbernat** [comment] 2021-04-28 20:12
Hello, can you please explain in detail here? Thanks!

**Comment by loechel** [comment] 2021-04-28 20:18
Sorry @gaborbernat  I was still on writing the problem, as the ticked was falsly created, I updated the comment / explaination.

**Comment by jugmac00** [comment] 2021-04-29 20:53
Hi @loechel,

could you please show us what command you ran? And possibly also the repo to reproduce the problem?

I just tested `--pdb` on a personal project and both with `tox -e py38 -- --pdb` and `tox4 -e py38 -- --pdb` I was dropped in the `pdb` repl and with both `tox -p -- --pdb` and `tox4 p --pdb` it just hung.

So I cannot see a different behavior between tox3 and tox4.

FWIW I used git@github.com:jugmac00/hibpcli.git and put a `raise ValueError` just after this line to provoke a test failure.

**Comment by loechel** [comment] 2021-04-29 22:36
@jugmac00 I was testing some things on https://github.com/zopefoundation/RestrictedPython 

As that repository currently has a test coverage of 100 % and all test passing you need to tweak a test to fail to be thrown into the debugger.

I casually test via 

```
tox -- --pdb
```


or with tox4

```
tox4 -- --pdb
```

but also with the parallel execution model of tox4

```
tox4 -p auto -- --pdb
```

On my macOS there is a difference between tox3 and tox4. on tox3 the pdb console did correctly show up, on tox4 without the parallel execution modell it halts and showes that it halts, but not the console:

tox3 output:

```
py37 develop-inst-noop: /Users/ri62gep/workspaces/Python/RestrictedPython
py37 installed: attrs==20.3.0,coverage==5.5,fancycompleter==0.9.1,importlib-metadata==4.0.1,iniconfig==1.1.1,packaging==20.9,pdbpp==0.10.2,pluggy==0.13.1,py==1.10.0,Pygments==2.8.1,pyparsing==2.4.7,pyrepl==0.9.0,pytest==6.2.3,pytest-cov==2.11.1,pytest-html==3.1.1,pytest-metadata==1.11.0,pytest-mock==3.6.0,-e git+git@github.com:zopefoundation/RestrictedPython.git@2e2d3fda70e574f379a7b2fa3d0261388e3c7d0d#egg=RestrictedPython,toml==0.10.2,typing-extensions==3.7.4.3,wmctrl==0.4,zipp==3.4.1
py37 run-test-pre: PYTHONHASHSEED='2607870095'
py37 run-test: commands[0] | python -VV
Python 3.7.10 (default, Mar 27 2021, 20:20:23)
[Clang 12.0.0 (clang-1200.0.32.29)]
py37 run-test: commands[1] | pip list
Package            Version  Location
------------------ -------- -----------------------------------------------------
attrs              20.3.0
coverage           5.5
fancycompleter     0.9.1
importlib-metadata 4.0.1
iniconfig          1.1.1
packaging          20.9
pdbpp              0.10.2
pip                21.0.1
pluggy             0.13.1
py                 1.10.0
Pygments           2.8.1
pyparsing          2.4.7
pyrepl             0.9.0
pytest             6.2.3
pytest-cov         2.11.1
pytest-html        3.1.1
pytest-metadata    1.11.0
pytest-mock        3.6.0
RestrictedPython   5.2.dev0 /Users/ri62gep/workspaces/Python/RestrictedPython/src
setuptools         54.2.0
toml               0.10.2
typing-extensions  3.7.4.3
wheel              0.36.2
wmctrl             0.4
zipp               3.4.1
WARNING: You are using pip version 21.0.1; however, version 21.1 is available.
You should consider upgrading via the '/Users/ri62gep/workspaces/Python/RestrictedPython/.tox/py37/bin/python -m pip install --upgrade pip' command.
py37 run-test: commands[2] | pytest --cov=src --cov=tests --cov-report=xml --html=_build/pytest/report-py37.html --self-contained-html --pdb
==================================================================================================================================================================================================================================== test session starts =====================================================================================================================================================================================================================================
platform darwin -- Python 3.7.10, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
cachedir: .tox/py37/.pytest_cache
rootdir: /Users/ri62gep/workspaces/Python/RestrictedPython, configfile: setup.cfg, testpaths: tests
plugins: html-3.1.1, cov-2.11.1, metadata-1.11.0, mock-3.6.0
collected 295 items

tests/test_Guards.py ............s.                                                                                                                                                                                                                                                                                                                                                                                                                                                    [  4%]
tests/test_NamedExpr.py sss                                                                                                                                                                                                                                                                                                                                                                                                                                                            [  5%]
tests/test_Utilities.py .....                                                                                                                                                                                                                                                                                                                                                                                                                                                          [  7%]
tests/test_compile.py ..............s..s                                                                                                                                                                                                                                                                                                                                                                                                                                               [ 13%]
tests/test_compile_restricted_function.py ........                                                                                                                                                                                                                                                                                                                                                                                                                                     [ 16%]
tests/test_eval.py ............                                                                                                                                                                                                                                                                                                                                                                                                                                                        [ 20%]
tests/test_imports.py .ss..                                                                                                                                                                                                                                                                                                                                                                                                                                                            [ 22%]
tests/test_iterating_over_dict_items.py ..                                                                                                                                                                                                                                                                                                                                                                                                                                             [ 22%]
tests/test_print_function.py ............                                                                                                                                                                                                                                                                                                                                                                                                                                              [ 26%]
tests/test_print_stmt.py ssssssssss                                                                                                                                                                                                                                                                                                                                                                                                                                                    [ 30%]
tests/test_random.py F
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> traceback >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

    @skipUnless(IS_PY37_OR_GREATER, ">")
    def test_random_os():
        >
>       assert result.code is not None
E       assert None is not None
E        +  where None = CompileResult(code=None, errors=('Line 4: "xxx".',), warnings=["Line None: Prints, but never reads 'printed' variable."], used_names={'random': True}).code

tests/test_random.py:59: AssertionError
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PDB >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PDB post_mortem (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[12] > /Users/ri62gep/workspaces/Python/RestrictedPython/tests/test_random.py(59)test_random_os()
-> assert result.code is not None
   6 frames hidden (try 'help hidden_frames')
(Pdb++)

```

on tox4 output:

```
py37: install_package> python -I -m pip install --no-deps --force-reinstall --no-build-isolation -e /Users/ri62gep/workspaces/Python/RestrictedPython
py37: commands[0]> python -VV
Python 3.7.10 (default, Mar 27 2021, 20:20:23)
[Clang 12.0.0 (clang-1200.0.32.29)]
py37: commands[1]> pip list
Package            Version  Location
------------------ -------- -----------------------------------------------------
attrs              20.3.0
coverage           5.5
fancycompleter     0.9.1
importlib-metadata 4.0.1
iniconfig          1.1.1
packaging          20.9
pdbpp              0.10.2
pip                21.0.1
pluggy             0.13.1
py                 1.10.0
Pygments           2.8.1
pyparsing          2.4.7
pyrepl             0.9.0
pytest             6.2.3
pytest-cov         2.11.1
pytest-html        3.1.1
pytest-metadata    1.11.0
pytest-mock        3.5.1
RestrictedPython   5.2.dev0 /Users/ri62gep/workspaces/Python/RestrictedPython/src
setuptools         52.0.0
toml               0.10.2
typing-extensions  3.7.4.3
wheel              0.36.2
wmctrl             0.4
zipp               3.4.1
py37: commands[2]> pytest --cov=src --cov=tests --cov-report=xml --html=_build/pytest/report-py37.html --self-contained-html --pdb
==================================================================================================================================================================================================================================== test session starts =====================================================================================================================================================================================================================================
platform darwin -- Python 3.7.10, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: /Users/ri62gep/workspaces/Python/RestrictedPython, configfile: setup.cfg, testpaths: tests
plugins: html-3.1.1, cov-2.11.1, metadata-1.11.0, mock-3.5.1
collected 295 items

tests/test_Guards.py ............s.                                                                                                                                                                                                                                                                                                                                                                                                                                                    [  4%]
tests/test_NamedExpr.py sss                                                                                                                                                                                                                                                                                                                                                                                                                                                            [  5%]
tests/test_Utilities.py .....                                                                                                                                                                                                                                                                                                                                                                                                                                                          [  7%]
tests/test_compile.py ..............s..s                                                                                                                                                                                                                                                                                                                                                                                                                                               [ 13%]
tests/test_compile_restricted_function.py ........                                                                                                                                                                                                                                                                                                                                                                                                                                     [ 16%]
tests/test_eval.py ............                                                                                                                                                                                                                                                                                                                                                                                                                                                        [ 20%]
tests/test_imports.py .ss..                                                                                                                                                                                                                                                                                                                                                                                                                                                            [ 22%]
tests/test_iterating_over_dict_items.py ..                                                                                                                                                                                                                                                                                                                                                                                                                                             [ 22%]
tests/test_print_function.py ............                                                                                                                                                                                                                                                                                                                                                                                                                                              [ 26%]
tests/test_print_stmt.py ssssssssss                                                                                                                                                                                                                                                                                                                                                                                                                                                    [ 30%]
tests/test_random.py F
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> traceback >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

    @skipUnless(IS_PY37_OR_GREATER, ">")
    def test_random_os():
         
>       assert result.code is not None
E       assert None is not None
E        +  where None = CompileResult(code=None, errors=('Line 4: ">".',), warnings=["Line None: Prints, but never reads 'printed' variable."], used_names={'random': True}).code

tests/test_random.py:59: AssertionError
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PDB >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PDB post_mortem (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
```

It stopped two lines before the console compared to tox 3

**Comment by loechel** [comment] 2021-04-29 22:55
Well even if the behaviour would be like on tox3, wouldn't it be good to auto disable parallel execution if `--pdb` is  supplied as posarg?

**Comment by jugmac00** [comment] 2021-04-30 06:37
I assume you ran `tox --pdb` and `tox4 --pdb` to get above output?

I still can't reproduce your problem. Both with `tox` and `tox4` I get a pdb shell.

```
❯ tox -- --pdb
py27 develop-inst-noop: /home/jugmac00/Projects/RestrictedPython
py27 installed: DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.,atomicwrites==1.4.0,attrs==20.3.0,backports.functools-lru-cache==1.6.4,configparser==4.0.2,contextlib2==0.6.0.post1,coverage==5.5,funcsigs==1.0.2,importlib-metadata==2.1.1,mock==3.0.5,more-itertools==5.0.0,packaging==20.9,pathlib2==2.3.5,pluggy==0.13.1,py==1.10.0,pyparsing==2.4.7,pytest==4.6.11,pytest-cov==2.11.1,pytest-html==1.22.1,pytest-metadata==1.11.0,pytest-mock==2.0.0,-e git+git@github.com:zopefoundation/RestrictedPython@ed13a18de6143580e9c010bd88ca24bfc058c875#egg=RestrictedPython,scandir==1.10.0,six==1.15.0,wcwidth==0.2.5,zipp==1.2.0
py27 run-test-pre: PYTHONHASHSEED='876858594'
py27 run-test: commands[0] | python -V
Python 2.7.17
py27 run-test: commands[1] | pip list
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Package                       Version     Location
----------------------------- ----------- --------------------------------------------
atomicwrites                  1.4.0
attrs                         20.3.0
backports.functools-lru-cache 1.6.4
configparser                  4.0.2
contextlib2                   0.6.0.post1
coverage                      5.5
funcsigs                      1.0.2
importlib-metadata            2.1.1
mock                          3.0.5
more-itertools                5.0.0
packaging                     20.9
pathlib2                      2.3.5
pip                           20.3.4
pluggy                        0.13.1
py                            1.10.0
pyparsing                     2.4.7
pytest                        4.6.11
pytest-cov                    2.11.1
pytest-html                   1.22.1
pytest-metadata               1.11.0
pytest-mock                   2.0.0
RestrictedPython              5.2.dev0    /home/jugmac00/Projects/RestrictedPython/src
scandir                       1.10.0
setuptools                    44.1.1
six                           1.15.0
wcwidth                       0.2.5
wheel                         0.36.2
zipp                          1.2.0
py27 run-test: commands[2] | pytest --cov=src --cov=tests --cov-report=xml --html=_build/pytest/report-py27.html --self-contained-html --pdb
===================================================== test session starts ======================================================
platform linux2 -- Python 2.7.17, pytest-4.6.11, py-1.10.0, pluggy-0.13.1
cachedir: .tox/py27/.pytest_cache
rootdir: /home/jugmac00/Projects/RestrictedPython, inifile: setup.cfg, testpaths: tests
plugins: cov-2.11.1, html-1.22.1, metadata-1.11.0, mock-2.0.0
collected 294 items                                                                                                            

tests/test_Guards.py ...........s..                                                                                      [  4%]
tests/test_NamedExpr.py sss                                                                                              [  5%]
tests/test_Utilities.py .....                                                                                            [  7%]
tests/test_compile.py .........s.......s                                                                                 [ 13%]
tests/test_compile_restricted_function.py ........                                                                       [ 16%]
tests/test_eval.py ............                                                                                          [ 20%]
tests/test_imports.py ...ss                                                                                              [ 22%]
tests/test_iterating_over_dict_items.py ..                                                                               [ 22%]
tests/test_print_function.py F
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> traceback >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

    def test_print_function__simple_prints():
        glb = {'_print_': PrintCollector, '_getattr_': None}
    
        code, errors = compiler(ALLOWED_PRINT_FUNCTION)[:2]
        assert errors == ()
>       assert code is None
E       assert <code object <module> at 0x7fed8ffdf530, file "<string>", line 2> is None

tests/test_print_function.py:52: AssertionError
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PDB >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PDB post_mortem (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> /home/jugmac00/Projects/RestrictedPython/tests/test_print_function.py(52)test_print_function__simple_prints()
-> assert code is None
```

```
❯ tox4 -r -- --pdb
py27: install_deps> python -E -m pip install 'isort>=4.3.2' pytest-cov pytest-html 'pytest-html<2' 'pytest<5'
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
ERROR: Double requirement given: pytest-html<2 (already in pytest-html, name='pytest-html')
py27: exit 1 (0.65 seconds) /home/jugmac00/Projects/RestrictedPython> python -E -m pip install 'isort>=4.3.2' pytest-cov pytest-html 'pytest-html<2' 'pytest<5' pid=24646
py27: FAIL ✖ in 0.77 seconds
py35: install_deps> python -I -m pip install 'isort>=4.3.2' pytest-cov pytest-html 'pytest-html<2' 'pytest<5'
.pkg: install_requires> python -I -m pip install 'setuptools>=40.8.0' wheel
.pkg: get_requires_for_build_wheel> python /home/jugmac00/.local/lib/python3.6/site-packages/tox/util/pep517/backend.py True setuptools.build_meta __legacy__
.pkg: install_requires_for_build_wheel> python -I -m pip install wheel
.pkg: prepare_metadata_for_build_wheel> python /home/jugmac00/.local/lib/python3.6/site-packages/tox/util/pep517/backend.py True setuptools.build_meta __legacy__
.pkg: get_requires_for_build_sdist> python /home/jugmac00/.local/lib/python3.6/site-packages/tox/util/pep517/backend.py True setuptools.build_meta __legacy__
py35: install_package_deps> python -I -m pip install 'setuptools>=40.8.0' wheel pytest pytest-mock
py35: install_package> python -I -m pip install --no-deps --force-reinstall --no-build-isolation -e /home/jugmac00/Projects/RestrictedPython
py35: commands[0]> python -V
Python 3.5.10
py35: commands[1]> pip list
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
Package            Version  Location
------------------ -------- --------------------------------------------
atomicwrites       1.4.0
attrs              20.3.0
coverage           5.5
importlib-metadata 2.1.1
iniconfig          1.1.1
isort              4.3.21
more-itertools     8.7.0
packaging          20.9
pathlib2           2.3.5
pip                20.3.4
pluggy             0.13.1
py                 1.10.0
pyparsing          2.4.7
pytest             6.1.2
pytest-cov         2.11.1
pytest-html        1.22.1
pytest-metadata    1.8.0
pytest-mock        3.5.1
RestrictedPython   5.2.dev0 /home/jugmac00/Projects/RestrictedPython/src
setuptools         50.3.2
six                1.15.0
toml               0.10.2
wcwidth            0.2.5
wheel              0.36.2
zipp               1.2.0
py35: commands[2]> pytest --cov=src --cov=tests --cov-report=xml --html=_build/pytest/report-py35.html --self-contained-html --pdb
===================================================== test session starts ======================================================
platform linux -- Python 3.5.10, pytest-6.1.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/jugmac00/Projects/RestrictedPython, configfile: setup.cfg, testpaths: tests
plugins: metadata-1.8.0, cov-2.11.1, html-1.22.1, mock-3.5.1
collected 294 items

tests/test_Guards.py ............s.                                                                                      [  4%]
tests/test_NamedExpr.py sss                                                                                              [  5%]
tests/test_Utilities.py .....                                                                                            [  7%]
tests/test_compile.py ..............s..s                                                                                 [ 13%]
tests/test_compile_restricted_function.py ........                                                                       [ 16%]
tests/test_eval.py ............                                                                                          [ 20%]
tests/test_imports.py .ss..                                                                                              [ 22%]
tests/test_iterating_over_dict_items.py ..                                                                               [ 22%]
tests/test_print_function.py F
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> traceback >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

    def test_print_function__simple_prints():
        glb = {'_print_': PrintCollector, '_getattr_': None}
    
        code, errors = compiler(ALLOWED_PRINT_FUNCTION)[:2]
        assert errors == ()
>       assert code is None
E       assert <code object <module> at 0x7ff838299b70, file "<string>", line 2> is None

tests/test_print_function.py:52: AssertionError
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PDB >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PDB post_mortem (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> /home/jugmac00/Projects/RestrictedPython/tests/test_print_function.py(52)test_print_function__simple_prints()
-> assert code is None
(Pdb) 
```

I do not know what is so special about your case. Could you verify that this is a `tox` issue, and not a `pytest` or `pdb` issue? So, could you please run it with `pytest` without `tox` involved?

As a last resort, could you push your deliberately broken branch so I can check it out?

## posargs and effect on tox

As about `tox` being aware of what gets passed to a command via `posargs`, and e.g. your proposal that parallel mode should be deactivated when `pytest` is called with the `--pdb` option...

I know that `tox` is used a lot with `pytest`, but still it feels not ok that `tox` should be aware of which command it runs, and especially not about which additional parameters are passed to that command.

Imagine the highly unlikely case, that one day `pytest` decides to replace `--pdb` with `--debug`. We not only would have to update `tox`, but we would need to be aware of which `pytest` version is run with `tox`  - sounds like the beginning of a maintenance nightmare :-)

So I am -1 on that.

Maybe the other maintainers have a different opinion?

**Comment by jugmac00** [comment] 2021-07-20 11:33
@loechel Closing this issue, as I cannot reproduce the problem.

Also, as nobody else stepped up, I think it is not a good idea to make `tox` aware of which parameters are passed to e.g. `pytest` - this would lead to a maintenance nightmare.

Feel free to reopen the issue when you have a reproducer.

**Closed by jugmac00** 2021-07-20 11:33 UTC
Labels: bug:normal
