### ISSUE TITLE
tox 4: --index-url not respected when specified in requirements file

### ISSUE THREAD

**Issue by r2dan** [tox-dev/tox#1986] opened 2021-03-30 12:13 UTC
Hi, when using the following tox.ini file:
```
[testenv]
deps=-rrequirements.txt
commands=echo "commands"
```
and the following requirements.txt file:
```
--index-url https://m.devpi.net/fschulze/dev
devpi-client==6.0.0dev3
```
Wrong pip command is executed and pip fails to install required dependencies (it should invoke --index-url devpi-client==version without the apostrophes) :
```
[venv]$ tox4 -rvvv
ROOT: 343 D setup logging to NOTSET on pid 87066 [tox/report.py:211]
ROOT: 349 W remove tox env folder /Users/mrusi/.tox/4/py [tox/tox_env/api.py:202]
ROOT: 511 W remove tox env folder /Users/mrusi/.tox/4/.pkg [tox/tox_env/api.py:202]
ROOT: 707 I find interpreter for spec PythonSpec(implementation=CPython) [virtualenv/discovery/builtin.py:62]
ROOT: 707 D discover exe for PythonInfo(spec=CPython3.8.5.final.0-64, exe=/Users/mrusi/venv/bin/python, platform=darwin, version='3.8.5 (default, Oct  8 2020, 12:28:24) \n[Clang 12.0.0 (clang-1200.0.32.2)]', encoding_fs_io=utf-8-utf-8) in /Users/mrusi/.pyenv/versions/3.8.5 [virtualenv/discovery/py_info.py:372]
ROOT: 709 D filesystem is not case-sensitive [virtualenv/info.py:28]
ROOT: 711 D Attempting to acquire lock 4583699072 on /Users/mrusi/Library/Application Support/virtualenv/py_info/1/557919b476b7b038a65f3e4c26e4409144c5ebc41d088eef7bcaf024bcdf4145.lock [filelock.py:270]
ROOT: 711 D Lock 4583699072 acquired on /Users/mrusi/Library/Application Support/virtualenv/py_info/1/557919b476b7b038a65f3e4c26e4409144c5ebc41d088eef7bcaf024bcdf4145.lock [filelock.py:274]
ROOT: 714 D got python info of /Users/mrusi/.pyenv/versions/3.8.5/bin/python3.8 from /Users/mrusi/Library/Application Support/virtualenv/py_info/1/557919b476b7b038a65f3e4c26e4409144c5ebc41d088eef7bcaf024bcdf4145.json [virtualenv/app_data/via_disk_folder.py:135]
ROOT: 714 D Attempting to release lock 4583699072 on /Users/mrusi/Library/Application Support/virtualenv/py_info/1/557919b476b7b038a65f3e4c26e4409144c5ebc41d088eef7bcaf024bcdf4145.lock [filelock.py:315]
ROOT: 715 D Lock 4583699072 released on /Users/mrusi/Library/Application Support/virtualenv/py_info/1/557919b476b7b038a65f3e4c26e4409144c5ebc41d088eef7bcaf024bcdf4145.lock [filelock.py:318]
ROOT: 715 I proposed PythonInfo(spec=CPython3.8.5.final.0-64, system=/Users/mrusi/.pyenv/versions/3.8.5/bin/python3.8, exe=/Users/mrusi/venv/bin/python, platform=darwin, version='3.8.5 (default, Oct  8 2020, 12:28:24) \n[Clang 12.0.0 (clang-1200.0.32.2)]', encoding_fs_io=utf-8-utf-8) [virtualenv/discovery/builtin.py:69]
ROOT: 715 D accepted PythonInfo(spec=CPython3.8.5.final.0-64, system=/Users/mrusi/.pyenv/versions/3.8.5/bin/python3.8, exe=/Users/mrusi/venv/bin/python, platform=darwin, version='3.8.5 (default, Oct  8 2020, 12:28:24) \n[Clang 12.0.0 (clang-1200.0.32.2)]', encoding_fs_io=utf-8-utf-8) [virtualenv/discovery/builtin.py:71]
ROOT: 765 I create virtual environment via CPython3Posix(dest=/Users/mrusi/.tox/4/py, clear=True, no_vcs_ignore=False, global=False) [virtualenv/run/session.py:52]
ROOT: 765 D delete /Users/mrusi/.tox/4/py [virtualenv/create/creator.py:169]
ROOT: 766 D create folder /Users/mrusi/.tox/4/py/bin [virtualenv/util/path/_sync.py:25]
ROOT: 766 D create folder /Users/mrusi/.tox/4/py/lib/python3.8/site-packages [virtualenv/util/path/_sync.py:25]
ROOT: 766 D write /Users/mrusi/.tox/4/py/pyvenv.cfg [virtualenv/create/pyenv_cfg.py:34]
ROOT: 767 D 	home = /Users/mrusi/.pyenv/versions/3.8.5 [virtualenv/create/pyenv_cfg.py:38]
ROOT: 767 D 	implementation = CPython [virtualenv/create/pyenv_cfg.py:38]
ROOT: 767 D 	version_info = 3.8.5.final.0 [virtualenv/create/pyenv_cfg.py:38]
ROOT: 767 D 	virtualenv = 20.4.3 [virtualenv/create/pyenv_cfg.py:38]
ROOT: 767 D 	include-system-site-packages = false [virtualenv/create/pyenv_cfg.py:38]
ROOT: 767 D 	base-prefix = /Users/mrusi/.pyenv/versions/3.8.5 [virtualenv/create/pyenv_cfg.py:38]
ROOT: 767 D 	base-exec-prefix = /Users/mrusi/.pyenv/versions/3.8.5 [virtualenv/create/pyenv_cfg.py:38]
ROOT: 767 D 	base-executable = /Users/mrusi/.pyenv/versions/3.8.5/bin/python3.8 [virtualenv/create/pyenv_cfg.py:38]
ROOT: 767 D symlink /Users/mrusi/.pyenv/versions/3.8.5/bin/python3.8 to /Users/mrusi/.tox/4/py/bin/python [virtualenv/util/path/_sync.py:44]
ROOT: 769 D create virtualenv import hook file /Users/mrusi/.tox/4/py/lib/python3.8/site-packages/_virtualenv.pth [virtualenv/create/via_global_ref/api.py:95]
ROOT: 769 D create /Users/mrusi/.tox/4/py/lib/python3.8/site-packages/_virtualenv.py [virtualenv/create/via_global_ref/api.py:98]
ROOT: 770 D ============================== target debug ============================== [virtualenv/run/session.py:54]
ROOT: 770 D debug via /Users/mrusi/.tox/4/py/bin/python /Users/mrusi/venv/lib/python3.8/site-packages/virtualenv/create/debug.py [virtualenv/create/creator.py:224]
ROOT: 770 D {
  "sys": {
    "executable": "/Users/mrusi/.tox/4/py/bin/python",
    "_base_executable": "/Users/mrusi/.tox/4/py/bin/python",
    "prefix": "/Users/mrusi/.tox/4/py",
    "base_prefix": "/Users/mrusi/.pyenv/versions/3.8.5",
    "real_prefix": null,
    "exec_prefix": "/Users/mrusi/.tox/4/py",
    "base_exec_prefix": "/Users/mrusi/.pyenv/versions/3.8.5",
    "path": [
      "/Users/mrusi/.pyenv/versions/3.8.5/lib/python38.zip",
      "/Users/mrusi/.pyenv/versions/3.8.5/lib/python3.8",
      "/Users/mrusi/.pyenv/versions/3.8.5/lib/python3.8/lib-dynload",
      "/Users/mrusi/.tox/4/py/lib/python3.8/site-packages"
    ],
    "meta_path": [
      "<class '_virtualenv._Finder'>",
      "<class '_frozen_importlib.BuiltinImporter'>",
      "<class '_frozen_importlib.FrozenImporter'>",
      "<class '_frozen_importlib_external.PathFinder'>"
    ],
    "fs_encoding": "utf-8",
    "io_encoding": "utf-8"
  },
  "version": "3.8.5 (default, Oct  8 2020, 12:28:24) \n[Clang 12.0.0 (clang-1200.0.32.2)]",
  "makefile_filename": "/Users/mrusi/.pyenv/versions/3.8.5/lib/python3.8/config-3.8-darwin/Makefile",
  "os": "<module 'os' from '/Users/mrusi/.pyenv/versions/3.8.5/lib/python3.8/os.py'>",
  "site": "<module 'site' from '/Users/mrusi/.pyenv/versions/3.8.5/lib/python3.8/site.py'>",
  "datetime": "<module 'datetime' from '/Users/mrusi/.pyenv/versions/3.8.5/lib/python3.8/datetime.py'>",
  "math": "<module 'math' from '/Users/mrusi/.pyenv/versions/3.8.5/lib/python3.8/lib-dynload/math.cpython-38-darwin.so'>",
  "json": "<module 'json' from '/Users/mrusi/.pyenv/versions/3.8.5/lib/python3.8/json/__init__.py'>"
} [virtualenv/run/session.py:55]
ROOT: 814 I add seed packages via FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/mrusi/Library/Application Support/virtualenv) [virtualenv/run/session.py:59]
py: 819 D got embed update of distribution pip from /Users/mrusi/Library/Application Support/virtualenv/wheel/3.8/embed/1/pip.json [virtualenv/app_data/via_disk_folder.py:135]
py: 819 D got embed update of distribution wheel from /Users/mrusi/Library/Application Support/virtualenv/wheel/3.8/embed/1/wheel.json [virtualenv/app_data/via_disk_folder.py:135]
py: 820 D got embed update of distribution setuptools from /Users/mrusi/Library/Application Support/virtualenv/wheel/3.8/embed/1/setuptools.json [virtualenv/app_data/via_disk_folder.py:135]
py: 823 D using periodically updated wheel /Users/mrusi/Library/Application Support/virtualenv/wheel/house/setuptools-50.3.2-py3-none-any.whl [virtualenv/seed/wheels/periodic_update.py:53]
py: 823 D using periodically updated wheel /Users/mrusi/Library/Application Support/virtualenv/wheel/house/wheel-0.36.0-py2.py3-none-any.whl [virtualenv/seed/wheels/periodic_update.py:53]
py: 823 D using periodically updated wheel /Users/mrusi/Library/Application Support/virtualenv/wheel/house/pip-20.3.1-py2.py3-none-any.whl [virtualenv/seed/wheels/periodic_update.py:53]
py: 824 D install setuptools from wheel /Users/mrusi/Library/Application Support/virtualenv/wheel/house/setuptools-50.3.2-py3-none-any.whl via CopyPipInstall [virtualenv/seed/embed/via_app_data/via_app_data.py:49]
py: 824 D install wheel from wheel /Users/mrusi/Library/Application Support/virtualenv/wheel/house/wheel-0.36.0-py2.py3-none-any.whl via CopyPipInstall [virtualenv/seed/embed/via_app_data/via_app_data.py:49]
py: 824 D install pip from wheel /Users/mrusi/Library/Application Support/virtualenv/wheel/house/pip-20.3.1-py2.py3-none-any.whl via CopyPipInstall [virtualenv/seed/embed/via_app_data/via_app_data.py:49]
py: 825 D Attempting to acquire lock 4585645488 on /Users/mrusi/Library/Application Support/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-50.3.2-py3-none-any.lock [filelock.py:270]
py: 825 D Attempting to acquire lock 4585644960 on /Users/mrusi/Library/Application Support/virtualenv/wheel/3.8/image/1/CopyPipInstall/wheel-0.36.0-py2.py3-none-any.lock [filelock.py:270]
py: 826 D Attempting to acquire lock 4585646928 on /Users/mrusi/Library/Application Support/virtualenv/wheel/3.8/image/1/CopyPipInstall/pip-20.3.1-py2.py3-none-any.lock [filelock.py:270]
py: 826 D Lock 4585644960 acquired on /Users/mrusi/Library/Application Support/virtualenv/wheel/3.8/image/1/CopyPipInstall/wheel-0.36.0-py2.py3-none-any.lock [filelock.py:274]
py: 826 D Lock 4585645488 acquired on /Users/mrusi/Library/Application Support/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-50.3.2-py3-none-any.lock [filelock.py:274]
py: 826 D Lock 4585646928 acquired on /Users/mrusi/Library/Application Support/virtualenv/wheel/3.8/image/1/CopyPipInstall/pip-20.3.1-py2.py3-none-any.lock [filelock.py:274]
py: 826 D Attempting to release lock 4585644960 on /Users/mrusi/Library/Application Support/virtualenv/wheel/3.8/image/1/CopyPipInstall/wheel-0.36.0-py2.py3-none-any.lock [filelock.py:315]
py: 826 D Lock 4585644960 released on /Users/mrusi/Library/Application Support/virtualenv/wheel/3.8/image/1/CopyPipInstall/wheel-0.36.0-py2.py3-none-any.lock [filelock.py:318]
py: 826 D Attempting to release lock 4585645488 on /Users/mrusi/Library/Application Support/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-50.3.2-py3-none-any.lock [filelock.py:315]
py: 826 D Lock 4585645488 released on /Users/mrusi/Library/Application Support/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-50.3.2-py3-none-any.lock [filelock.py:318]
py: 827 D Attempting to release lock 4585646928 on /Users/mrusi/Library/Application Support/virtualenv/wheel/3.8/image/1/CopyPipInstall/pip-20.3.1-py2.py3-none-any.lock [filelock.py:315]
py: 827 D copy directory /Users/mrusi/Library/Application Support/virtualenv/wheel/3.8/image/1/CopyPipInstall/wheel-0.36.0-py2.py3-none-any/wheel to /Users/mrusi/.tox/4/py/lib/python3.8/site-packages/wheel [virtualenv/util/path/_sync.py:52]
py: 827 D Lock 4585646928 released on /Users/mrusi/Library/Application Support/virtualenv/wheel/3.8/image/1/CopyPipInstall/pip-20.3.1-py2.py3-none-any.lock [filelock.py:318]
py: 827 D copy directory /Users/mrusi/Library/Application Support/virtualenv/wheel/3.8/image/1/CopyPipInstall/pip-20.3.1-py2.py3-none-any/pip-20.3.1.dist-info to /Users/mrusi/.tox/4/py/lib/python3.8/site-packages/pip-20.3.1.dist-info [virtualenv/util/path/_sync.py:52]
py: 828 D copy directory /Users/mrusi/Library/Application Support/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-50.3.2-py3-none-any/setuptools-50.3.2.dist-info to /Users/mrusi/.tox/4/py/lib/python3.8/site-packages/setuptools-50.3.2.dist-info [virtualenv/util/path/_sync.py:52]
py: 837 D copy /Users/mrusi/Library/Application Support/virtualenv/wheel/3.8/image/1/CopyPipInstall/pip-20.3.1-py2.py3-none-any/pip-20.3.1.virtualenv to /Users/mrusi/.tox/4/py/lib/python3.8/site-packages/pip-20.3.1.virtualenv [virtualenv/util/path/_sync.py:52]
py: 838 D copy directory /Users/mrusi/Library/Application Support/virtualenv/wheel/3.8/image/1/CopyPipInstall/pip-20.3.1-py2.py3-none-any/pip to /Users/mrusi/.tox/4/py/lib/python3.8/site-packages/pip [virtualenv/util/path/_sync.py:52]
py: 839 D copy /Users/mrusi/Library/Application Support/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-50.3.2-py3-none-any/easy_install.py to /Users/mrusi/.tox/4/py/lib/python3.8/site-packages/easy_install.py [virtualenv/util/path/_sync.py:52]
py: 840 D copy /Users/mrusi/Library/Application Support/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-50.3.2-py3-none-any/distutils-precedence.pth to /Users/mrusi/.tox/4/py/lib/python3.8/site-packages/distutils-precedence.pth [virtualenv/util/path/_sync.py:52]
py: 841 D copy /Users/mrusi/Library/Application Support/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-50.3.2-py3-none-any/setuptools-50.3.2.virtualenv to /Users/mrusi/.tox/4/py/lib/python3.8/site-packages/setuptools-50.3.2.virtualenv [virtualenv/util/path/_sync.py:52]
py: 842 D copy directory /Users/mrusi/Library/Application Support/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-50.3.2-py3-none-any/setuptools to /Users/mrusi/.tox/4/py/lib/python3.8/site-packages/setuptools [virtualenv/util/path/_sync.py:52]
py: 850 D copy /Users/mrusi/Library/Application Support/virtualenv/wheel/3.8/image/1/CopyPipInstall/wheel-0.36.0-py2.py3-none-any/wheel-0.36.0.virtualenv to /Users/mrusi/.tox/4/py/lib/python3.8/site-packages/wheel-0.36.0.virtualenv [virtualenv/util/path/_sync.py:52]
py: 851 D copy directory /Users/mrusi/Library/Application Support/virtualenv/wheel/3.8/image/1/CopyPipInstall/wheel-0.36.0-py2.py3-none-any/wheel-0.36.0.dist-info to /Users/mrusi/.tox/4/py/lib/python3.8/site-packages/wheel-0.36.0.dist-info [virtualenv/util/path/_sync.py:52]
py: 880 D changing mode of /Users/mrusi/.tox/4/py/bin/wheel-3.8 to 755 [distlib/util.py:566]
py: 881 D changing mode of /Users/mrusi/.tox/4/py/bin/wheel3.8 to 755 [distlib/util.py:566]
py: 882 D changing mode of /Users/mrusi/.tox/4/py/bin/wheel3 to 755 [distlib/util.py:566]
py: 883 D changing mode of /Users/mrusi/.tox/4/py/bin/wheel to 755 [distlib/util.py:566]
py: 883 D generated console scripts wheel3.8 wheel3 wheel-3.8 wheel [virtualenv/seed/embed/via_app_data/pip_install/base.py:48]
py: 1086 D copy directory /Users/mrusi/Library/Application Support/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-50.3.2-py3-none-any/pkg_resources to /Users/mrusi/.tox/4/py/lib/python3.8/site-packages/pkg_resources [virtualenv/util/path/_sync.py:52]
py: 1114 D copy directory /Users/mrusi/Library/Application Support/virtualenv/wheel/3.8/image/1/CopyPipInstall/setuptools-50.3.2-py3-none-any/_distutils_hack to /Users/mrusi/.tox/4/py/lib/python3.8/site-packages/_distutils_hack [virtualenv/util/path/_sync.py:52]
py: 1119 D changing mode of /Users/mrusi/.tox/4/py/bin/easy_install-3.8 to 755 [distlib/util.py:566]
py: 1119 D changing mode of /Users/mrusi/.tox/4/py/bin/easy_install3.8 to 755 [distlib/util.py:566]
py: 1120 D changing mode of /Users/mrusi/.tox/4/py/bin/easy_install3 to 755 [distlib/util.py:566]
py: 1121 D changing mode of /Users/mrusi/.tox/4/py/bin/easy_install to 755 [distlib/util.py:566]
py: 1121 D generated console scripts easy_install3.8 easy_install easy_install3 easy_install-3.8 [virtualenv/seed/embed/via_app_data/pip_install/base.py:48]
py: 1498 D changing mode of /Users/mrusi/.tox/4/py/bin/pip3.8 to 755 [distlib/util.py:566]
py: 1498 D changing mode of /Users/mrusi/.tox/4/py/bin/pip-3.8 to 755 [distlib/util.py:566]
py: 1498 D changing mode of /Users/mrusi/.tox/4/py/bin/pip3 to 755 [distlib/util.py:566]
py: 1499 D changing mode of /Users/mrusi/.tox/4/py/bin/pip to 755 [distlib/util.py:566]
py: 1499 D generated console scripts pip3 pip pip3.8 pip-3.8 [virtualenv/seed/embed/via_app_data/pip_install/base.py:48]
ROOT: 1499 I add activators for Bash, CShell, Fish, PowerShell, Python, Xonsh [virtualenv/run/session.py:64]
ROOT: 1504 D write /Users/mrusi/.tox/4/py/pyvenv.cfg [virtualenv/create/pyenv_cfg.py:34]
ROOT: 1504 D 	home = /Users/mrusi/.pyenv/versions/3.8.5 [virtualenv/create/pyenv_cfg.py:38]
ROOT: 1504 D 	implementation = CPython [virtualenv/create/pyenv_cfg.py:38]
ROOT: 1504 D 	version_info = 3.8.5.final.0 [virtualenv/create/pyenv_cfg.py:38]
ROOT: 1504 D 	virtualenv = 20.4.3 [virtualenv/create/pyenv_cfg.py:38]
ROOT: 1504 D 	include-system-site-packages = false [virtualenv/create/pyenv_cfg.py:38]
ROOT: 1504 D 	base-prefix = /Users/mrusi/.pyenv/versions/3.8.5 [virtualenv/create/pyenv_cfg.py:38]
ROOT: 1504 D 	base-exec-prefix = /Users/mrusi/.pyenv/versions/3.8.5 [virtualenv/create/pyenv_cfg.py:38]
ROOT: 1504 D 	base-executable = /Users/mrusi/.pyenv/versions/3.8.5/bin/python3.8 [virtualenv/create/pyenv_cfg.py:38]
ROOT: 1508 W install_deps> python -I -m pip install '--index-url https://m.devpi.net/fschulze/dev' devpi-client==6.0.0dev3 [tox/tox_env/api.py:288]

Usage:
  /Users/mrusi/.tox/4/py/bin/python -m pip install [options] <requirement specifier> [package-index-options] ...
  /Users/mrusi/.tox/4/py/bin/python -m pip install [options] -r <requirements file> [package-index-options] ...
  /Users/mrusi/.tox/4/py/bin/python -m pip install [options] [-e] <vcs project url> ...
  /Users/mrusi/.tox/4/py/bin/python -m pip install [options] [-e] <local project path> ...
  /Users/mrusi/.tox/4/py/bin/python -m pip install [options] <archive url/path> ...

no such option: --index-url https://m.devpi.net/fschulze/dev
ROOT: 2421 C exit 2 (0.91 seconds) /Users/mrusi> python -I -m pip install '--index-url https://m.devpi.net/fschulze/dev' devpi-client==6.0.0dev3 pid=87070 [tox/execute/api.py:193]
  py: FAIL code 2 (2.07 seconds)
  evaluation failed :( (2.14 seconds)
```
Using `python -I -m pip install --index-url https://m.devpi.net/fschulze/dev devpi-client==6.0.0dev3` would work. 

BTW is there any particular reason you do not pass just -r[requirements_file_path] directly to pip? It would make sense in my opinion as new pip resolver could do its job and the built environment will match the one executed by passing the whole requirements file.

**Comment by jugmac00** [comment] 2021-04-02 10:00
I reproduced the problem - it boils down to

```
import subprocess

subprocess.Popen(['pip', 'install', '--index-url https://m.devpi.net/fschulze/dev', 'devpi-client==6.0.0dev3'])
# versus
subprocess.Popen(['pip', 'install', '--index-url', 'https://m.devpi.net/fschulze/dev', 'devpi-client==6.0.0dev3'])
```

So, we need to split `--index` and the argument.

My first attempt was to fix it here...

https://github.com/tox-dev/tox/blob/f17774fdd9fceea40564110bdeac7ce4b30ed677/src/tox/tox_env/python/req_file.py#L136-L161

But :-) - as it is never super easy, later on sort is applied on the list, and the order is messed up.

```
  45         def before_package_install(self) -> None:                                                                                    
  46             super().before_package_install()                                                                                         
  47             # install deps                                                                                                           
  48             requirements_file: RequirementsFile = self.conf["deps"]                                                                  
  49             breakpoint()                                                                                                             
  50             requirement_file_content = requirements_file.validate_and_expand()                                                       
  51  ->         requirement_file_content.sort()  # stable order dependencies                                                             
  52             with self._cache.compare(requirement_file_content, PythonRun.__name__, "deps") as (eq, old):                             
  53                 if not eq:                                                                                                           
  54                     # if new env, or additions only a simple install will do                                                         
  55                     missing: Set[str] = set() if old is None else set(old) - set(requirement_file_content)                           
  56                     if not missing:                                                                                                  
  57                         if requirement_file_content:                                                                                 
  58                             self.install_deps(requirement_file_content)                                                              
  59                     else:  # otherwise, no idea how to compute the diff, instead just start from scratch                             
  60                         logging.warning(f"recreate env because dependencies removed: {', '.join(str(i) for i in missing)}")          
  61                         raise Recreate                                                                                               
(Pdb++) requirement_file_content
['--index-url', 'https://m.devpi.net/fschulze/dev', 'devpi-client==6.0.0dev3']
```

So, if the sort will stay, we need to do the splitting after it.

Looks like here would be a good spot to do the split. (or later on in `LocalSubProcessExecuteInstance` - any way, before it gets passed to `Popen`).

https://github.com/tox-dev/tox/blob/356a56200f0cae45a0a6c955ed6d41273604e337/src/tox/tox_env/api.py#L233-L247

I will have to think about whether there are "legal" use cases when parts of the cmd have spaces, e.g. from the Python docs `Popen(["/usr/bin/git", "commit", "-m", "Fixes a bug."])`.

Maybe it would be a good idea to do only the split when the item starts with an element present in `ONE_ARG`...

My time's up for today.. @gaborbernat maybe you can share your thoughts on this before I continue.

**Comment by gaborbernat** [comment] 2021-04-02 10:03
I'm in process of rewriting the requirements file with the introduction of the installer which handles this correctly :-) so probably this will be fixed in the next few days... I managed to get the number of failing test down to 3 from 200.... so progress. Still need some cleanup but not far now.

**Comment by jugmac00** [comment] 2021-04-02 11:12
Oh wow, so I managed to pick exactly the wrong one of 134 open issues 😬😂

Sounds great. I wonder how many issues you will be able to close at once. Quite some are very related to working with deps.

I guess I better wait until you merge your branch.

**Closed** 2021-04-05 07:10 UTC
Labels: bug:normal
