### ISSUE TITLE
tox 3.10.0 breaks on AppVeyor

### ISSUE THREAD

**Issue by fschulze** [tox-dev/tox#1304] opened 2019-05-17 08:34 UTC
Since tox 3.10.0 our AppVeyor builds don't work anymore (3.11.0 also doesn't work).

See https://ci.appveyor.com/project/fschulze/devpi/builds/24614048/job/dpgxf6tibvmk3e98 with 3.10.0

```
C:\Python35\python -m pip install tox==3.10.0
Collecting tox==3.10.0
  Downloading https://files.pythonhosted.org/packages/28/9b/23a760e8cc10527bea10976fe43f27257fbafca306e4559930cae68a3ecf/tox-3.10.0-py2.py3-none-any.whl (75kB)
Collecting toml>=0.9.4 (from tox==3.10.0)
  Downloading https://files.pythonhosted.org/packages/a2/12/ced7105d2de62fa7c8fb5fce92cc4ce66b57c95fb875e9318dba7f8c5db0/toml-0.10.0-py2.py3-none-any.whl
Collecting py<2,>=1.4.17 (from tox==3.10.0)
  Downloading https://files.pythonhosted.org/packages/76/bc/394ad449851729244a97857ee14d7cba61ddb268dce3db538ba2f2ba1f0f/py-1.8.0-py2.py3-none-any.whl (83kB)
Collecting six<2,>=1.0.0 (from tox==3.10.0)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Requirement already satisfied: virtualenv>=14.0.0 in c:\python35\lib\site-packages (from tox==3.10.0) (15.0.1)
Collecting pluggy<1,>=0.3.0 (from tox==3.10.0)
  Downloading https://files.pythonhosted.org/packages/cc/e4/2003a5e4e445424602c8f06a436eeed9e78bcae4947128f64741c66c7216/pluggy-0.11.0-py2.py3-none-any.whl
Collecting setuptools>=30.0.0 (from tox==3.10.0)
  Downloading https://files.pythonhosted.org/packages/ec/51/f45cea425fd5cb0b0380f5b0f048ebc1da5b417e48d304838c02d6288a1e/setuptools-41.0.1-py2.py3-none-any.whl (575kB)
Collecting filelock<4,>=3.0.0 (from tox==3.10.0)
  Downloading https://files.pythonhosted.org/packages/d7/ca/3c74396a9ed8a4cfab5459800edeef9a1269591cb21f5a49bd71a49c5fa2/filelock-3.0.10-py3-none-any.whl
Installing collected packages: toml, py, six, pluggy, setuptools, filelock, tox
  Found existing installation: setuptools 28.8.0
    Uninstalling setuptools-28.8.0:
      Successfully uninstalled setuptools-28.8.0
  The scripts tox-quickstart.exe and tox.exe are installed in 'C:\Python35\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed filelock-3.0.10 pluggy-0.11.0 py-1.8.0 setuptools-41.0.1 six-1.12.0 toml-0.10.0 tox-3.10.0
You are using pip version 18.1, however version 19.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
cd "%PROJECT%"
C:\Python35\python -m tox --skip-missing-interpreters
GLOB sdist-make: C:\projects\devpi\common\setup.py
py27 create: C:\projects\devpi\common\.tox\py27
py27 installdeps: pytest, pytest-flake8
py27 inst: C:\projects\devpi\common\.tox\.tmp\package\1\devpi-common-3.3.3.dev0.zip
py27 installed: You are using pip version 8.1.1, however version 19.1.1 is available.,You should consider upgrading via the 'python -m pip install --upgrade pip' command.,atomicwrites==1.3.0,attrs==19.1.0,certifi==2019.3.9,chardet==3.0.4,colorama==0.4.1,configparser==3.7.4,devpi-common==3.3.3.dev0,entrypoints==0.3,enum34==1.1.6,flake8==3.7.7,funcsigs==1.0.2,functools32==3.2.3.post2,idna==2.8,mccabe==0.6.1,more-itertools==5.0.0,pathlib2==2.3.3,pluggy==0.11.0,py==1.8.0,pycodestyle==2.5.0,pyflakes==2.1.1,pytest==4.5.0,pytest-flake8==1.0.4,requests==2.22.0,scandir==1.10.0,six==1.12.0,typing==3.6.6,urllib3==1.25.2,wcwidth==0.1.7
py27 run-test-pre: PYTHONHASHSEED='333'
py27 run-test: commands[0] | py.test
============================= test session starts =============================
platform win32 -- Python 2.7.16, pytest-4.5.0, py-1.8.0, pluggy-0.11.0
cachedir: .tox\py27\.pytest_cache
rootdir: C:\projects\devpi\common, inifile: tox.ini
plugins: flake8-1.0.4
collected 20 items / 8 errors / 12 selected
=================================== ERRORS ====================================
__________________ ERROR collecting testing/test_archive.py ___________________
ImportError while importing test module 'C:\projects\devpi\common\testing\test_archive.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
testing\test_archive.py:1: in <module>
    from devpi_common.archive import Archive
E   ImportError: No module named devpi_common.archive
<snipped>
```

and https://ci.appveyor.com/project/fschulze/devpi/builds/24614189/job/i57kkxa8bc8pjdl9 with 3.9.0

```
C:\Python35\python -m pip install tox==3.9.0
Collecting tox==3.9.0
  Downloading https://files.pythonhosted.org/packages/13/94/df88fb647f5f3d7c5afdb6c05bb56417c8bbbd0db0202f71448a040bba95/tox-3.9.0-py2.py3-none-any.whl (73kB)
Requirement already satisfied: virtualenv>=1.11.2 in c:\python35\lib\site-packages (from tox==3.9.0) (15.0.1)
Collecting setuptools>=30.0.0 (from tox==3.9.0)
  Downloading https://files.pythonhosted.org/packages/ec/51/f45cea425fd5cb0b0380f5b0f048ebc1da5b417e48d304838c02d6288a1e/setuptools-41.0.1-py2.py3-none-any.whl (575kB)
Collecting filelock<4,>=3.0.0 (from tox==3.9.0)
  Downloading https://files.pythonhosted.org/packages/d7/ca/3c74396a9ed8a4cfab5459800edeef9a1269591cb21f5a49bd71a49c5fa2/filelock-3.0.10-py3-none-any.whl
Collecting pluggy<1,>=0.3.0 (from tox==3.9.0)
  Downloading https://files.pythonhosted.org/packages/cc/e4/2003a5e4e445424602c8f06a436eeed9e78bcae4947128f64741c66c7216/pluggy-0.11.0-py2.py3-none-any.whl
Collecting toml>=0.9.4 (from tox==3.9.0)
  Downloading https://files.pythonhosted.org/packages/a2/12/ced7105d2de62fa7c8fb5fce92cc4ce66b57c95fb875e9318dba7f8c5db0/toml-0.10.0-py2.py3-none-any.whl
Collecting six<2,>=1.0.0 (from tox==3.9.0)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting py<2,>=1.4.17 (from tox==3.9.0)
  Downloading https://files.pythonhosted.org/packages/76/bc/394ad449851729244a97857ee14d7cba61ddb268dce3db538ba2f2ba1f0f/py-1.8.0-py2.py3-none-any.whl (83kB)
Installing collected packages: setuptools, filelock, pluggy, toml, six, py, tox
  Found existing installation: setuptools 28.8.0
    Uninstalling setuptools-28.8.0:
      Successfully uninstalled setuptools-28.8.0
  The scripts tox-quickstart.exe and tox.exe are installed in 'C:\Python35\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed filelock-3.0.10 pluggy-0.11.0 py-1.8.0 setuptools-41.0.1 six-1.12.0 toml-0.10.0 tox-3.9.0
You are using pip version 18.1, however version 19.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
cd "%PROJECT%"
C:\Python35\python -m tox --skip-missing-interpreters
GLOB sdist-make: C:\projects\devpi\common\setup.py
py27 create: C:\projects\devpi\common\.tox\py27
py27 installdeps: pytest, pytest-flake8
py27 inst: C:\projects\devpi\common\.tox\.tmp\package\1\devpi-common-3.3.3.dev0.zip
py27 installed: DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.,atomicwrites==1.3.0,attrs==19.1.0,certifi==2019.3.9,chardet==3.0.4,colorama==0.4.1,configparser==3.7.4,devpi-common==3.3.3.dev0,entrypoints==0.3,enum34==1.1.6,flake8==3.7.7,funcsigs==1.0.2,functools32==3.2.3.post2,idna==2.8,mccabe==0.6.1,more-itertools==5.0.0,pathlib2==2.3.3,pluggy==0.11.0,py==1.8.0,pycodestyle==2.5.0,pyflakes==2.1.1,pytest==4.5.0,pytest-flake8==1.0.4,requests==2.22.0,scandir==1.10.0,six==1.12.0,typing==3.6.6,urllib3==1.25.2,wcwidth==0.1.7
py27 run-test-pre: PYTHONHASHSEED='41'
py27 run-test: commands[0] | py.test
============================= test session starts =============================
platform win32 -- Python 2.7.16, pytest-4.5.0, py-1.8.0, pluggy-0.11.0
cachedir: .tox\py27\.pytest_cache
rootdir: C:\projects\devpi\common, inifile: tox.ini
plugins: flake8-1.0.4
collected 195 items
setup.py .                                                               [  0%]
devpi_common\__init__.py .                                               [  1%]
devpi_common\archive.py .                                                [  1%]
devpi_common\metadata.py .                                               [  2%]
devpi_common\proc.py .                                                   [  2%]
<snipped>
```

**Comment by gaborbernat** [comment] 2019-05-17 08:54
Duplicate of https://github.com/tox-dev/tox/issues/1302

**Closed by gaborbernat** 2019-05-17 08:54 UTC
Labels: bug:normal
