### ISSUE TITLE
Support for phony environments

### ISSUE THREAD

**Issue by brechtm** [tox-dev/tox#427] opened 2016-12-19 11:25 UTC
Tox can also be [used as a make tool](https://blog.ionelmc.ro/2015/04/14/tox-tricks-and-patterns/). For example, I created targets/environments to build the documentation for my project (Sphinx), an stand-alone installer for Windows and a stand-alone Mac application.

The `envlist` value in `[tox]` in `tox.ini` allows specifying which environments should be executed when not specifying one manually. I only include the test environments in `envlist`. It would be nice if it were possible to define fake environments that simply execute a number of other (real) environments. This would also be useful for pure test environments.

**Comment by brechtm** [comment] 2016-12-19 11:42
Phony environments could be specified as follows:

```
[phony:docs]
envlist = test-docs, build-docs
```

On another note, for environments that do not really test anything (build docs, build installer), it is strange that the environment needs to be specified as `[testenv:build-something]`. Could another category of environments be introduced? For example `[target:build-something]` or `[buildenv:build-something]`. These environments could behave differently from test environments, but I'm not sure what would make sense. The default values could for `skip_install` and `usedevelop` could be set to `true` and `false`, respectively.

**Comment by obestwalter** [comment] 2016-12-20 20:57
Using tox as a pythonic make replacement seems to become more and more common and it surely is a good idea to think about how needs growing from that can better be accommodated.

Regarding your `.Phony` suggestion: this sounds like you are basically looking for https://github.com/tox-dev/tox/issues/238 where the idea is also to group environments. 

About your other point (having sections being named more fittingly for the tasks): I see your point, but I don't have an opioninion about this yet.

**Comment by funkyfuture** [comment] 2017-03-24 23:11
it would be useful to use this as a circuit breaker too, so the phony stops on the first failure of one of the envitonments.

**Comment by Pawamoy** [comment] 2017-03-25 12:51
I like to define "shortcuts" as well in my tox conf, like:

```ini
[testenv:check]
skip_install = true
commands = tox -e checksetup,checksafety,checkstyle,checkspell,checklink

[testenv:checksetup]
...
```

Also, I can't do:

```ini
[tox]
envlist = check,docs,test

[testenv:test]
commands = tox -e py27-django19,py34-django19
```

... because `py27-django19` and `py34-django19` are not defined in tox's `envlist`.

**Comment by gaborbernat** [comment] 2019-05-02 21:38
Duplicate of #647.

**Closed by gaborbernat** 2019-05-02 21:38 UTC
Labels: area:configuration, level:hard, needs:discussion
