### ISSUE TITLE
`AttributeError: 'dict' object has no attribute 'select'` on python 3.7

### ISSUE THREAD

**Issue by joaomcteixeira** [tox-dev/tox#2379] opened 2022-03-12 11:42 UTC
Hi everyone, Sorry if the issue is repeated.

`tox` is breaking on all github actions running python 3.7

here's one example, but I am receiving this on every project
https://github.com/joaomcteixeira/taurenmd/runs/5472039593?check_suite_focus=true

```
Run tox -e py37
  tox -e py37
  shell: /usr/bin/bash -l {0}
  env:
    CONDA_PKGS_DIR: /home/runner/conda_pkgs_dir
.tox create: /home/runner/work/taurenmd/taurenmd/.tox/.tox
ERROR: invocation failed (exit code 1), logfile: /home/runner/work/taurenmd/taurenmd/.tox/.tox/log/.tox-0.log
================================== log start ===================================
AttributeError: 'dict' object has no attribute 'select'

=================================== log end ====================================
ERROR: InvocationError for command /usr/share/miniconda/envs/test/bin/python -m virtualenv --no-download --python /usr/share/miniconda/envs/test/bin/python .tox (exited with code 1)
Error: Process completed with exit code [2](https://github.com/joaomcteixeira/taurenmd/runs/5472039593?check_suite_focus=true#step:5:2).
```

running on python 3.8 or 3.9 works without a problem.

Thanks and cheers,

**Comment by jugmac00** [comment] 2022-03-12 12:09
Please change the command to `tox -e py37 -rvv`.

FWIW `tox` works for me on py37:
https://github.com/jugmac00/flask-reuploaded/runs/5493631334?check_suite_focus=true

Could you please share your `tox.ini` and all installed plugins?

**Comment by joaomcteixeira** [comment] 2022-03-12 12:21
Maybe I am doing something wrong because I am having the same problem with all my projects. However, before everything was working.

I updated the command in the github actions -> https://github.com/joaomcteixeira/taurenmd/pull/60

The tox config for those actions here -> https://github.com/joaomcteixeira/taurenmd/blob/plots/tox.ini

Thanks

**Comment by jugmac00** [comment] 2022-03-12 12:30
Looking at https://github.com/joaomcteixeira/taurenmd/runs/5521760532?check_suite_focus=true
especially at line 7
```
could not satisfy requires PackageNotFoundError('tox-conda')
```
this does not look like to be an issue with tox.

**Comment by jugmac00** [comment] 2022-03-12 12:52
Having a look at the build history of your project, Python 3.7 started failing in January

First failing build:
https://github.com/joaomcteixeira/taurenmd/runs/5013161873?check_suite_focus=true

Last working build:
https://github.com/joaomcteixeira/taurenmd/runs/4815085018?check_suite_focus=true

Now the tedious part begins... what has changed since then?

When I have a look at the installed Python packages, the version of tox was in both cases 3.24.5, so I think we can rule out tox here.

Hm... looking again at the output of the build log...
```
[2342] /home/runner/work/taurenmd/taurenmd/.tox$ /usr/share/miniconda/envs/test/bin/python -m virtualenv --no-download --python /usr/share/miniconda/envs/test/bin/python .tox
AttributeError: 'dict' object has no attribute 'select'
```
Looks like the problem occurred when running virtualenv, right?

And at least there are two different virtualenv versions used in the mentioned builds.

So, this is the end for me.

You could try to reproduce the problem on your local pc.

Especially by running the above line and have a look whether this works. As I mentioned, I do not use conda, so I cannot provide any further help.

Usually I would close the issue here, but as @gaborbernat is also the maintainer of virtualenv, let's wait what he has to add.

**Comment by joaomcteixeira** [comment] 2022-03-12 13:10
Thanks a lot for your help. I will have a look at it, and any further help is always appreciated. The error happens for other projects where I don't use conda (private project, though). Many thanks,

**Comment by jugmac00** [comment] 2022-03-12 13:18
I can't reproduce the issue, but this change looks promising @gaborbernat 

https://github.com/pypa/virtualenv/commit/bb82a73b6dbf577874f6d4bfaf72d2a7f59dfffe

**Comment by jugmac00** [comment] 2022-03-12 13:23
This change looks promising: https://github.com/pypa/virtualenv/commit/bb82a73b6dbf577874f6d4bfaf72d2a7f59dfffe

@gaborbernat

**Comment by gaborbernat** [comment] 2022-03-18 12:25
This usually is tox being installed into a broken environment and its dependencies not being satisfied.

**Closed by gaborbernat** 2022-03-18 12:25 UTC
Labels: bug:normal
