### ISSUE TITLE
website SSL cert has expired

### ISSUE THREAD

**Issue by rdonkin** [tox-dev/tox#440] opened 2017-01-18 10:47 UTC
Warning from Chrome when visiting https://tox.readthedocs.io/en/latest/ - certificate expired in early Jan.

**Comment by RonnyPfannschmidt** [comment] 2017-01-18 13:05
i just checked, and its fine, please verify you are not the target of an attack, or the user of a incompetent antivirus software

**Comment by warsaw** [comment] 2017-01-18 14:45
On Jan 18, 2017, at 05:05 AM, Ronny Pfannschmidt wrote:

>i just checked, and its fine, please verify you are not the target of an
>attack, or the user of a incompetent antivirus software

Nope, I'm getting the same warning on testrun.org for both Chrome and FF.
They claim the testrun.org cert expired on Dec 31, 2016.  Maybe it missed a
Let's Encrypt renewal?

Issued To

Common Name (CN)	testrun.org
Organization (O)	<Not Part Of Certificate>
Organizational Unit (OU)	<Not Part Of Certificate>
Issued By

Common Name (CN)	Let's Encrypt Authority X3
Organization (O)	Let's Encrypt
Organizational Unit (OU)	<Not Part Of Certificate>
Validity Period

Issued On	Sunday, October 2, 2016 at 8:31:00 PM
Expires On	Saturday, December 31, 2016 at 7:31:00 PM
Fingerprints

SHA-256 Fingerprint	D1 4E 30 9B 2E AD 43 64 97 F3 FA 48 56 3A 3E 06
F8 EB 2C 15 92 44 06 10 12 7F 3B 2B 9E D4 84 DC
SHA-1 Fingerprint	A1 27 A9 11 6B 30 69 79 F2 C8 8A 33 4C C7 6B DD
11 7A 39 E8

**Comment by RonnyPfannschmidt** [comment] 2017-01-18 15:13
@warsaw the url in the issue is the redirect target which works on correctly set up rtd infrastructure

testrun.org is indeed ran out and not the current url

@hpk42 should testrun.org be fixed or ignored?

**Comment by hpk42** [comment] 2017-01-18 19:34
all tox urls should point to readthedocs, not testrun anymore.  Older versions will still point to the testrun one, i am afraid. 

The letsencrypt update mechanism doesn't currently work on that host (it's surprisingly fragile) and i'd prefer to not have to care for it.

**Comment by obestwalter** [comment] 2017-01-23 18:20
I get a valid cert on https://tox.readthedocs.io/en/latest/ - I also am correctly redirected, if I go to http://testrun.org/tox 

@hpk you might want to remove

> This site was used for an experimental Jenkins server. As of now it only hosts the "tox" documentation:
> 
>    http://testrun.org/tox

... from the startpage http://testrun.org - then I think we caught everything :)

I would close this then as invalid unless I am missing something.

**Comment by hpk42** [comment] 2017-01-26 12:05
done, no reference to testrun.org anymore. thanks @obestwalter for helping!

**Closed by hpk42** 2017-01-26 12:05 UTC
Labels: example-needed
