### ISSUE TITLE
.tox/py36/bin/python: No module named pip

### ISSUE THREAD

**Issue by BenRbtz** [tox-dev/tox#1016] opened 2018-09-24 15:01 UTC
OS: EC2 (Amazon Linux)

Pip list:
- pip (9.0.3)
- pluggy (0.7.1)
- py (1.6.0)
- setuptools (36.2.7)
- six (1.11.0)
- toml (0.9.6)
- tox (3.4.0)
- virtualenv (16.0.0)

Here's the tox.ini: 

> [tox]
> envlist =
>         py36
> 
> [testenv]
> deps =
>      pytest
>      pytest-mock
> commands =
>          pytest
> 

I'm having a problem when running tox with python3.6 but works fine with python 2.7. I get the following error when running tox: 

> GLOB sdist-make: /TestRepo/project/setup.py
> py36 create: /TestRepo/project/.tox/py36
> py36 installdeps: pytest, pytest-mock
> ERROR: invocation failed (exit code 1), logfile: /TestRepo/project/.tox/py36/log/py36-1.log
> ERROR: actionid: py36
> msg: getenv
> cmdargs: '/TestRepo/project/.tox/py36/bin/python -m pip install pytest pytest-mock'
> 
> /TestRepo/project/.tox/py36/bin/python: No module named pip
> 
> ERROR: could not install deps [pytest, pytest-mock]; v = InvocationError('/TestRepo/project/.tox/py36/bin/python -m pip install pytest pytest-mock (see /TestRepo/project/.tox/py36/log/py36-1.log)', 1)

Any help with be appreciated. Thanks in advance!

**Comment by obestwalter** [comment] 2018-09-25 09:32
Hi @BenRbtz, this means that your py36 interpreter has no pip installed.

> For Amazon Linux, pip is not installed, it will be neccessary:

> $ curl -O https://bootstrap.pypa.io/get-pip.py
> and
> $ python3 get-pip.py --user

-- https://gist.github.com/niranjv/f80fc1f488afc49845e2ff3d5df7f83b#gistcomment-2570550

**Comment by BenRbtz** [comment] 2018-09-25 09:55
Thanks for the reply and suggestion!

I tried what you recommend but it still yields the same error. I even ran the script to rebuild python then the get-pip script but to no avail.

**Comment by gaborbernat** [comment] 2018-09-25 10:50
@BenRbtz can you provide the content for ``tox -e py36 -vvvv``, thanks 👍

**Comment by BenRbtz** [comment] 2018-09-25 11:04
Sure thing :) 

 tox -e py36 -vvvv:
>   removing /usr/local/TestRepo/project/.tox/log
> using tox.ini: /usr/local/TestRepo/project/tox.ini
> using tox-3.4.0 from /usr/lib/python3.6/dist-packages/tox/__init__.py
> GLOB start: packaging
> GLOB sdist-make: /usr/local/TestRepo/project/setup.py
>   removing /usr/local/TestRepo/project/.tox/dist
>   /usr/local/TestRepo/project$ /usr/bin/python3.6 /usr/local/TestRepo/project/setup.py sdist --formats=zip --dist-dir /usr/local/TestRepo/project/.tox/dist >/usr/local/TestRepo/project/.tox/log/tox-0.log
> GLOB finish: packaging after 0.33 seconds
> copying new sdistfile to '/root/.tox/distshare/testName-0.0.0.zip'
> py36 start: getenv /usr/local/TestRepo/project/.tox/py36
> py36 cannot reuse: no previous config /usr/local/TestRepo/project/.tox/py36/.tox-config1
> py36 create: /usr/local/TestRepo/project/.tox/py36
>   removing /usr/local/TestRepo/project/.tox/py36
> setting PATH=/usr/local/TestRepo/project/.tox/py36/bin:/opt/phpbrew/php/php-7.2.1/bin:/root/.phpbrew/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/aws/bin:/root/bin
>   /usr/local/TestRepo/project/.tox$ /usr/bin/python3.6 -m virtualenv --python /usr/bin/python3.6 py36 >/usr/local/TestRepo/project/.tox/py36/log/py36-0.log
> py36 installdeps: pytest, pytest-mock
> setting PATH=/usr/local/TestRepo/project/.tox/py36/bin:/opt/phpbrew/php/php-7.2.1/bin:/root/.phpbrew/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/aws/bin:/root/bin
>   /usr/local/TestRepo/project$ /usr/local/TestRepo/project/.tox/py36/bin/python -m pip install pytest pytest-mock
> /usr/local/TestRepo/project/.tox/py36/bin/python: No module named pip
> ERROR: could not install deps [pytest, pytest-mock]; v = InvocationError("'/usr/local/TestRepo/project/.tox/py36/bin/python -m pip install pytest pytest-mock'", 1)
> py36 finish: getenv after 2.88 seconds
> __________________________________________________________________________________________________________________ summary __________________________________________________________________________________________________________________
> ERROR:   py36: could not install deps [pytest, pytest-mock]; v = InvocationError("'/usr/local/TestRepo/project/.tox/py36/bin/python -m pip install pytest pytest-mock'", 1)

**Comment by gaborbernat** [comment] 2018-09-25 12:06
seems the problem is that the virtual environment we create does not have pip inside it. virtualenv should ensure this, ``/usr/bin/python3.6 -m virtualenv --python /usr/bin/python3.6 `` something goes wrong here. Can you try to run only that command perhaps with some verbose flags and see what happens? Also do a pip freeze as /usr/bin/python3.6 -m pip and the same with the created venv (perhaps also after tox fails).

**Comment by BenRbtz** [comment] 2018-09-25 12:16
/usr/bin/python3.6 -m pip freeze
> pluggy==0.7.1
> py==1.6.0
> six==1.11.0
> toml==0.9.6
> tox==3.4.0
> virtualenv==16.0.0
> You are using pip version 9.0.1, however version 18.0 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by gaborbernat** [comment] 2018-09-25 14:51
So you're saying it works if you use the command directly, but fails from within tox. 🤔 ?

**Comment by BenRbtz** [comment] 2018-09-25 15:43
I just double check and yes, it's as you said :(

**Comment by gaborbernat** [comment] 2018-09-25 16:03
Can you check output of pip list --user and pip list --local of the pip command respectively?

**Comment by BenRbtz** [comment] 2018-09-26 13:57
pip list --local

> Package    Version
> ---------- -------
> pip        18.0
> pluggy     0.7.1
> py         1.6.0
> setuptools 40.4.3
> six        1.11.0
> toml       0.9.6
> tox        3.4.0
> virtualenv 16.0.0
> wheel      0.31.1

pip list --user

> Package Version
> ------- -------
> pip     18.0
> wheel   0.31.1

**Comment by jsfehler** [comment] 2018-10-25 17:38
@BenRbtz @gaborbernat I've been having the exact same issues running tox on EC2 Amazon Linux, using python36 installed via yum.

The only thing that worked was uninstalling python36 and instead installing pyenv and managing the python installation from there.

**Comment by obestwalter** [comment] 2018-11-02 15:39
Hi @jsfehler, I just tried to reproduce this with a fresh ec2 instance. If I say `yum install python3` it installs python 3.7 and I can't find a way to install 3.6 via yum. Could you explain how you did that?

**Comment by jsfehler** [comment] 2018-11-02 15:42
@obestwalter I believe it was just `sudo yum install python36`

**Comment by obestwalter** [comment] 2018-11-02 15:44
Tried that - no luck. Seems like `pyenv` seems a good way to go to get Python36 on an Amazon Linux.

**Comment by obestwalter** [comment] 2018-11-02 15:58
As I can't reproduce this. I'll close this now as a highly specific corner case that is not even seem to be reproducible anymore. I tried playing this through with the Python 3.7 that now ssems to shp with current versions of Amazon Linux and all is working as expected.

```console
[root@ip-172-31-27-41 ~]# python3 -m venv toxtest
[root@ip-172-31-27-41 ~]# source toxtest/bin/activate
(toxtest) [root@ip-172-31-27-41 ~]# pip install tox
[...]
```

tox.ini:

```ini
[tox]
skipsdist = True
envlist = py37

[testenv]
skip_install = True
deps = pytest
commands = pytest --version
```

```console
(toxbase) [root@ip-172-31-27-41 ~]# tox
py37 create: /root/.tox/py37
py37 installdeps: pytest
py37 installed: atomicwrites==1.2.1,attrs==18.2.0,more-itertools==4.3.0,pluggy==0.8.0,py==1.7.0,pytest==3.9.3,six==1.11.0
py37 run-test-pre: PYTHONHASHSEED='4020926433'
py37 runtests: commands[0] | pytest --version
This is pytest version 3.9.3, imported from /root/.tox/py37/lib/python3.7/site-packages/pytest.py
______________________________ summary _________________________________
  py37: commands succeeded
  congratulations :)
```

So at least with the shipped Python3 all seems to be well.

To repeat the suggestion above: if you have a system that shows weird behaviour regarding packaging tools and you need a specific Python version, you might be well served by using [pyenv](https://github.com/pyenv/pyenv). `pyenv` compiles pretty much all Python versions for you (no root permissions necessary) and makes them available in (in the way the creators intended - e.g. coming with a packaged venv in the case of all modern Python versions).

**Closed by obestwalter** 2018-11-02 15:58 UTC
Labels: type:question :grey_question:
