### ISSUE TITLE
Problems with path relativization in commands section

### ISSUE THREAD

**Issue by i386x** [tox-dev/tox#1463] opened 2019-11-21 19:44 UTC
Hello,

the [shortening absolute path to relative ones](https://github.com/tox-dev/tox/commit/43d65b17#diff-57c0f90ac19d5a79d6495ab22fab6539R247-R248) may [break](https://travis-ci.com/linux-system-roles/network/jobs/258652534#L268-L272) some use cases when for example `{envpython}` is [passed](https://github.com/linux-system-roles/network/blob/670b48f006a011c28feb59891b6d8e0ab91beb5f/tox.ini#L244) to [shell script](https://github.com/linux-system-roles/network/blob/670b48f006a011c28feb59891b6d8e0ab91beb5f/.travis/custom.sh). I don't know whether this should be considered as a bug or not but at least it should be mentioned [here](https://tox.readthedocs.io/en/latest/config.html#conf-commands).

**Comment by pcahyna** [comment] 2019-11-25 12:26
IIUC the issue is, when there is a complex command containing some `cd ... &&`, replacing absolute paths by relative everywhere in the command does no longer work as expected (after the `cd`).

**Comment by gaborbernat** [comment] 2020-04-19 08:58
Feel free to open a PR against master and fix it. My available efforts at the moment are aimed at fixing this as part of https://github.com/tox-dev/tox/issues/1394, but that probably will take a while (ETA September).

**Comment by jayvdb** [comment] 2020-10-20 07:59
@i386x does https://github.com/tox-dev/tox/issues/1339 explain your problem?

If it is different, perhaps you could provide a sample `tox.ini` to help diagnose the problem.

**Comment by i386x** [comment] 2020-10-20 11:51
Yes, #1339 is the same problem.

**Comment by gaborbernat** [comment] 2021-03-01 18:51
This is now fixed on the rewrite branch.

**Closed by gaborbernat** 2021-03-01 18:51 UTC
Labels: bug:normal, help:wanted
