### ISSUE TITLE
Expose virtualenv --no-download somewhere in tox ini

### ISSUE THREAD

**Issue by rogalski** [tox-dev/tox#497] opened 2017-03-28 06:33 UTC
I work in environment where local PyPI mirror is used. I set non-standard index server in [tox] section of tox.ini file and it works fine when existing virtualenv is reused. When _new_ virtualenv is created, it still attempts to connect to standard PyPI server (see [`create_environment`](https://github.com/pypa/virtualenv/blob/master/virtualenv.py#L907) and [`install_wheel`](https://github.com/pypa/virtualenv/blob/master/virtualenv.py#L834) functions). It spends long time there and eventually get timed out. While virtualenv is still created successfully, long timeout is certainly unexpected behavior.

It could either be done explicitly (something along the lines of `virtualenv_custom_args` [text], `virtualenv_no_download` [bool] option), or maybe implicitly (add --no-download when custom index server is defined)

I'd like to get some input before I'll start to work on a PR.

**Comment by obestwalter** [comment] 2017-03-28 09:27
@rogalski - interesting. I have the same set up at work and have never noticed that problem. Maybe this is because I have set my `pip.conf` like this?

    [global]
    index-url = https://pypi.python.org/simple/
    extra-index-url = <company devpi server>

I did that ages ago, before we actually had added the company index to the tox inis, so I will have try this out, how tox behaves with that extra hint for pip.

**Comment by rogalski** [comment] 2017-03-28 11:26
Using code below in tox.ini seems to do the job:
```
setenv = 
             VIRTUALENV_DOWNLOAD=0
```

**Comment by asottile** [comment] 2017-03-30 14:32
Duplicates #446 I believe?

**Comment by obestwalter** [comment] 2017-04-01 10:56
@asottile I think you wanted to type something else (#446 is about running Travis on Mac), which issue did you mean?

**Comment by asottile** [comment] 2017-04-01 12:10
Indeed #448 is the one I was thinking of

**Comment by rogalski** [comment] 2017-04-01 12:29
Any extra actions required on my side for removing an `incomplete` tag?

**Comment by obestwalter** [comment] 2017-04-01 13:53
So if I understand it correctly this is indeed a dupe of #448, so I'd say we close this and the discussion how to improve the situation can be followed up there ...

**Closed by obestwalter** 2017-04-01 13:53 UTC
Labels: bug, incomplete

**Comment by asottile** [comment] 2017-04-29 21:08
I made a plugin to turn virtualenv's behaviour off entirely: https://github.com/asottile/tox-virtualenv-no-download
