### ISSUE TITLE
Tox 4 fails to parse a `tox.ini` with a testenv named `flake8` and a config section named `flake8`

### ISSUE THREAD

**Issue by whyscream** [tox-dev/tox#2686] opened 2022-12-12 14:44 UTC
## Issue

Tox runs the wrong install and test commands when an equally named (?) section is available in `tox.ini`.

Python linter `flake8` supports configuration by adding a `[flake8]` section to `tox.ini`. We have a `[testenv:flake8]` in tox.ini that runs the flake8 test within tox. Under tox3, this setup worked fine for us, but as of tox 4, the flake8 test fails: dependencies are not installed and the wrong test command is executed. 

A minimal failing `tox.ini`:
```ini
[tox]
envlist =
    python3.10, flake8

[flake8]
extend-ignore = E501,W503

[testenv]
basepython = python3.10
deps =
    pytest
commands = pytest

[testenv:flake8]
deps =
    flake8
commands = flake8 -v hello.py
```
When running `tox -e flake8`, tox installs `pytest` as deps, and runs `pytest` as test command. I can resolve this in several ways:
- moving the `[flake8]` section in tox.ini towards the end of the config file (below the `[testenv:flake8]` entry).
- moving the flake config to a whole separate file (e.g, `.flake8`)

I have no idea whether configuring `flake8` within `tox.ini` was ever a supported idea from the side of tox. I'd prefer a separate config file like `.flake8` (or `pyproject.toml` /  `setup.cfg` as being generic by definition), but I ran into this on an inherited setup.

## Environment

Provide at least:

- OS: ubuntu 20.04, Python 3.10
- `pip list` of the host Python where `tox` is installed:
```console
Package       Version
------------- -------
cachetools    5.2.0
chardet       5.1.0
colorama      0.4.6
distlib       0.3.6
filelock      3.8.2
packaging     22.0
pip           22.3.1
platformdirs  2.6.0
pluggy        1.0.0
pyproject_api 1.2.1
setuptools    65.6.3
tomli         2.0.1
tox           4.0.8
virtualenv    20.17.1
wheel         0.38.4
```

## Output of running tox

Provide the output of `tox -rvv`:

```console
$ tox -rvv
python3.10: 145 W remove tox env folder /home/tom/code/tox-test/.tox/python3.10 [tox/tox_env/api.py:302]
python3.10: 184 I find interpreter for spec PythonSpec(major=3, minor=10) [virtualenv/discovery/builtin.py:56]
python3.10: 184 D discover exe for PythonInfo(spec=CPython3.10.8.final.0-64, exe=/home/tom/code/wagtail-helpdesk/env/bin/python3.10, platform=linux, version='3.10.8 (main, Oct 12 2022, 19:14:26) [GCC 9.4.0]', encoding_fs_io=utf-8-utf-8) in /usr [virtualenv/discovery/py_info.py:437]
python3.10: 185 D filesystem is case-sensitive [virtualenv/info.py:24]
python3.10: 185 D got python info of /usr/bin/python3.10 from /home/tom/.local/share/virtualenv/py_info/1/8a94588eda9d64d9e9a351ab8144e55b1fabf5113b54e67dd26a8c27df0381b3.json [virtualenv/app_data/via_disk_folder.py:129]
python3.10: 186 I proposed PythonInfo(spec=CPython3.10.8.final.0-64, system=/usr/bin/python3.10, exe=/home/tom/code/wagtail-helpdesk/env/bin/python3.10, platform=linux, version='3.10.8 (main, Oct 12 2022, 19:14:26) [GCC 9.4.0]', encoding_fs_io=utf-8-utf-8) [virtualenv/discovery/builtin.py:63]
python3.10: 186 D accepted PythonInfo(spec=CPython3.10.8.final.0-64, system=/usr/bin/python3.10, exe=/home/tom/code/wagtail-helpdesk/env/bin/python3.10, platform=linux, version='3.10.8 (main, Oct 12 2022, 19:14:26) [GCC 9.4.0]', encoding_fs_io=utf-8-utf-8) [virtualenv/discovery/builtin.py:65]
python3.10: 212 I create virtual environment via CPython3Posix(dest=/home/tom/code/tox-test/.tox/python3.10, clear=False, no_vcs_ignore=False, global=False) [virtualenv/run/session.py:48]
python3.10: 212 D create folder /home/tom/code/tox-test/.tox/python3.10/bin [virtualenv/util/path/_sync.py:9]
python3.10: 213 D create folder /home/tom/code/tox-test/.tox/python3.10/lib/python3.10/site-packages [virtualenv/util/path/_sync.py:9]
python3.10: 213 D write /home/tom/code/tox-test/.tox/python3.10/pyvenv.cfg [virtualenv/create/pyenv_cfg.py:30]
python3.10: 213 D 	home = /usr/bin [virtualenv/create/pyenv_cfg.py:34]
python3.10: 213 D 	implementation = CPython [virtualenv/create/pyenv_cfg.py:34]
python3.10: 213 D 	version_info = 3.10.8.final.0 [virtualenv/create/pyenv_cfg.py:34]
python3.10: 213 D 	virtualenv = 20.17.1 [virtualenv/create/pyenv_cfg.py:34]
python3.10: 213 D 	include-system-site-packages = false [virtualenv/create/pyenv_cfg.py:34]
python3.10: 213 D 	base-prefix = /usr [virtualenv/create/pyenv_cfg.py:34]
python3.10: 213 D 	base-exec-prefix = /usr [virtualenv/create/pyenv_cfg.py:34]
python3.10: 213 D 	base-executable = /usr/bin/python3.10 [virtualenv/create/pyenv_cfg.py:34]
python3.10: 213 D symlink /usr/bin/python3.10 to /home/tom/code/tox-test/.tox/python3.10/bin/python [virtualenv/util/path/_sync.py:28]
python3.10: 214 D create virtualenv import hook file /home/tom/code/tox-test/.tox/python3.10/lib/python3.10/site-packages/_virtualenv.pth [virtualenv/create/via_global_ref/api.py:89]
python3.10: 214 D create /home/tom/code/tox-test/.tox/python3.10/lib/python3.10/site-packages/_virtualenv.py [virtualenv/create/via_global_ref/api.py:92]
python3.10: 214 D ============================== target debug ============================== [virtualenv/run/session.py:50]
python3.10: 214 D debug via /home/tom/code/tox-test/.tox/python3.10/bin/python /home/tom/code/wagtail-helpdesk/env/lib/python3.10/site-packages/virtualenv/create/debug.py [virtualenv/create/creator.py:197]
python3.10: 214 D {
  "sys": {
    "executable": "/home/tom/code/tox-test/.tox/python3.10/bin/python",
    "_base_executable": "/home/tom/code/tox-test/.tox/python3.10/bin/python",
    "prefix": "/home/tom/code/tox-test/.tox/python3.10",
    "base_prefix": "/usr",
    "real_prefix": null,
    "exec_prefix": "/home/tom/code/tox-test/.tox/python3.10",
    "base_exec_prefix": "/usr",
    "path": [
      "/usr/lib/python310.zip",
      "/usr/lib/python3.10",
      "/usr/lib/python3.10/lib-dynload",
      "/home/tom/code/tox-test/.tox/python3.10/lib/python3.10/site-packages"
    ],
    "meta_path": [
      "<class '_virtualenv._Finder'>",
      "<class '_frozen_importlib.BuiltinImporter'>",
      "<class '_frozen_importlib.FrozenImporter'>",
      "<class '_frozen_importlib_external.PathFinder'>"
    ],
    "fs_encoding": "utf-8",
    "io_encoding": "utf-8"
  },
  "version": "3.10.8 (main, Oct 12 2022, 19:14:26) [GCC 9.4.0]",
  "makefile_filename": "/usr/lib/python3.10/config-3.10-x86_64-linux-gnu/Makefile",
  "os": "<module 'os' from '/usr/lib/python3.10/os.py'>",
  "site": "<module 'site' from '/usr/lib/python3.10/site.py'>",
  "datetime": "<module 'datetime' from '/usr/lib/python3.10/datetime.py'>",
  "math": "<module 'math' (built-in)>",
  "json": "<module 'json' from '/usr/lib/python3.10/json/__init__.py'>"
} [virtualenv/run/session.py:51]
python3.10: 248 I add seed packages via FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/tom/.local/share/virtualenv) [virtualenv/run/session.py:55]
python3.10: 251 D got embed update of distribution setuptools from /home/tom/.local/share/virtualenv/wheel/3.10/embed/3/setuptools.json [virtualenv/app_data/via_disk_folder.py:129]
python3.10: 252 D got embed update of distribution pip from /home/tom/.local/share/virtualenv/wheel/3.10/embed/3/pip.json [virtualenv/app_data/via_disk_folder.py:129]
python3.10: 252 D got embed update of distribution wheel from /home/tom/.local/share/virtualenv/wheel/3.10/embed/3/wheel.json [virtualenv/app_data/via_disk_folder.py:129]
python3.10: 256 D install setuptools from wheel /home/tom/code/wagtail-helpdesk/env/lib/python3.10/site-packages/virtualenv/seed/wheels/embed/setuptools-65.6.3-py3-none-any.whl via CopyPipInstall [virtualenv/seed/embed/via_app_data/via_app_data.py:47]
python3.10: 256 D install pip from wheel /home/tom/code/wagtail-helpdesk/env/lib/python3.10/site-packages/virtualenv/seed/wheels/embed/pip-22.3.1-py3-none-any.whl via CopyPipInstall [virtualenv/seed/embed/via_app_data/via_app_data.py:47]
python3.10: 256 D install wheel from wheel /home/tom/code/wagtail-helpdesk/env/lib/python3.10/site-packages/virtualenv/seed/wheels/embed/wheel-0.38.4-py3-none-any.whl via CopyPipInstall [virtualenv/seed/embed/via_app_data/via_app_data.py:47]
python3.10: 257 D copy directory /home/tom/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/pip-22.3.1-py3-none-any/pip to /home/tom/code/tox-test/.tox/python3.10/lib/python3.10/site-packages/pip [virtualenv/util/path/_sync.py:36]
python3.10: 257 D copy /home/tom/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/setuptools-65.6.3-py3-none-any/distutils-precedence.pth to /home/tom/code/tox-test/.tox/python3.10/lib/python3.10/site-packages/distutils-precedence.pth [virtualenv/util/path/_sync.py:36]
python3.10: 257 D copy directory /home/tom/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/wheel-0.38.4-py3-none-any/wheel to /home/tom/code/tox-test/.tox/python3.10/lib/python3.10/site-packages/wheel [virtualenv/util/path/_sync.py:36]
python3.10: 258 D copy directory /home/tom/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/setuptools-65.6.3-py3-none-any/setuptools to /home/tom/code/tox-test/.tox/python3.10/lib/python3.10/site-packages/setuptools [virtualenv/util/path/_sync.py:36]
python3.10: 262 D copy /home/tom/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/wheel-0.38.4-py3-none-any/wheel-0.38.4.virtualenv to /home/tom/code/tox-test/.tox/python3.10/lib/python3.10/site-packages/wheel-0.38.4.virtualenv [virtualenv/util/path/_sync.py:36]
python3.10: 262 D copy directory /home/tom/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/wheel-0.38.4-py3-none-any/wheel-0.38.4.dist-info to /home/tom/code/tox-test/.tox/python3.10/lib/python3.10/site-packages/wheel-0.38.4.dist-info [virtualenv/util/path/_sync.py:36]
python3.10: 265 D generated console scripts wheel3 wheel wheel3.10 wheel-3.10 [virtualenv/seed/embed/via_app_data/pip_install/base.py:41]
python3.10: 288 D copy directory /home/tom/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/setuptools-65.6.3-py3-none-any/_distutils_hack to /home/tom/code/tox-test/.tox/python3.10/lib/python3.10/site-packages/_distutils_hack [virtualenv/util/path/_sync.py:36]
python3.10: 288 D copy /home/tom/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/setuptools-65.6.3-py3-none-any/setuptools-65.6.3.virtualenv to /home/tom/code/tox-test/.tox/python3.10/lib/python3.10/site-packages/setuptools-65.6.3.virtualenv [virtualenv/util/path/_sync.py:36]
python3.10: 289 D copy directory /home/tom/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/setuptools-65.6.3-py3-none-any/pkg_resources to /home/tom/code/tox-test/.tox/python3.10/lib/python3.10/site-packages/pkg_resources [virtualenv/util/path/_sync.py:36]
python3.10: 296 D copy directory /home/tom/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/setuptools-65.6.3-py3-none-any/setuptools-65.6.3.dist-info to /home/tom/code/tox-test/.tox/python3.10/lib/python3.10/site-packages/setuptools-65.6.3.dist-info [virtualenv/util/path/_sync.py:36]
python3.10: 297 D generated console scripts  [virtualenv/seed/embed/via_app_data/pip_install/base.py:41]
python3.10: 313 D copy /home/tom/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/pip-22.3.1-py3-none-any/pip-22.3.1.virtualenv to /home/tom/code/tox-test/.tox/python3.10/lib/python3.10/site-packages/pip-22.3.1.virtualenv [virtualenv/util/path/_sync.py:36]
python3.10: 314 D copy directory /home/tom/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/pip-22.3.1-py3-none-any/pip-22.3.1.dist-info to /home/tom/code/tox-test/.tox/python3.10/lib/python3.10/site-packages/pip-22.3.1.dist-info [virtualenv/util/path/_sync.py:36]
python3.10: 315 D generated console scripts pip3.10 pip-3.10 pip pip3 [virtualenv/seed/embed/via_app_data/pip_install/base.py:41]
python3.10: 315 I add activators for Bash, CShell, Fish, Nushell, PowerShell, Python [virtualenv/run/session.py:61]
python3.10: 317 D write /home/tom/code/tox-test/.tox/python3.10/pyvenv.cfg [virtualenv/create/pyenv_cfg.py:30]
python3.10: 317 D 	home = /usr/bin [virtualenv/create/pyenv_cfg.py:34]
python3.10: 317 D 	implementation = CPython [virtualenv/create/pyenv_cfg.py:34]
python3.10: 317 D 	version_info = 3.10.8.final.0 [virtualenv/create/pyenv_cfg.py:34]
python3.10: 317 D 	virtualenv = 20.17.1 [virtualenv/create/pyenv_cfg.py:34]
python3.10: 317 D 	include-system-site-packages = false [virtualenv/create/pyenv_cfg.py:34]
python3.10: 317 D 	base-prefix = /usr [virtualenv/create/pyenv_cfg.py:34]
python3.10: 317 D 	base-exec-prefix = /usr [virtualenv/create/pyenv_cfg.py:34]
python3.10: 317 D 	base-executable = /usr/bin/python3.10 [virtualenv/create/pyenv_cfg.py:34]
python3.10: 319 W install_deps> python -I -m pip install pytest [tox/tox_env/api.py:408]
Collecting pytest
  Using cached pytest-7.2.0-py3-none-any.whl (316 kB)
Collecting packaging
  Using cached packaging-22.0-py3-none-any.whl (42 kB)
Collecting pluggy<2.0,>=0.12
  Using cached pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Collecting tomli>=1.0.0
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting attrs>=19.2.0
  Using cached attrs-22.1.0-py2.py3-none-any.whl (58 kB)
Collecting iniconfig
  Using cached iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Collecting exceptiongroup>=1.0.0rc8
  Using cached exceptiongroup-1.0.4-py3-none-any.whl (14 kB)
Installing collected packages: iniconfig, tomli, pluggy, packaging, exceptiongroup, attrs, pytest
Successfully installed attrs-22.1.0 exceptiongroup-1.0.4 iniconfig-1.1.1 packaging-22.0 pluggy-1.0.0 pytest-7.2.0 tomli-2.0.1
python3.10: 2042 I exit 0 (1.72 seconds) /home/tom/code/tox-test> python -I -m pip install pytest pid=660839 [tox/execute/api.py:275]
python3.10: 2043 W commands[0]> pytest [tox/tox_env/api.py:408]
========================================================== test session starts ==========================================================
platform linux -- Python 3.10.8, pytest-7.2.0, pluggy-1.0.0
cachedir: .tox/python3.10/.pytest_cache
rootdir: /home/tom/code/tox-test
collected 1 item

test_hello.py .                                                                                                                   [100%]

=========================================================== 1 passed in 0.00s ===========================================================
python3.10: 2240 I exit 0 (0.20 seconds) /home/tom/code/tox-test> pytest pid=660879 [tox/execute/api.py:275]
python3.10: OK ✔ in 2.1 seconds
flake8: 2240 W remove tox env folder /home/tom/code/tox-test/.tox/flake8 [tox/tox_env/api.py:302]
flake8: 2272 I find interpreter for spec PythonSpec(major=3, minor=10) [virtualenv/discovery/builtin.py:56]
flake8: 2272 I proposed PythonInfo(spec=CPython3.10.8.final.0-64, system=/usr/bin/python3.10, exe=/home/tom/code/wagtail-helpdesk/env/bin/python3.10, platform=linux, version='3.10.8 (main, Oct 12 2022, 19:14:26) [GCC 9.4.0]', encoding_fs_io=utf-8-utf-8) [virtualenv/discovery/builtin.py:63]
flake8: 2272 D accepted PythonInfo(spec=CPython3.10.8.final.0-64, system=/usr/bin/python3.10, exe=/home/tom/code/wagtail-helpdesk/env/bin/python3.10, platform=linux, version='3.10.8 (main, Oct 12 2022, 19:14:26) [GCC 9.4.0]', encoding_fs_io=utf-8-utf-8) [virtualenv/discovery/builtin.py:65]
flake8: 2273 I create virtual environment via CPython3Posix(dest=/home/tom/code/tox-test/.tox/flake8, clear=False, no_vcs_ignore=False, global=False) [virtualenv/run/session.py:48]
flake8: 2273 D create folder /home/tom/code/tox-test/.tox/flake8/bin [virtualenv/util/path/_sync.py:9]
flake8: 2273 D create folder /home/tom/code/tox-test/.tox/flake8/lib/python3.10/site-packages [virtualenv/util/path/_sync.py:9]
flake8: 2273 D write /home/tom/code/tox-test/.tox/flake8/pyvenv.cfg [virtualenv/create/pyenv_cfg.py:30]
flake8: 2274 D 	home = /usr/bin [virtualenv/create/pyenv_cfg.py:34]
flake8: 2274 D 	implementation = CPython [virtualenv/create/pyenv_cfg.py:34]
flake8: 2274 D 	version_info = 3.10.8.final.0 [virtualenv/create/pyenv_cfg.py:34]
flake8: 2274 D 	virtualenv = 20.17.1 [virtualenv/create/pyenv_cfg.py:34]
flake8: 2274 D 	include-system-site-packages = false [virtualenv/create/pyenv_cfg.py:34]
flake8: 2274 D 	base-prefix = /usr [virtualenv/create/pyenv_cfg.py:34]
flake8: 2274 D 	base-exec-prefix = /usr [virtualenv/create/pyenv_cfg.py:34]
flake8: 2274 D 	base-executable = /usr/bin/python3.10 [virtualenv/create/pyenv_cfg.py:34]
flake8: 2274 D symlink /usr/bin/python3.10 to /home/tom/code/tox-test/.tox/flake8/bin/python [virtualenv/util/path/_sync.py:28]
flake8: 2274 D create virtualenv import hook file /home/tom/code/tox-test/.tox/flake8/lib/python3.10/site-packages/_virtualenv.pth [virtualenv/create/via_global_ref/api.py:89]
flake8: 2275 D create /home/tom/code/tox-test/.tox/flake8/lib/python3.10/site-packages/_virtualenv.py [virtualenv/create/via_global_ref/api.py:92]
flake8: 2275 D ============================== target debug ============================== [virtualenv/run/session.py:50]
flake8: 2275 D debug via /home/tom/code/tox-test/.tox/flake8/bin/python /home/tom/code/wagtail-helpdesk/env/lib/python3.10/site-packages/virtualenv/create/debug.py [virtualenv/create/creator.py:197]
flake8: 2275 D {
  "sys": {
    "executable": "/home/tom/code/tox-test/.tox/flake8/bin/python",
    "_base_executable": "/home/tom/code/tox-test/.tox/flake8/bin/python",
    "prefix": "/home/tom/code/tox-test/.tox/flake8",
    "base_prefix": "/usr",
    "real_prefix": null,
    "exec_prefix": "/home/tom/code/tox-test/.tox/flake8",
    "base_exec_prefix": "/usr",
    "path": [
      "/usr/lib/python310.zip",
      "/usr/lib/python3.10",
      "/usr/lib/python3.10/lib-dynload",
      "/home/tom/code/tox-test/.tox/flake8/lib/python3.10/site-packages"
    ],
    "meta_path": [
      "<class '_virtualenv._Finder'>",
      "<class '_frozen_importlib.BuiltinImporter'>",
      "<class '_frozen_importlib.FrozenImporter'>",
      "<class '_frozen_importlib_external.PathFinder'>"
    ],
    "fs_encoding": "utf-8",
    "io_encoding": "utf-8"
  },
  "version": "3.10.8 (main, Oct 12 2022, 19:14:26) [GCC 9.4.0]",
  "makefile_filename": "/usr/lib/python3.10/config-3.10-x86_64-linux-gnu/Makefile",
  "os": "<module 'os' from '/usr/lib/python3.10/os.py'>",
  "site": "<module 'site' from '/usr/lib/python3.10/site.py'>",
  "datetime": "<module 'datetime' from '/usr/lib/python3.10/datetime.py'>",
  "math": "<module 'math' (built-in)>",
  "json": "<module 'json' from '/usr/lib/python3.10/json/__init__.py'>"
} [virtualenv/run/session.py:51]
flake8: 2301 I add seed packages via FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/tom/.local/share/virtualenv) [virtualenv/run/session.py:55]
flake8: 2303 D got embed update of distribution pip from /home/tom/.local/share/virtualenv/wheel/3.10/embed/3/pip.json [virtualenv/app_data/via_disk_folder.py:129]
flake8: 2303 D got embed update of distribution setuptools from /home/tom/.local/share/virtualenv/wheel/3.10/embed/3/setuptools.json [virtualenv/app_data/via_disk_folder.py:129]
flake8: 2304 D got embed update of distribution wheel from /home/tom/.local/share/virtualenv/wheel/3.10/embed/3/wheel.json [virtualenv/app_data/via_disk_folder.py:129]
flake8: 2304 D install pip from wheel /home/tom/code/wagtail-helpdesk/env/lib/python3.10/site-packages/virtualenv/seed/wheels/embed/pip-22.3.1-py3-none-any.whl via CopyPipInstall [virtualenv/seed/embed/via_app_data/via_app_data.py:47]
flake8: 2304 D install setuptools from wheel /home/tom/code/wagtail-helpdesk/env/lib/python3.10/site-packages/virtualenv/seed/wheels/embed/setuptools-65.6.3-py3-none-any.whl via CopyPipInstall [virtualenv/seed/embed/via_app_data/via_app_data.py:47]
flake8: 2304 D install wheel from wheel /home/tom/code/wagtail-helpdesk/env/lib/python3.10/site-packages/virtualenv/seed/wheels/embed/wheel-0.38.4-py3-none-any.whl via CopyPipInstall [virtualenv/seed/embed/via_app_data/via_app_data.py:47]
flake8: 2305 D copy /home/tom/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/setuptools-65.6.3-py3-none-any/distutils-precedence.pth to /home/tom/code/tox-test/.tox/flake8/lib/python3.10/site-packages/distutils-precedence.pth [virtualenv/util/path/_sync.py:36]
flake8: 2306 D copy directory /home/tom/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/wheel-0.38.4-py3-none-any/wheel to /home/tom/code/tox-test/.tox/flake8/lib/python3.10/site-packages/wheel [virtualenv/util/path/_sync.py:36]
flake8: 2306 D copy directory /home/tom/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/setuptools-65.6.3-py3-none-any/setuptools to /home/tom/code/tox-test/.tox/flake8/lib/python3.10/site-packages/setuptools [virtualenv/util/path/_sync.py:36]
flake8: 2306 D copy directory /home/tom/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/pip-22.3.1-py3-none-any/pip to /home/tom/code/tox-test/.tox/flake8/lib/python3.10/site-packages/pip [virtualenv/util/path/_sync.py:36]
flake8: 2312 D copy /home/tom/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/wheel-0.38.4-py3-none-any/wheel-0.38.4.virtualenv to /home/tom/code/tox-test/.tox/flake8/lib/python3.10/site-packages/wheel-0.38.4.virtualenv [virtualenv/util/path/_sync.py:36]
flake8: 2312 D copy directory /home/tom/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/wheel-0.38.4-py3-none-any/wheel-0.38.4.dist-info to /home/tom/code/tox-test/.tox/flake8/lib/python3.10/site-packages/wheel-0.38.4.dist-info [virtualenv/util/path/_sync.py:36]
flake8: 2316 D generated console scripts wheel3.10 wheel-3.10 wheel3 wheel [virtualenv/seed/embed/via_app_data/pip_install/base.py:41]
flake8: 2340 D copy directory /home/tom/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/setuptools-65.6.3-py3-none-any/_distutils_hack to /home/tom/code/tox-test/.tox/flake8/lib/python3.10/site-packages/_distutils_hack [virtualenv/util/path/_sync.py:36]
flake8: 2340 D copy /home/tom/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/setuptools-65.6.3-py3-none-any/setuptools-65.6.3.virtualenv to /home/tom/code/tox-test/.tox/flake8/lib/python3.10/site-packages/setuptools-65.6.3.virtualenv [virtualenv/util/path/_sync.py:36]
flake8: 2341 D copy directory /home/tom/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/setuptools-65.6.3-py3-none-any/pkg_resources to /home/tom/code/tox-test/.tox/flake8/lib/python3.10/site-packages/pkg_resources [virtualenv/util/path/_sync.py:36]
flake8: 2349 D copy directory /home/tom/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/setuptools-65.6.3-py3-none-any/setuptools-65.6.3.dist-info to /home/tom/code/tox-test/.tox/flake8/lib/python3.10/site-packages/setuptools-65.6.3.dist-info [virtualenv/util/path/_sync.py:36]
flake8: 2350 D generated console scripts  [virtualenv/seed/embed/via_app_data/pip_install/base.py:41]
flake8: 2375 D copy /home/tom/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/pip-22.3.1-py3-none-any/pip-22.3.1.virtualenv to /home/tom/code/tox-test/.tox/flake8/lib/python3.10/site-packages/pip-22.3.1.virtualenv [virtualenv/util/path/_sync.py:36]
flake8: 2375 D copy directory /home/tom/.local/share/virtualenv/wheel/3.10/image/1/CopyPipInstall/pip-22.3.1-py3-none-any/pip-22.3.1.dist-info to /home/tom/code/tox-test/.tox/flake8/lib/python3.10/site-packages/pip-22.3.1.dist-info [virtualenv/util/path/_sync.py:36]
flake8: 2376 D generated console scripts pip-3.10 pip pip3 pip3.10 [virtualenv/seed/embed/via_app_data/pip_install/base.py:41]
flake8: 2376 I add activators for Bash, CShell, Fish, Nushell, PowerShell, Python [virtualenv/run/session.py:61]
flake8: 2378 D write /home/tom/code/tox-test/.tox/flake8/pyvenv.cfg [virtualenv/create/pyenv_cfg.py:30]
flake8: 2378 D 	home = /usr/bin [virtualenv/create/pyenv_cfg.py:34]
flake8: 2378 D 	implementation = CPython [virtualenv/create/pyenv_cfg.py:34]
flake8: 2378 D 	version_info = 3.10.8.final.0 [virtualenv/create/pyenv_cfg.py:34]
flake8: 2378 D 	virtualenv = 20.17.1 [virtualenv/create/pyenv_cfg.py:34]
flake8: 2378 D 	include-system-site-packages = false [virtualenv/create/pyenv_cfg.py:34]
flake8: 2378 D 	base-prefix = /usr [virtualenv/create/pyenv_cfg.py:34]
flake8: 2378 D 	base-exec-prefix = /usr [virtualenv/create/pyenv_cfg.py:34]
flake8: 2378 D 	base-executable = /usr/bin/python3.10 [virtualenv/create/pyenv_cfg.py:34]
flake8: 2380 W install_deps> python -I -m pip install pytest [tox/tox_env/api.py:408]
Collecting pytest
  Using cached pytest-7.2.0-py3-none-any.whl (316 kB)
Collecting packaging
  Using cached packaging-22.0-py3-none-any.whl (42 kB)
Collecting pluggy<2.0,>=0.12
  Using cached pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Collecting attrs>=19.2.0
  Using cached attrs-22.1.0-py2.py3-none-any.whl (58 kB)
Collecting exceptiongroup>=1.0.0rc8
  Using cached exceptiongroup-1.0.4-py3-none-any.whl (14 kB)
Collecting tomli>=1.0.0
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting iniconfig
  Using cached iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Installing collected packages: iniconfig, tomli, pluggy, packaging, exceptiongroup, attrs, pytest
Successfully installed attrs-22.1.0 exceptiongroup-1.0.4 iniconfig-1.1.1 packaging-22.0 pluggy-1.0.0 pytest-7.2.0 tomli-2.0.1
flake8: 4208 I exit 0 (1.83 seconds) /home/tom/code/tox-test> python -I -m pip install pytest pid=660893 [tox/execute/api.py:275]
flake8: 4208 W commands[0]> pytest [tox/tox_env/api.py:408]
========================================================== test session starts ==========================================================
platform linux -- Python 3.10.8, pytest-7.2.0, pluggy-1.0.0
cachedir: .tox/flake8/.pytest_cache
rootdir: /home/tom/code/tox-test
collected 1 item

test_hello.py .                                                                                                                   [100%]

=========================================================== 1 passed in 0.00s ===========================================================
flake8: 4403 I exit 0 (0.19 seconds) /home/tom/code/tox-test> pytest pid=660921 [tox/execute/api.py:275]
  python3.10: OK (2.10=setup[1.90]+cmd[0.20] seconds)
  flake8: OK (2.16=setup[1.97]+cmd[0.19] seconds)
  congratulations :) (4.30 seconds)
```

## Minimal example

cat `hello.py`:
```python
print("hello world")
```
cat `test_hello.py`:
```python
def test_bogus():
    assert True
```
cat `tox.ini`:
```ini
[tox]
envlist =
    python3.10, flake8

[flake8]
extend-ignore = E501,W503

[testenv]
basepython = python3.10
deps =
    pytest
commands = pytest

[testenv:flake8]
deps =
    flake8
commands = flake8 -v hello.py
```

Run the test:
```console
$ tox -r
python3.10: remove tox env folder /home/tom/code/tox-test/.tox/python3.10
python3.10: install_deps> python -I -m pip install pytest
python3.10: commands[0]> pytest
========================================================== test session starts ==========================================================
platform linux -- Python 3.10.8, pytest-7.2.0, pluggy-1.0.0
cachedir: .tox/python3.10/.pytest_cache
rootdir: /home/tom/code/tox-test
collected 1 item

test_hello.py .                                                                                                                   [100%]

=========================================================== 1 passed in 0.00s ===========================================================
python3.10: OK ✔ in 2.11 seconds
flake8: remove tox env folder /home/tom/code/tox-test/.tox/flake8
flake8: install_deps> python -I -m pip install pytest
flake8: commands[0]> pytest
========================================================== test session starts ==========================================================
platform linux -- Python 3.10.8, pytest-7.2.0, pluggy-1.0.0
cachedir: .tox/flake8/.pytest_cache
rootdir: /home/tom/code/tox-test
collected 1 item

test_hello.py .                                                                                                                   [100%]

=========================================================== 1 passed in 0.00s ===========================================================
  python3.10: OK (2.10=setup[1.88]+cmd[0.22] seconds)
  flake8: OK (2.01=setup[1.81]+cmd[0.20] seconds)
  congratulations :) (4.15 seconds)
```

As you can see, the flake test is incorrect (and passes for the wrong reasons). Fortunately, in the actual, non-simplified setup, the `flake8` test failed miserably.

**Comment by jugmac00** [comment] 2022-12-12 14:48
Duplicate of #2636

**Closed by jugmac00** 2022-12-12 14:48 UTC
