### ISSUE TITLE
feature: virtualenv self-repair logic into tox

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/tox#501] opened 2017-04-05 10:08 UTC
Recreating the testing virtualenv for each build can be really time consuming and re-using the previous one is, most of the time, harmless. 

Still, there are cases when this environment can become broken like: when system python was updated or one of the system packages were updates. 

As far as I know there is no really safe way to validate a virtualenv but there is something else we can do: we can safe the result of the last execution in a placeholder file and next time we run, if if find the file we to reinitialize the virtualenvs. 

This could also also work as a failure counter and we could trigger the time-expensive recreation automatically when failure counter is above a specific threshold.

This approach should also benefit usage on developer machines, not only CI environments.

**Comment by obestwalter** [comment] 2017-04-05 10:16
@ssbarnea this sounds familiar ... I can't pinpoint it down to a concrete issue though. Did you have a look already if we have something along those lines floating around already?

**Comment by ssbarnea** [comment] 2017-04-05 10:30
@obestwalter I am still looking around, but I still have to fix some broken builds. Be sure that if I found anything I will add it here. Maybe there are reasons why this may not work the way I described it. 

For start I could try to implement it outside tox first and see what happens. At least this would allow me to validate the concept.

**Comment by asottile** [comment] 2017-05-01 04:02
This seems to be a duplicate of one or more of: #93 #149

**Comment by asottile** [comment] 2017-09-10 01:35
I've "solved" a similar problem [here](https://github.com/pre-commit/pre-commit/blob/3cc5aa023ed1068eca4f631fa29db112b8d1fc5e/pre_commit/languages/python.py#L86-L91)

It's not perfect, but it picks some of the more common modules which cause breakage due to OS upgrades / etc.

**Comment by merwok** [comment] 2017-09-14 17:00
@asottile I’ve had to recreate all virtualenvs after openssl changes a few times in the last couple years, you may want to add `ssl` to your imports.

**Comment by asottile** [comment] 2017-09-14 17:11
@mewok good idea: https://github.com/pre-commit/pre-commit/pull/619

**Comment by gaborbernat** [comment] 2022-01-13 10:14
I think this should now be fixed with version 4 (rewrite branch). If still reproducible please post it and we'll reopen it.

**Closed by gaborbernat** 2022-01-13 10:14 UTC
Labels: area:testenv-creation, level:hard, help:wanted
