### ISSUE TITLE
commands in [testenv] affects the isolated_build environment

### ISSUE THREAD

**Issue by brechtm** [tox-dev/tox#1882] opened 2021-01-28 22:19 UTC
My project has a _pyproject.toml_ and is packaged by Poetry. I have this tox.ini:

```ini
[tox]
envlist = check,unit,regression
isolated_build = true

[testenv]
setenv =
    unit:       TESTS_DIR = tests
    regression: TESTS_DIR = tests_regression
    regression: EXTRA = -m "not longrunning" --script-launch-mode=subprocess
commands =
    python run_tests.py {env:EXTRA:} {posargs} {env:TESTS_DIR}
```

Running the _unit_ env fails to build the sdist:
```
$ toxvenv/bin/tox -rvvve unit
using tox.ini: /Users/brechtm/Documents/Code/rinohtype/tox.ini (pid 9755)
using tox-3.21.3 from /Users/brechtm/Documents/Code/rinohtype/toxvenv/lib/python3.9/site-packages/tox/__init__.py (pid 9755)
/Users/brechtm/Documents/Code/rinohtype/toxvenv/bin/python (/Users/brechtm/Documents/Code/rinohtype/toxvenv/bin/python) is {'executable': '/Users/brechtm/Documents/Code/rinohtype/toxvenv/bin/python', 'implementation': 'CPython', 'version_info': [3, 9, 1, 'final', 0], 'version': '3.9.1 (default, Dec 22 2020, 01:02:13) \n[Clang 10.0.0 (clang-1000.11.45.5)]', 'is_64': True, 'sysplatform': 'darwin', 'extra_version_info': None}
.package uses /Users/brechtm/Documents/Code/rinohtype/toxvenv/bin/python
.package start: get-build-requires /Users/brechtm/Documents/Code/rinohtype/.tox/.package
setting PATH=/Users/brechtm/Documents/Code/rinohtype/.tox/.package/bin:/Users/brechtm/.poetry/bin:/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims:/Users/brechtm/.pyenv/shims:/usr/local/sbin:/Users/brechtm/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Users/brechtm/.nimble/bin
ERROR: invocation failed (exit code 2), logfile: /Users/brechtm/Documents/Code/rinohtype/.tox/.package/log/.package-0.log
============================================ log start =============================================

============================================= log end ==============================================
ERROR: FAIL could not package project - v = InvocationError("/Users/brechtm/Documents/Code/rinohtype/.tox/.package/bin/python toxvenv/lib/python3.9/site-packages/tox/helper/build_requires.py poetry.core.masonry.api '' ''", 2)
```

The log doesn't provide any hints:
```
$ cat .tox/.package/log/.package-0.log
action: .package, msg: get-build-requires
cwd: /Users/brechtm/Documents/Code/rinohtype
cmd: /Users/brechtm/Documents/Code/rinohtype/.tox/.package/bin/python toxvenv/lib/python3.9/site-packages/tox/helper/build_requires.py poetry.core.masonry.api '' ''
```

Providing a default for `{env:TESTS_DIR` in the command "fixes" this issue:
```
    python run_tests.py {env:EXTRA:} {posargs} {env:TESTS_DIR:}
```

**Comment by jayvdb** [comment] 2021-01-29 08:47
You may want to try [v3.20.1](https://github.com/tox-dev/tox/releases/tag/3.20.1).  There is a chance that this is related to one of the changes since then, several of which have touched handling of `posargs` and `setenv`.  I'll do this regression check, and help fix it, over the weekend, if nobody beats me to it.

**Comment by brechtm** [comment] 2021-01-29 09:28
Nope, I see the same thing with v3.20.1.

**Comment by gaborbernat** [comment] 2021-02-27 13:47
This has been fixed in the rewrite branch, so will close this now.

**Closed by gaborbernat** 2021-02-27 13:47 UTC
Labels: bug:normal
