### ISSUE TITLE
Help Needed:   File "__init__.py", line 25, in get_executable return self.name2executable[envconfig.envname] KeyError: 'docs'

### ISSUE THREAD

**Issue by vishalpandeyvip** [tox-dev/tox#2194] opened 2021-08-31 20:51 UTC
I am new to tox. currently, I am working on [django-local flavor](https://github.com/django/django-localflavor) to make my first pull request for Open Source Contribution, while testing packages of django-localflavor I faced the issue mentioned above.
while trying to solve my problem I came across these issues #1454 and #1704 But It didn't helped me much. Can anyone please help me with this issue?

Other details:
OS: Windows 10
Python version : 3.8.0
pip version: 20.0.2
Pip list:
<pre>
asgiref                           3.4.1  
backports.entry-points-selectable 1.1.0  
colorama                          0.4.4  
distlib                           0.3.2  
Django                            3.2.6  
filelock                          3.0.12 
packaging                         21.0   
pip                               20.0.2 
platformdirs                      2.3.0  
pluggy                            1.0.0  
py                                1.10.0 
pyparsing                         2.4.7  
pytz                              2021.1 
setuptools                        46.0.0 
six                               1.16.0 
sqlparse                          0.4.1  
toml                              0.10.2 
tox                               3.24.3 
virtualenv                        20.7.2 
wheel                             0.34.2 
</pre>

Full traceback
<pre>
________________________________________________________________________________________ summary _________________________________________________________________________________________
ERROR:   docs: undefined      
ERROR:   prospector: undefined
ERROR:   py35-2.2: undefined  
ERROR:   py36-2.2: undefined  
ERROR:   py37-2.2: undefined  
ERROR:   py38-2.2: undefined  
ERROR:   pypy3-2.2: undefined 
ERROR:   py36-3.0: undefined  
ERROR:   py37-3.0: undefined  
ERROR:   py38-3.0: undefined  
ERROR:   pypy3-3.0: undefined 
ERROR:   py36-3.1: undefined  
ERROR:   py37-3.1: undefined  
ERROR:   py38-3.1: undefined  
ERROR:   pypy3-3.1: undefined 
ERROR:   py36-3.2: undefined  
ERROR:   py37-3.2: undefined
ERROR:   py38-3.2: undefined
ERROR:   py39-3.2: undefined
ERROR:   pypy3-3.2: undefined
ERROR:   py38-main: undefined
ERROR:   py39-main: undefined
ERROR:   pypy3-main: undefined
Traceback (most recent call last):
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\interpreters\__init__.py", line 25, in get_executable
    return self.name2executable[envconfig.envname]
KeyError: 'docs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\asus\appdata\local\programs\python\python38-32\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\asus\appdata\local\programs\python\python38-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Asus\Envs\localflavor\Scripts\tox.exe\__main__.py", line 7, in <module>
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\session\__init__.py", line 44, in cmdline
    main(args)
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\session\__init__.py", line 69, in main
    exit_code = session.runcommand()
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\session\__init__.py", line 197, in runcommand
    return self.subcommand_test()
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\session\__init__.py", line 225, in subcommand_test
    run_sequential(self.config, self.venv_dict)
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\session\commands\run\sequential.py", line 9, in run_sequential
    if venv.setupenv():
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\venv.py", line 621, in setupenv
    with self.new_action("getenv", self.envconfig.envdir) as action:
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\venv.py", line 135, in new_action
    self.envconfig.envpython,
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\config\__init__.py", line 1042, in __getattribute__
    rv = object.__getattribute__(self, name)
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\config\__init__.py", line 1080, in envpython
    return self.get_envpython()
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\config\__init__.py", line 1088, in get_envpython
    return self.envbindir.join(name)
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\config\__init__.py", line 1042, in __getattribute__
    rv = object.__getattribute__(self, name)
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\config\__init__.py", line 1075, in envbindir
    return self.get_envbindir()
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\config\__init__.py", line 1057, in get_envbindir
    isinstance(self.python_info, NoInterpreterInfo)
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\config\__init__.py", line 1042, in __getattribute__
    rv = object.__getattribute__(self, name)
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\config\__init__.py", line 1101, in python_info
    return self.config.interpreters.get_info(envconfig=self)
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\interpreters\__init__.py", line 33, in get_info
    executable = self.get_executable(envconfig)
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\interpreters\__init__.py", line 27, in get_executable
    exe = self.hook.tox_get_python_executable(envconfig=envconfig)
  File "c:\users\asus\envs\localflavor\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "c:\users\asus\envs\localflavor\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "c:\users\asus\envs\localflavor\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "c:\users\asus\envs\localflavor\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\users\asus\envs\localflavor\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\interpreters\windows\__init__.py", line 19, in tox_get_python_executable
    py_exe = locate_via_pep514(spec)
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\interpreters\windows\__init__.py", line 45, in locate_via_pep514
    _PY_AVAILABLE.extend(pep514.discover_pythons())
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\interpreters\windows\pep514.py", line 49, in discover_pythons
    for spec in process_set(hive, hive_name, key, flags, default_arch):
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\interpreters\windows\pep514.py", line 59, in process_set
    for spec in process_company(hive_name, company, root_key, default_arch):
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\interpreters\windows\pep514.py", line 68, in process_company
    for spec in process_tag(hive_name, company, company_key, tag, default_arch):
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\interpreters\windows\pep514.py", line 78, in process_tag
    exe, args = load_exe(hive_name, company, company_key, tag)
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\interpreters\windows\pep514.py", line 97, in load_exe
    if os.path.exists(exe):
  File "c:\users\asus\appdata\local\programs\python\python38-32\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType`
</pre>
Please let me know if you need more details.

**Comment by vishalpandeyvip** [comment] 2021-08-31 20:55
tox.ini file
<pre>
[tox]
args_are_paths = false
envlist =
    docs,prospector
    {py35,py36,py37,py38,pypy3}-2.2
    {py36,py37,py38,pypy3}-3.0
    {py36,py37,py38,pypy3}-3.1
    {py36,py37,py38,py39,pypy3}-3.2
    {py38,py39,pypy3}-main

[testenv]
basepython =
    py35: python3.5
    py36: python3.6
    py37: python3.7
    py38: python3.8
    py39: python3.9
    pypy3: pypy3
usedevelop = true
pip_pre = true
commands =
    invoke test {posargs}
deps =
    2.2: Django>=2.2,<2.3
    3.0: Django>=3.0,<3.1
    3.1: Django>=3.1,<3.2
    3.2: Django>=3.2,<3.3
    main: https://github.com/django/django/archive/main.tar.gz
    -r{toxinidir}/tests/requirements.txt

[testenv:docs]
deps =
    Sphinx>=1.3
    -r{toxinidir}/docs/requirements.txt
basepython = python3.9
commands =
    sphinx-build -W -b html -d {envtmpdir}/doctrees docs docs/_build/html

[testenv:prospector]
deps =
    prospector==1.3.0
    pylint>=2.5.2,<2.6.0
    -r{toxinidir}/tests/requirements.txt
basepython = python3.8
commands = prospector --profile .prospector.yaml {toxinidir}
</pre>

**Comment by vishalpandeyvip** [comment] 2021-09-01 03:22
How could I help with you reproducing this issue? @gaborbernat

**Comment by vishalpandeyvip** [comment] 2021-09-01 04:21
How may I help you in reproducing this issue? @gaborbernat

**Comment by jugmac00** [comment] 2021-09-01 06:53
We need to know how you called `tox` - please do a `tox -rvv` and paste the **complete** output - as mentioned in the issue template.

**Comment by gaborbernat** [comment] 2021-09-01 08:22
Feels like a bug in our PEP-514 interpreter discovery. You seem to have a malformed registry entry somehow, and we don't ignore it but fail with the above not that descriptive message. See the relevant part:

```
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\interpreters\windows\__init__.py", line 19, in tox_get_python_executable
    py_exe = locate_via_pep514(spec)
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\interpreters\windows\__init__.py", line 45, in locate_via_pep514
    _PY_AVAILABLE.extend(pep514.discover_pythons())
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\interpreters\windows\pep514.py", line 49, in discover_pythons
    for spec in process_set(hive, hive_name, key, flags, default_arch):
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\interpreters\windows\pep514.py", line 59, in process_set
    for spec in process_company(hive_name, company, root_key, default_arch):
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\interpreters\windows\pep514.py", line 68, in process_company
    for spec in process_tag(hive_name, company, company_key, tag, default_arch):
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\interpreters\windows\pep514.py", line 78, in process_tag
    exe, args = load_exe(hive_name, company, company_key, tag)
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\interpreters\windows\pep514.py", line 97, in load_exe
    if os.path.exists(exe):
  File "c:\users\asus\appdata\local\programs\python\python38-32\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType`
```

For what it's worth, this should not be an issue with tox 4, as that uses virtualenv logic, which should be a bit more robust (hopefully).

**Comment by vishalpandeyvip** [comment] 2021-09-01 10:02
I followed this [contributing guideline](https://github.com/django/django-localflavor/blob/master/CONTRIBUTING.rst) and got the above traceback when I simply run `tox` on my VS Code terminal.

This is complete traceback when I run `tox -rvv` on my terminal.
<pre>
using tox.ini: D:\open-source\django-localflavor\tox.ini (pid 9600)
  removing D:\open-source\django-localflavor\.tox\log
using tox-3.24.3 from c:\users\asus\envs\localflavor\lib\site-packages\tox\__init__.py (pid 9600)
skipping sdist step
PEP-514 violation in Windows Registry at HKEY_CURRENT_USER/ContinuumAnalytics/Anaconda37-64 error: exe does not exists C:\Users\Asus\miniconda3\python.exe
PEP-514 violation in Windows Registry at HKEY_CURRENT_USER/PythonCore/3.5-32 error: no ExecutablePath or default for it
____________________________________________________________________________________________ summary _____________________________________________________________________________________________ 
ERROR:   docs: undefined
ERROR:   prospector: undefined
ERROR:   py35-2.2: undefined
ERROR:   py36-2.2: undefined
ERROR:   py37-2.2: undefined
ERROR:   py38-2.2: undefined
ERROR:   pypy3-2.2: undefined
ERROR:   py36-3.0: undefined
ERROR:   py37-3.0: undefined
ERROR:   py38-3.0: undefined
ERROR:   pypy3-3.0: undefined
ERROR:   py36-3.1: undefined
ERROR:   py37-3.1: undefined
ERROR:   py38-3.1: undefined
ERROR:   pypy3-3.1: undefined
ERROR:   py36-3.2: undefined
ERROR:   py37-3.2: undefined
ERROR:   py38-3.2: undefined
ERROR:   py39-3.2: undefined
ERROR:   pypy3-3.2: undefined
ERROR:   py38-main: undefined
ERROR:   py39-main: undefined
ERROR:   pypy3-main: undefined
Traceback (most recent call last):
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\interpreters\__init__.py", line 25, in get_executable
    return self.name2executable[envconfig.envname]
KeyError: 'docs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\asus\appdata\local\programs\python\python38-32\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\asus\appdata\local\programs\python\python38-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Asus\Envs\localflavor\Scripts\tox.exe\__main__.py", line 7, in <module>
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\session\__init__.py", line 44, in cmdline
    main(args)
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\session\__init__.py", line 69, in main
    exit_code = session.runcommand()
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\session\__init__.py", line 197, in runcommand
    return self.subcommand_test()
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\session\__init__.py", line 225, in subcommand_test
    run_sequential(self.config, self.venv_dict)
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\session\commands\run\sequential.py", line 9, in run_sequential
    if venv.setupenv():
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\venv.py", line 621, in setupenv
    with self.new_action("getenv", self.envconfig.envdir) as action:
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\venv.py", line 135, in new_action
    self.envconfig.envpython,
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\config\__init__.py", line 1042, in __getattribute__
    rv = object.__getattribute__(self, name)
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\config\__init__.py", line 1080, in envpython
    return self.get_envpython()
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\config\__init__.py", line 1088, in get_envpython
    return self.envbindir.join(name)
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\config\__init__.py", line 1042, in __getattribute__
    rv = object.__getattribute__(self, name)
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\config\__init__.py", line 1075, in envbindir
    return self.get_envbindir()
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\config\__init__.py", line 1057, in get_envbindir
    isinstance(self.python_info, NoInterpreterInfo)
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\config\__init__.py", line 1042, in __getattribute__
    rv = object.__getattribute__(self, name)
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\config\__init__.py", line 1101, in python_info
    return self.config.interpreters.get_info(envconfig=self)
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\interpreters\__init__.py", line 33, in get_info
    executable = self.get_executable(envconfig)
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\interpreters\__init__.py", line 27, in get_executable
    exe = self.hook.tox_get_python_executable(envconfig=envconfig)
  File "c:\users\asus\envs\localflavor\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "c:\users\asus\envs\localflavor\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "c:\users\asus\envs\localflavor\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "c:\users\asus\envs\localflavor\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\users\asus\envs\localflavor\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\interpreters\windows\__init__.py", line 19, in tox_get_python_executable
    py_exe = locate_via_pep514(spec)
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\interpreters\windows\__init__.py", line 45, in locate_via_pep514
    _PY_AVAILABLE.extend(pep514.discover_pythons())
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\interpreters\windows\pep514.py", line 49, in discover_pythons
    for spec in process_set(hive, hive_name, key, flags, default_arch):
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\interpreters\windows\pep514.py", line 59, in process_set
    for spec in process_company(hive_name, company, root_key, default_arch):
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\interpreters\windows\pep514.py", line 68, in process_company
    for spec in process_tag(hive_name, company, company_key, tag, default_arch):
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\interpreters\windows\pep514.py", line 78, in process_tag
    exe, args = load_exe(hive_name, company, company_key, tag)
  File "c:\users\asus\envs\localflavor\lib\site-packages\tox\interpreters\windows\pep514.py", line 97, in load_exe
    if os.path.exists(exe):
  File "c:\users\asus\appdata\local\programs\python\python38-32\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType.
</pre>

Please let me know if you need more details. @gaborbernat  @jugmac00

**Comment by gaborbernat** [comment] 2021-09-01 10:10
@vishalpandeyvip see my comment above, we did not need this here. However, the issue is not easy to reproduce and will be fixed by tox 4, so unless you have time to debug into it unlikely will get traction.

**Comment by jugmac00** [comment] 2021-09-08 18:02
@vishalpandeyvip  Any chance you try to reproduce the issue with the alpha version of tox4?

https://pypi.org/project/tox/4.0.0a8/

For how to install pre-releases, please see https://jugmac00.github.io/til/how-to-install-release-candidates/

**Comment by gaborbernat** [comment] 2021-09-09 09:46
Closing due to lack of response.

**Closed by gaborbernat** 2021-09-09 09:46 UTC
Labels: bug:normal
