### ISSUE TITLE
tox shell completion is not documented or working

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/tox#1750] opened 2020-11-24 12:12 UTC
At this moment shell completion for tox seems to be a trade secret as:

* no mention on README
* no mention on `tox --help`
* no mention on full documentation
* no mention of [project docs](https://tox.readthedocs.io/en/latest/search.html?q=shell+completion&check_keywords=yes&area=default)

We clearly need to document how to enable shell completion for at least ``bash`` and ``zsh`` as these are the default shells across supported platforms.

For example other tools expose the fact that user can enable shell completion when called with ``--help``, example output:

```
  Enable autocomplete issue:

    eval "$(_MOLECULE_COMPLETE=source molecule)"
```

Would it be possible to have the same for tox?

**Comment by gaborbernat** [comment] 2020-11-24 15:56
We can do this, but I consider this a feature, not a bug.

**Comment by ssbarnea** [comment] 2020-11-24 15:58
Thanks. I would have raised the PR directly but I wasn't able to find how to do it yet.

**Comment by gaborbernat** [comment] 2020-11-24 16:07
Duplicate of https://github.com/tox-dev/tox/issues/918

**Closed by gaborbernat** 2020-11-24 16:07 UTC
Labels: feature:new
