### ISSUE TITLE
tox4: typing error in add_config with factory and container types

### ISSUE THREAD

**Issue by dcrosta** [tox-dev/tox#2240] opened 2021-10-01 14:36 UTC
With this code

```python
class EnvDockerConfigSet(ConfigSet):
    def register_config(self) -> None:
        def build_docker_config_set(container_name: object) -> DockerConfigSet:
            assert isinstance(container_name, str)
            return self._conf.get_section_config(
                section=Section("docker", container_name),
                base=[],
                of_type=DockerConfigSet,
                for_env=None,
            )

        self.add_config(
            keys=["docker"],
            of_type=List[DockerConfigSet],
            default=[],
            desc="docker image configs to load",
            factory=build_docker_config_set,
        )
```

I get this mypy error:

```
tox_docker/tox4/config.py:124: error: Argument "factory" to "add_config" of "ConfigSet" has incompatible type "Callable[[object], DockerConfigSet]"; expected "Optional[Callable[[object], List[DockerConfigSet]]]"
Found 1 error in 1 file (checked 19 source files)
```

The code seems to actually do the right thing -- call the `factory` for each element of the list, so I think this is just a typing error, not a correctness bug.

As a work-around, adding `# type: ignore` on the `factory=...` line of that code sample silences the mypy error, but obviously at the cost of typechecking...

**Comment by gaborbernat** [comment] 2021-10-01 14:39
Duplicate of https://github.com/tox-dev/tox/issues/2233

**Closed by gaborbernat** 2021-10-01 14:39 UTC
Labels: bug:normal

**Comment by dcrosta** [comment] 2021-10-01 14:40
Oh sorry, didn't realize you had created this already!

**Comment by gaborbernat** [comment] 2021-10-01 15:47
No worries 👍
