### ISSUE TITLE
pip interactive credential prompt hangs tox

### ISSUE THREAD

**Issue by davidszotten** [tox-dev/tox#2042] opened 2021-04-21 12:44 UTC
if pip-index-url is set to an index that uses basicauth (without including credentials), pip pauses and asks for credentials interactively.  with `tox -vv` this is presented to the caller, but with lower verbosity, tox just hangs

**Comment by gaborbernat** [comment] 2021-04-21 13:13
tox is an automation tool in general. So interactive authentication entry is out of scope as is today. This is less of a bug, more of a lack of feature. One could make an argument to add this support though, so PRs welcome (the fact it works via `tox -vv` is by chance, not by design).

**Comment by davidszotten** [comment] 2021-04-21 13:35
sure, i was expecting it to error rather than hang though

before i noticed that it worked with `-vv` my plan was to set stdin to `devnull` in the subprocess call. thoughts?

**Comment by gaborbernat** [comment] 2021-04-21 13:41
> before i noticed that it worked with `-vv` my plan was to set stdin to `devnull` in the subprocess call. thoughts?

You'd have to try, but my guess is that it would break many existing tests and use cases...

**Comment by davidszotten** [comment] 2021-04-21 13:56
what are the use-cases for giving stdin to the pip subprocess? or do you mean folks relying on the behaviour above with vv?

**Comment by gaborbernat** [comment] 2021-04-21 14:20
Can't tell you from the top of my head. But someone might be relying on some behavior and with this change break them.

**Comment by davidszotten** [comment] 2021-04-21 14:25
oh, it's fixed in tox 4. already doesn't allow using stdin

**Comment by gaborbernat** [comment] 2021-04-21 14:27
Yeah, we're a bit laxer with breaking things there.

**Comment by davidszotten** [comment] 2021-04-21 14:49
ok. i guess we can close this then. thanks for the quick replies!

**Closed** 2021-04-21 14:58 UTC
Labels: feature:new
