### ISSUE TITLE
UnicodeDecodeError on line 100 of execute/stream.py

### ISSUE THREAD

**Issue by julzt0244** [tox-dev/tox#2422] opened 2022-05-19 12:53 UTC
Currently using Version: 4.0.0b2 on Windows, and getting an error whereby Tox is trying to decode everything using "utf-8" alone while there might be other valid encodings as well.

This is the problematic line for me that happened on Windows:
Line 100 onwards of "execute/stream.py"
```
    @property
    def text(self) -> str:
        with self._content_lock:
            return self._content.decode("utf-8")
```
            
When using breakpoint() there it seems that it will produce a UnicodeDecodeError with one of the self._content having an encoding of "Windows-1252" if I use the chardet library to detect it.

My own personal patch is modifying the function this way but I suppose a more elegant fix can be put in by someone else hopefully:

```
import chardet
...
...

    @property
    def text(self) -> str:
        with self._content_lock:
            encoding_detected: str | None = chardet.detect(self._content).get('encoding')
            if encoding_detected:
                return self._content.decode(encoding_detected)
            return self._content.decode('utf-8')
```

**Comment by jugmac00** [comment] 2022-06-02 07:14
Thanks for your report. This looks like a release blocker for me.

@gaborbernat What is your take on the patch?

**Comment by jugmac00** [comment] 2022-06-04 06:50
@julzt0244 Would you like to create a pull request with your fix? This would also require a test which reproduces the issue / covers the new code, and a short news entry.

**Comment by gaborbernat** [comment] 2022-06-04 06:53
Let's hold with that, I'm not sure thats' the path ahead. Guessing the encoding is never the good path ahead if you can just tell.

**Comment by jugmac00** [comment] 2022-06-04 07:05
> Let's hold with that, I'm not sure thats' the path ahead. Guessing the encoding is never the good path ahead if you can just tell.

Ok. I guess I misinterpreted your thumbs up in https://github.com/tox-dev/tox/issues/2422#issuecomment-1144528500

**Comment by jugmac00** [comment] 2022-12-06 15:33
@gaborbernat What do you think about this issue? If we do nothing we might release a broken tox for Windows, right? Or do I miss something?

**Comment by gaborbernat** [comment] 2022-12-06 17:43
I can't replicate this, so it's not widely enough spread to be release blocker.

**Comment by julzt0244** [comment] 2022-12-06 21:44
Can we perhaps have the default behaviour under a try block then the exception block can use chardet above then?

**Comment by gaborbernat** [comment] 2022-12-06 21:55
Without a test and replication I don't want to add changes just in case helps.

**Comment by julzt0244** [comment] 2022-12-06 22:09
Fair enough. I assume you've manually created a file with the "Windows-1252" encoding (on Windows) and try parsing it? I've stopped using Tox since this bug so will take me time to set it up again from scratch

**Comment by maxnoe** [comment] 2022-12-08 12:10
Shouldn't the `"utf-8"` just be replaced with `sys.getdefaultencoding()`?

**Comment by maxnoe** [comment] 2022-12-08 12:20
Using chardet is only a last resort. You should be able to *know* the encoding of the stream you are working on.

**Comment by maxnoe** [comment] 2022-12-08 16:14
This can be fixed by encluding

```
setenv = 
    PYTHONIOENCODING=utf-8
```

for the envs in `tox.ini`

**Closed** 2022-12-08 16:40 UTC
Labels: bug:normal, help:wanted
