### ISSUE TITLE
New version of tox does not see environment variables

### ISSUE THREAD

**Issue by Mhoian** [tox-dev/tox#2659] opened 2022-12-09 07:51 UTC
## Issue

Describe what's the expected behaviour and what you're observing.

Today I started my regression with tests, there no changes in the tox file, and I got an error:

tests\integration\conftest.py:84: in <module>
    __parse()
tests\integration\conftest.py:63: in __parse
    raise Exception(
E   Exception: PPE_DESKTOP_APP_KEY is not an env variable, 'PPE_DESKTOP_APP_KEY'.

Also I removed current tox version 4.0.3 then instaled 3.27.1 and everything works
 

Provide at least:

- Linux, Windows:
- `pip list` of the host Python where `tox` is installed:

**Comment by jugmac00** [comment] 2022-12-09 09:18
I am afraid we need more information.

Is your repository available on the internet? If so, please provide a link.

Also please provide your `tox.ini` and the output of `tox -rvv` as requested in the issue template.

Thank you!

**Comment by Mhoian** [comment] 2022-12-09 09:31
Hi @jugmac00  just try to use in the tox env variable and you will able to reproduce this issue. My repository is not a public. I have i tox a lot confidential information

**Comment by eigenein** [comment] 2022-12-09 11:58
I'm not sure whether this is relevant, but we've faced a similar issue.

The `os.environ` inside `setup.py` seems completely isolated from the outer environment. Among others, the inner environment doesn't include `$HOME`, and that makes our builds fail: build backend seems to check for configuration in user's home directory. But there isn't one, and since our Docker container is running under a different UID, `gethomedir` just fails:

```
[2022-12-08T15:23:24.712Z] venv/bin/tox -e py39 
[2022-12-08T15:23:27.994Z] py39: install_deps> pip install -r requirements.txt
[2022-12-08T15:24:49.392Z] .pkg: install_requires> python -I -m pip install 'setuptools>=42' 'setuptools_scm[toml]>=3.4' wheel
[2022-12-08T15:24:49.392Z] .pkg: _optional_hooks> python /home/jenkins/masters/team/workspace/PR/venv/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
[2022-12-08T15:24:49.956Z] .pkg: get_requires_for_build_sdist> python /home/jenkins/masters/team/workspace/PR/venv/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
[2022-12-08T15:24:49.956Z] py39: packaging backend failed (code=1), with KeyError: 'getpwuid(): uid not found: 45001'
[2022-12-08T15:24:49.956Z] Traceback (most recent call last):
[2022-12-08T15:24:49.956Z]   File "/usr/local/lib/python3.9/pathlib.py", line 387, in gethomedir
[2022-12-08T15:24:49.956Z]     return os.environ['HOME']
[2022-12-08T15:24:49.956Z]   File "/usr/local/lib/python3.9/os.py", line 679, in __getitem__
[2022-12-08T15:24:49.956Z]     raise KeyError(key) from None
[2022-12-08T15:24:49.956Z] KeyError: 'HOME'
[2022-12-08T15:24:49.956Z] 
[2022-12-08T15:24:49.956Z] During handling of the above exception, another exception occurred:
[2022-12-08T15:24:49.956Z] 
[2022-12-08T15:24:49.956Z] Traceback (most recent call last):
[2022-12-08T15:24:49.956Z]   File "/home/jenkins/masters/team/workspace/PR/venv/lib/python3.9/site-packages/pyproject_api/_backend.py", line 90, in run
[2022-12-08T15:24:49.956Z]     outcome = backend_proxy(parsed_message["cmd"], **parsed_message["kwargs"])
[2022-12-08T15:24:49.956Z]   File "/home/jenkins/masters/team/workspace/PR/venv/lib/python3.9/site-packages/pyproject_api/_backend.py", line 32, in __call__
[2022-12-08T15:24:49.956Z]     return getattr(on_object, name)(*args, **kwargs)
[2022-12-08T15:24:49.956Z]   File "/home/jenkins/masters/team/workspace/PR/.tox/.pkg/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_sdist
[2022-12-08T15:24:49.956Z]     return self._get_build_requires(config_settings, requirements=[])
[2022-12-08T15:24:49.956Z]   File "/home/jenkins/masters/team/workspace/PR/.tox/.pkg/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
[2022-12-08T15:24:49.956Z]     self.run_setup()
[2022-12-08T15:24:49.956Z]   File "/home/jenkins/masters/team/workspace/PR/.tox/.pkg/lib/python3.9/site-packages/setuptools/build_meta.py", line 484, in run_setup
[2022-12-08T15:24:49.956Z]     super(_BuildMetaLegacyBackend,
[2022-12-08T15:24:49.956Z]   File "/home/jenkins/masters/team/workspace/PR/.tox/.pkg/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
[2022-12-08T15:24:49.956Z]     exec(code, locals())
[2022-12-08T15:24:49.956Z]   File "<string>", line 18, in <module>
[2022-12-08T15:24:49.956Z]   File "/home/jenkins/masters/team/workspace/PR/.tox/.pkg/lib/python3.9/site-packages/setuptools/__init__.py", line 86, in setup
[2022-12-08T15:24:49.956Z]     _install_setup_requires(attrs)
[2022-12-08T15:24:49.956Z]   File "/home/jenkins/masters/team/workspace/PR/.tox/.pkg/lib/python3.9/site-packages/setuptools/__init__.py", line 78, in _install_setup_requires
[2022-12-08T15:24:49.956Z]     dist.parse_config_files(ignore_option_errors=True)
[2022-12-08T15:24:49.956Z]   File "/home/jenkins/masters/team/workspace/PR/.tox/.pkg/lib/python3.9/site-packages/_virtualenv.py", line 21, in parse_config_files
[2022-12-08T15:24:49.956Z]     result = old_parse_config_files(self, *args, **kwargs)
[2022-12-08T15:24:49.956Z]   File "/home/jenkins/masters/team/workspace/PR/.tox/.pkg/lib/python3.9/site-packages/setuptools/dist.py", line 861, in parse_config_files
[2022-12-08T15:24:49.956Z]     self._parse_config_files(filenames=inifiles)
[2022-12-08T15:24:49.956Z]   File "/home/jenkins/masters/team/workspace/PR/.tox/.pkg/lib/python3.9/site-packages/setuptools/dist.py", line 703, in _parse_config_files
[2022-12-08T15:24:49.956Z]     filenames = self.find_config_files()
[2022-12-08T15:24:49.956Z]   File "/home/jenkins/masters/team/workspace/PR/.tox/.pkg/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 338, in find_config_files
[2022-12-08T15:24:49.956Z]     files = [str(path) for path in self._gen_paths() if os.path.isfile(path)]
[2022-12-08T15:24:49.956Z]   File "/home/jenkins/masters/team/workspace/PR/.tox/.pkg/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 338, in <listcomp>
[2022-12-08T15:24:49.956Z]     files = [str(path) for path in self._gen_paths() if os.path.isfile(path)]
[2022-12-08T15:24:49.956Z]   File "/home/jenkins/masters/team/workspace/PR/.tox/.pkg/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 354, in _gen_paths
[2022-12-08T15:24:49.956Z]     yield pathlib.Path('~').expanduser() / filename
[2022-12-08T15:24:49.956Z]   File "/usr/local/lib/python3.9/pathlib.py", line 1572, in expanduser
[2022-12-08T15:24:49.956Z]     homedir = self._flavour.gethomedir(self._parts[0][1:])
[2022-12-08T15:24:49.956Z]   File "/usr/local/lib/python3.9/pathlib.py", line 390, in gethomedir
[2022-12-08T15:24:49.956Z]     return pwd.getpwuid(os.getuid()).pw_dir
[2022-12-08T15:24:49.956Z] KeyError: 'getpwuid(): uid not found: 45001'
```

**Comment by eigenein** [comment] 2022-12-09 12:16
Please, disregard that. We could fix it by:

```ini
[testenv:.pkg]
passenv = HOME
```

Maybe my comment will still be helpful for others.

**Comment by Saransh-cpp** [comment] 2022-12-09 14:38
The solution mentioned above works! Thank you!

Should this be added here - https://tox--2601.org.readthedocs.build/en/2601/faq.html#breaking-changes-in-tox-4?

**Comment by Mhoian** [comment] 2022-12-09 14:42
I used to do this before, but now it doesn't work.

**Comment by gaborbernat** [comment] 2022-12-09 15:34
Duplicate of https://github.com/tox-dev/tox/issues/2543

**Closed by gaborbernat** 2022-12-09 15:34 UTC
